import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * EFB 模块国际化
 *
 * 门限名（gate.*）与飞行阶段名（phase.*）的 key 与 `services/efb-gates.ts`
 * 里的 id 一一对应 —— 加门限时两边都要动。
 */
export const EfbLocalizationKeys = {
  navTitle: 'efb.nav_title',
  pageTitle: 'efb.page_title',
  pageSubtitle: 'efb.page_subtitle',

  sectionPhase: 'efb.section.phase',
  sectionGates: 'efb.section.gates',
  sectionFuel: 'efb.section.fuel',
  sectionNearby: 'efb.section.nearby',

  disconnected: 'efb.disconnected',
  noGates: 'efb.no_gates',
  refresh: 'efb.refresh',
  loading: 'efb.loading',
  lastUpdated: 'efb.last_updated',
  columnValue: 'efb.column.value',
  columnLimit: 'efb.column.limit',

  fuelOnboard: 'efb.fuel.onboard',
  fuelFlow: 'efb.fuel.flow',
  fuelEndurance: 'efb.fuel.endurance',
  fuelBurnToDest: 'efb.fuel.burn_to_dest',
  fuelAtDest: 'efb.fuel.at_dest',
  fuelReserve: 'efb.fuel.reserve',
  fuelMargin: 'efb.fuel.margin',
  fuelStatusOk: 'efb.fuel.status_ok',
  fuelStatusWatch: 'efb.fuel.status_watch',
  fuelStatusCritical: 'efb.fuel.status_critical',
  fuelStatusUnknown: 'efb.fuel.status_unknown',

  nearbyEmpty: 'efb.nearby.empty',
  nearbyStale: 'efb.nearby.stale',
  nearbyNoMetar: 'efb.nearby.no_metar',

  phaseUnknown: 'efb.phase.unknown',
  phaseParked: 'efb.phase.parked',
  phaseTaxi: 'efb.phase.taxi',
  phaseTakeoff: 'efb.phase.takeoff',
  phaseClimb: 'efb.phase.climb',
  phaseCruise: 'efb.phase.cruise',
  phaseDescent: 'efb.phase.descent',
  phaseApproach: 'efb.phase.approach',
  phaseLanding: 'efb.phase.landing',

  gateTaxiSpeed: 'efb.gate.taxi_speed',
  gateParkingBrake: 'efb.gate.parking_brake',
  gateFlaps: 'efb.gate.flaps',
  gateGearDown: 'efb.gate.gear_down',
  gateElevatorTrim: 'efb.gate.elevator_trim',
  gateSpeedBelow10000: 'efb.gate.speed_below_10000',
  gateClimbRate: 'efb.gate.climb_rate',
  gateMach: 'efb.gate.mach',
  gateVerticalDeviation: 'efb.gate.vertical_deviation',
  gateAutopilot: 'efb.gate.autopilot',
  gateDescentRate: 'efb.gate.descent_rate',
  gateSpeedBrake: 'efb.gate.speed_brake',
  gateSinkRate: 'efb.gate.sink_rate',
  gateBankAngle: 'efb.gate.bank_angle',
  gateFlapsDeployed: 'efb.gate.flaps_deployed',
  gateTouchdownG: 'efb.gate.touchdown_g',
  gateSpoilers: 'efb.gate.spoilers',
  gateReverseReady: 'efb.gate.reverse_ready',
} as const;

const K = EfbLocalizationKeys;

export const efbTranslations: ModuleTranslations = {
  zh_CN: {
    [K.navTitle]: '飞行卡',
    [K.pageTitle]: 'EFB 飞行卡',
    [K.pageSubtitle]: '一屏看清当前阶段、关键门限、近场气象与油量余度',

    [K.sectionPhase]: '飞行阶段',
    [K.sectionGates]: '关键门限',
    [K.sectionFuel]: '油量余度',
    [K.sectionNearby]: '近场机场与气象',

    [K.disconnected]: '未连接模拟器，飞行卡暂无数据',
    [K.noGates]: '当前阶段无需盯门限',
    [K.refresh]: '刷新',
    [K.loading]: '加载中…',
    [K.lastUpdated]: '更新于 {}',
    [K.columnValue]: '实测',
    [K.columnLimit]: '判据',

    [K.fuelOnboard]: '机上剩油',
    [K.fuelFlow]: '当前流量',
    [K.fuelEndurance]: '续航时间',
    [K.fuelBurnToDest]: '至目的地耗油',
    [K.fuelAtDest]: '落地预计剩油',
    [K.fuelReserve]: '最低储备',
    [K.fuelMargin]: '余量',
    [K.fuelStatusOk]: '余量充裕',
    [K.fuelStatusWatch]: '接近储备线',
    [K.fuelStatusCritical]: '已低于最低储备',
    [K.fuelStatusUnknown]: '数据不足，无法评估',

    [K.nearbyEmpty]: '附近没有可用机场数据',
    [K.nearbyStale]: '报文偏旧，正在后台刷新',
    [K.nearbyNoMetar]: '气象获取中…',

    [K.phaseUnknown]: '未知',
    [K.phaseParked]: '停机',
    [K.phaseTaxi]: '滑行',
    [K.phaseTakeoff]: '起飞',
    [K.phaseClimb]: '爬升',
    [K.phaseCruise]: '巡航',
    [K.phaseDescent]: '下降',
    [K.phaseApproach]: '进近',
    [K.phaseLanding]: '着陆',

    [K.gateTaxiSpeed]: '滑行速度',
    [K.gateParkingBrake]: '停留刹车',
    [K.gateFlaps]: '襟翼',
    [K.gateGearDown]: '起落架',
    [K.gateElevatorTrim]: '升降舵配平',
    [K.gateSpeedBelow10000]: 'FL100 以下速度',
    [K.gateClimbRate]: '爬升率',
    [K.gateMach]: '马赫数',
    [K.gateVerticalDeviation]: '高度保持',
    [K.gateAutopilot]: '自动驾驶',
    [K.gateDescentRate]: '下降率',
    [K.gateSpeedBrake]: '减速板',
    [K.gateSinkRate]: '下降率（稳定进近）',
    [K.gateBankAngle]: '坡度',
    [K.gateFlapsDeployed]: '着陆构型',
    [K.gateTouchdownG]: '接地过载',
    [K.gateSpoilers]: '扰流板',
    [K.gateReverseReady]: '减速装置',
  },
  en_US: {
    [K.navTitle]: 'Flight Card',
    [K.pageTitle]: 'EFB Flight Card',
    [K.pageSubtitle]: 'Phase, key gates, nearby weather and fuel margin on one screen',

    [K.sectionPhase]: 'Flight phase',
    [K.sectionGates]: 'Key gates',
    [K.sectionFuel]: 'Fuel margin',
    [K.sectionNearby]: 'Nearby airports & weather',

    [K.disconnected]: 'No simulator connected — flight card has no data',
    [K.noGates]: 'No gates to watch in this phase',
    [K.refresh]: 'Refresh',
    [K.loading]: 'Loading…',
    [K.lastUpdated]: 'Updated {}',
    [K.columnValue]: 'Actual',
    [K.columnLimit]: 'Limit',

    [K.fuelOnboard]: 'Fuel onboard',
    [K.fuelFlow]: 'Current flow',
    [K.fuelEndurance]: 'Endurance',
    [K.fuelBurnToDest]: 'Burn to destination',
    [K.fuelAtDest]: 'Fuel at destination',
    [K.fuelReserve]: 'Minimum reserve',
    [K.fuelMargin]: 'Margin',
    [K.fuelStatusOk]: 'Comfortable margin',
    [K.fuelStatusWatch]: 'Approaching reserve',
    [K.fuelStatusCritical]: 'Below minimum reserve',
    [K.fuelStatusUnknown]: 'Not enough data to assess',

    [K.nearbyEmpty]: 'No nearby airport data available',
    [K.nearbyStale]: 'Report is stale, refreshing in background',
    [K.nearbyNoMetar]: 'Fetching weather…',

    [K.phaseUnknown]: 'Unknown',
    [K.phaseParked]: 'Parked',
    [K.phaseTaxi]: 'Taxi',
    [K.phaseTakeoff]: 'Takeoff',
    [K.phaseClimb]: 'Climb',
    [K.phaseCruise]: 'Cruise',
    [K.phaseDescent]: 'Descent',
    [K.phaseApproach]: 'Approach',
    [K.phaseLanding]: 'Landing',

    [K.gateTaxiSpeed]: 'Taxi speed',
    [K.gateParkingBrake]: 'Parking brake',
    [K.gateFlaps]: 'Flaps',
    [K.gateGearDown]: 'Landing gear',
    [K.gateElevatorTrim]: 'Elevator trim',
    [K.gateSpeedBelow10000]: 'Speed below FL100',
    [K.gateClimbRate]: 'Climb rate',
    [K.gateMach]: 'Mach',
    [K.gateVerticalDeviation]: 'Altitude hold',
    [K.gateAutopilot]: 'Autopilot',
    [K.gateDescentRate]: 'Descent rate',
    [K.gateSpeedBrake]: 'Speed brake',
    [K.gateSinkRate]: 'Sink rate (stabilized)',
    [K.gateBankAngle]: 'Bank angle',
    [K.gateFlapsDeployed]: 'Landing configuration',
    [K.gateTouchdownG]: 'Touchdown load',
    [K.gateSpoilers]: 'Spoilers',
    [K.gateReverseReady]: 'Deceleration devices',
  },
};

/** 门限 id → i18n key */
export const GATE_LABEL_KEY: Record<string, string> = {
  taxi_speed: K.gateTaxiSpeed,
  parking_brake: K.gateParkingBrake,
  flaps: K.gateFlaps,
  gear_down: K.gateGearDown,
  elevator_trim: K.gateElevatorTrim,
  speed_below_10000: K.gateSpeedBelow10000,
  climb_rate: K.gateClimbRate,
  mach: K.gateMach,
  vertical_deviation: K.gateVerticalDeviation,
  autopilot: K.gateAutopilot,
  descent_rate: K.gateDescentRate,
  speed_brake: K.gateSpeedBrake,
  sink_rate: K.gateSinkRate,
  bank_angle: K.gateBankAngle,
  flaps_deployed: K.gateFlapsDeployed,
  touchdown_g: K.gateTouchdownG,
  spoilers: K.gateSpoilers,
  reverse_ready: K.gateReverseReady,
};

/** 飞行阶段 → i18n key */
export const PHASE_LABEL_KEY: Record<string, string> = {
  unknown: K.phaseUnknown,
  parked: K.phaseParked,
  taxi: K.phaseTaxi,
  takeoff: K.phaseTakeoff,
  climb: K.phaseClimb,
  cruise: K.phaseCruise,
  descent: K.phaseDescent,
  approach: K.phaseApproach,
  landing: K.phaseLanding,
};

/** 飞行阶段 → Material 图标 */
export const PHASE_ICON: Record<string, string> = {
  unknown: 'help',
  parked: 'local_parking',
  taxi: 'directions',
  takeoff: 'flight_takeoff',
  climb: 'trending_up',
  cruise: 'flight',
  descent: 'trending_down',
  approach: 'flight_land',
  landing: 'airlines',
};
