import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * Map 模块国际化
 *
 * 对应 Flutter 版 `modules/map/localization/*.dart`（204 个 key）。
 * 由脚本机械转换，key 与文案逐条对齐。
 */
export const MapLocalizationKeys = {
  navTitle: 'map.nav.title',
  panelTitle: 'map.panel.title',
  panelSubtitle: 'map.panel.subtitle',
  followAircraft: 'map.control.follow',
  layerTitle: 'map.layer.title',
  layerDark: 'map.layer.dark',
  layerSatellite: 'map.layer.satellite',
  layerTerrain: 'map.layer.terrain',
  layerTaxiway: 'map.layer.taxiway',
  moduleSettings: 'map.module.settings',
  moduleSettingsDesc: 'map.module.settings_desc',
  timerSectionTitle: 'map.timer.section_title',
  timerSectionDesc: 'map.timer.section_desc',
  timerAutoEnable: 'map.timer.auto_enable',
  timerStartCondition: 'map.timer.start_condition',
  timerStopCondition: 'map.timer.stop_condition',
  timerStartRunwayMovement: 'map.timer.start.runway_movement',
  timerStartPushback: 'map.timer.start.pushback',
  timerStartAnyMovement: 'map.timer.start.any_movement',
  timerStopStableLanding: 'map.timer.stop.stable_landing',
  timerStopRunwayExit: 'map.timer.stop.runway_exit',
  timerStopParkingArrival: 'map.timer.stop.parking_arrival',
  timerSettingsSaved: 'map.timer.settings_saved',
  alertSettingsSectionTitle: 'map.alert_settings.section_title',
  alertSettingsSectionDesc: 'map.alert_settings.section_desc',
  alertSettingsEnableAll: 'map.alert_settings.enable_all',
  alertSettingsSelectAlerts: 'map.alert_settings.select_alerts',
  alertSettingsThresholdTitle: 'map.alert_settings.threshold_title',
  alertThresholdClimbWarningLabel: 'map.alert_settings.threshold.climb_warning',
  alertThresholdClimbDangerLabel: 'map.alert_settings.threshold.climb_danger',
  alertThresholdDescentWarningLabel: 'map.alert_settings.threshold.descent_warning',
  alertThresholdDescentDangerLabel: 'map.alert_settings.threshold.descent_danger',
  alertThresholdHint: 'map.alert_settings.threshold_hint',
  alertSettingsSaved: 'map.alert_settings.saved',
  invalidAlertThreshold: 'map.alert_settings.invalid_threshold',
  flightDataSectionTitle: 'map.flight_data.section_title',
  flightDataSectionDesc: 'map.flight_data.section_desc',
  flightDataIntervalLabel: 'map.flight_data.interval_label',
  flightDataIntervalHint: 'map.flight_data.interval_hint',
  currentFlightDataInterval: 'map.flight_data.current_interval',
  invalidFlightDataInterval: 'map.flight_data.invalid_interval',
  flightDataIntervalSaved: 'map.flight_data.saved',
  homeAirportSectionTitle: 'map.home_airport.section_title',
  homeAirportSectionDesc: 'map.home_airport.section_desc',
  homeAirportIcaoLabel: 'map.home_airport.icao_label',
  homeAirportIcaoHint: 'map.home_airport.icao_hint',
  homeAirportCurrent: 'map.home_airport.current',
  homeAirportSaved: 'map.home_airport.saved',
  homeAirportNotFound: 'map.home_airport.not_found',
  homeAirportCleared: 'map.home_airport.cleared',
  homeAirportServiceUnavailableTag: 'map.home_airport.service_unavailable_tag',
  homeAirportServiceUnavailableHint: 'map.home_airport.service_unavailable_hint',
  clearButton: 'map.action.clear',
  saveButton: 'map.action.save',
  saving: 'map.action.saving',
  toggleRoute: 'map.control.route',
  toggleAirports: 'map.control.toggle_airports',
  toggleNearbyAirports: 'map.control.toggle_nearby_airports',
  toggleRunways: 'map.control.runways',
  toggleParkings: 'map.control.parkings',
  toggleAeroway: 'map.control.aeroway',
  toggleWeather: 'map.control.weather',
  toggleWeatherRainfall: 'map.control.weather_rainfall',
  toggleWeatherWind: 'map.control.weather_wind',
  toggleWeatherPressure: 'map.control.weather_pressure',
  toggleWeatherTemperature: 'map.control.weather_temperature',
  toggleRestrictedAirspace: 'map.control.restricted_airspace',
  toggleTerrainWarning: 'map.control.terrain_warning',
  toggleCompass: 'map.control.compass',
  legendTitle: 'map.legend.title',
  legendRadarTitle: 'map.legend.radar',
  legendRainTitle: 'map.legend.rain',
  legendWindTitle: 'map.legend.wind',
  legendPressureTitle: 'map.legend.pressure',
  legendTempTitle: 'map.legend.temp',
  legendAirspaceTitle: 'map.legend.airspace',
  legendTerrainTitle: 'map.legend.terrain',
  legendWeak: 'map.legend.weak',
  legendStrong: 'map.legend.strong',
  legendAirspaceCritical: 'map.legend.airspace_critical',
  legendAirspaceWarning: 'map.legend.airspace_warning',
  legendAirspaceAdvisory: 'map.legend.airspace_advisory',
  legendTerrainDanger: 'map.legend.terrain_danger',
  legendTerrainWarning: 'map.legend.terrain_warning',
  legendTerrainCaution: 'map.legend.terrain_caution',
  runwayGlideslope: 'map.runway.glideslope',
  runwayGlideslopeHint: 'map.runway.glideslope_hint',
  runwayLocHint: 'map.runway.loc_hint',
  runwayDmeHint: 'map.runway.dme_hint',
  runwayNoIls: 'map.runway.no_ils',
  toggleHoldings: 'map.control.holdings',
  toggleProcedures: 'map.control.procedures',
  toggleTaxiGuidance: 'map.control.taxi_guidance',
  taxiTitle: 'map.taxi.title',
  taxiClearanceHint: 'map.taxi.clearance_hint',
  taxiPlanAction: 'map.taxi.plan',
  taxiClear: 'map.taxi.clear',
  taxiTotal: 'map.taxi.total',
  taxiHoldShort: 'map.taxi.hold_short',
  taxiUnnamed: 'map.taxi.unnamed',
  taxiToRunway: 'map.taxi.to_runway',
  taxiEta: 'map.taxi.eta',
  taxiStartFrom: 'map.taxi.start_from',
  taxiStartAircraft: 'map.taxi.start_aircraft',
  taxiStand: 'map.taxi.stand',
  taxiErrorNoAeroway: 'map.taxi.error.no_aeroway',
  taxiErrorNoRefs: 'map.taxi.error.no_refs',
  taxiErrorNoStart: 'map.taxi.error.no_start',
  taxiErrorUnreachable: 'map.taxi.error.unreachable',
  procedureTitle: 'map.procedure.title',
  procedureKindSid: 'map.procedure.kind.sid',
  procedureKindStar: 'map.procedure.kind.star',
  procedureKindApproach: 'map.procedure.kind.approach',
  procedureLoading: 'map.procedure.loading',
  procedureEmpty: 'map.procedure.empty',
  procedureNoAirport: 'map.procedure.no_airport',
  procedureLegs: 'map.procedure.legs',
  procedureClear: 'map.procedure.clear',
  procedureSearchHint: 'map.procedure.search_hint',
  controlGroupFlight: 'map.control_group.flight',
  controlGroupAirport: 'map.control_group.airport',
  controlGroupProcedure: 'map.control_group.procedure',
  controlGroupWeather: 'map.control_group.weather',
  controlGroupHazard: 'map.control_group.hazard',
  controlGroupTaxiway: 'map.control_group.taxiway',
  toggleRunwayNavaids: 'map.control.runway_navaids',
  papiHigh: 'map.papi.high',
  papiSlightlyHigh: 'map.papi.slightly_high',
  papiOnSlope: 'map.papi.on_slope',
  papiSlightlyLow: 'map.papi.slightly_low',
  papiLow: 'map.papi.low',
  legendCollapse: 'map.legend.collapse',
  legendExpand: 'map.legend.expand',
  toggleCustomTaxiway: 'map.control.custom_taxiway',
  toggleTaxiwayDrawing: 'map.control.taxiway_drawing',
  emptyState: 'map.empty_state',
  aircraft: 'map.label.aircraft',
  altitude: 'map.label.altitude',
  groundSpeed: 'map.label.ground_speed',
  routePoints: 'map.label.route_points',
  airports: 'map.label.airports',
  distance: 'map.label.distance',
  clearRoute: 'map.action.clear_route',
  clearSearch: 'map.action.clear_search',
  searchHint: 'map.search.hint',
  searchNoResult: 'map.search.no_result',
  selectedAirport: 'map.marker.selected_airport',
  markerDepartureAirport: 'map.marker.departure_airport',
  markerArrivalAirport: 'map.marker.arrival_airport',
  markerAlternateAirport: 'map.marker.alternate_airport',
  markerHomeAirport: 'map.marker.home_airport',
  actionSetAsDepartureAirport: 'map.action.set_as_departure_airport',
  actionSetAsArrivalAirport: 'map.action.set_as_arrival_airport',
  actionSetAsAlternateAirport: 'map.action.set_as_alternate_airport',
  tooltipLayer: 'map.tooltip.layer',
  tooltipFollow: 'map.tooltip.follow',
  tooltipTimerStart: 'map.tooltip.timer_start',
  tooltipTimerPause: 'map.tooltip.timer_pause',
  tooltipTimerReset: 'map.tooltip.timer_reset',
  tooltipTaxiwayUndo: 'map.tooltip.taxiway_undo',
  tooltipTaxiwayRedo: 'map.tooltip.taxiway_redo',
  tooltipTaxiwayClear: 'map.tooltip.taxiway_clear',
  tooltipTaxiwaySave: 'map.tooltip.taxiway_save',
  tooltipTaxiwayImport: 'map.tooltip.taxiway_import',
  tooltipPlannedRoute: 'map.tooltip.planned_route',
  tooltipZoomIn: 'map.tooltip.zoom_in',
  tooltipZoomOut: 'map.tooltip.zoom_out',
  tooltipHideDetail: 'map.tooltip.hide_detail',
  tooltipShowDetail: 'map.tooltip.show_detail',
  plannedRouteTotal: 'map.label.planned_route_total',
  labelTakeoff: 'map.label.takeoff',
  labelLanding: 'map.label.landing',
  labelLatitudeLongitude: 'map.label.latitude_longitude',
  labelHeading: 'map.label.heading',
  labelLastEdited: 'map.label.last_edited',
  labelNodeCount: 'map.label.node_count',
  clearRouteConfirmTitle: 'map.clear_route.confirm_title',
  clearRouteConfirmContent: 'map.clear_route.confirm_content',
  reconnectPromptTitle: 'map.reconnect.prompt_title',
  reconnectPromptContent: 'map.reconnect.prompt_content',
  reconnectKeepRoute: 'map.reconnect.keep_route',
  taxiwayExportSuccess: 'map.taxiway.export_success',
  taxiwayImportSuccess: 'map.taxiway.import_success',
  taxiwayImportInvalid: 'map.taxiway.import_invalid',
  taxiwayNoRouteToSave: 'map.taxiway.no_route_to_save',
  taxiwayNodePositionUpdated: 'map.taxiway.node_position_updated',
  taxiwayEditUnsaved: 'map.taxiway.edit_unsaved',
  taxiwaySaveInProgress: 'map.taxiway.save_in_progress',
  taxiwayAutoLoadTitle: 'map.taxiway.auto_load.title',
  taxiwayAutoLoadPrompt: 'map.taxiway.auto_load.load_prompt',
  taxiwayAutoLoadSkip: 'map.taxiway.auto_load.skip',
  taxiwayAutoLoadLoad: 'map.taxiway.auto_load.load',
  taxiwayAutoLoadLoaded: 'map.taxiway.auto_load.loaded',
  taxiwayAutoLoadInvalid: 'map.taxiway.auto_load.invalid',
  taxiwayNode: 'map.taxiway.node',
  taxiwayNodeSettings: 'map.taxiway.node_settings',
  taxiwayNodeName: 'map.taxiway.node_name',
  taxiwayNodeNote: 'map.taxiway.node_note',
  taxiwayNodeColor: 'map.taxiway.node_color',
  taxiwayNodeCurrentColor: 'map.taxiway.node_current_color',
  taxiwayDeleteNode: 'map.taxiway.delete_node',
  taxiwayInsertNode: 'map.taxiway.insert_node',
  taxiwayInsertNodeSuccess: 'map.taxiway.insert_node_success',
  taxiwayEditConnection: 'map.taxiway.edit_connection',
  taxiwayConnection: 'map.taxiway.connection',
  taxiwayConnectionRange: 'map.taxiway.connection_range',
  taxiwayConnectionName: 'map.taxiway.connection_name',
  taxiwayConnectionNote: 'map.taxiway.connection_note',
  taxiwayConnectionColor: 'map.taxiway.connection_color',
  taxiwayConnectionLineType: 'map.taxiway.connection_line_type',
  taxiwayConnectionLineTypeStraight: 'map.taxiway.connection_line_type_straight',
  taxiwayConnectionLineTypeMapMatching: 'map.taxiway.connection_line_type_map_matching',
  taxiwayConnectionCurvature: 'map.taxiway.connection_curvature',
  taxiwayConnectionCurveDirection: 'map.taxiway.connection_curve_direction',
  taxiwayConnectionCurveDirectionLeft: 'map.taxiway.connection_curve_direction_left',
  taxiwayConnectionCurveDirectionRight: 'map.taxiway.connection_curve_direction_right',
  taxiwayConnectionDragHint: 'map.taxiway.connection_drag_hint',
  taxiwayDangerGeneric: 'map.taxiway.danger_generic',
  weatherNoData: 'map.weather.no_data',
  loadingAirportDetail: 'map.airport.loading_detail',
  metarRawShort: 'map.weather.raw_short',
  metarDecodedShort: 'map.weather.decoded_short',
  approachRuleHint: 'map.weather.approach_rule_hint',
  alertPitchUpDanger: 'map.alert.pitch_up_danger',
  alertPitchUpWarning: 'map.alert.pitch_up_warning',
  alertPitchDownDanger: 'map.alert.pitch_down_danger',
  alertPitchDownWarning: 'map.alert.pitch_down_warning',
  alertBankDanger: 'map.alert.bank_danger',
  alertBankWarning: 'map.alert.bank_warning',
  alertStallWarning: 'map.alert.stall_warning',
  alertSinkRateDanger: 'map.alert.sink_rate_danger',
  alertSinkRateWarning: 'map.alert.sink_rate_warning',
  alertInvertedFlightDanger: 'map.alert.inverted_flight_danger',
  alertKnifeEdgeDanger: 'map.alert.knife_edge_danger',
  alertKnifeEdgeWarning: 'map.alert.knife_edge_warning',
  alertPullUpDanger: 'map.alert.pull_up_danger',
  alertPullUpWarning: 'map.alert.pull_up_warning',
  alertPushOverDanger: 'map.alert.push_over_danger',
  alertPushOverWarning: 'map.alert.push_over_warning',
  alertSpiralDiveDanger: 'map.alert.spiral_dive_danger',
  alertSpiralDiveWarning: 'map.alert.spiral_dive_warning',
  alertUnusualAttitudeDanger: 'map.alert.unusual_attitude_danger',
  alertUnusualAttitudeWarning: 'map.alert.unusual_attitude_warning',
  alertClimbRateDanger: 'map.alert.climb_rate_danger',
  alertClimbRateWarning: 'map.alert.climb_rate_warning',
  alertDescentRateDanger: 'map.alert.descent_rate_danger',
  alertDescentRateWarning: 'map.alert.descent_rate_warning',
  alertHighGDanger: 'map.alert.high_g_danger',
  alertHighGWarning: 'map.alert.high_g_warning',
  alertNegativeGDanger: 'map.alert.negative_g_danger',
  alertNegativeGWarning: 'map.alert.negative_g_warning',
  alertOverspeedDanger: 'map.alert.overspeed_danger',
  alertOverspeedWarning: 'map.alert.overspeed_warning',
  aircraftInfoPanelTitle: 'map.aircraft_info.title',
  airportCardCollapse: 'map.airport_card.collapse',
  airportCardExpand: 'map.airport_card.expand',
  airportOnRunway: 'map.airport_card.on_runway',
  airportOnRunwayHint: 'map.airport_card.on_runway_hint',
  airportHere: 'map.airport_card.here',
  alertTerrainPullUpDanger: 'map.alert.terrain_pull_up_danger',
  alertTerrainPullUpWarning: 'map.alert.terrain_pull_up_warning',
  crashTitle: 'map.crash.title',
  crashSubtitle: 'map.crash.subtitle',
  crashResetButton: 'map.crash.reset_button',
  crashQuote1: 'map.crash.quote_1',
  crashQuote2: 'map.crash.quote_2',
  crashQuote3: 'map.crash.quote_3',
  crashQuote4: 'map.crash.quote_4',
  crashQuote5: 'map.crash.quote_5',
  crashQuote6: 'map.crash.quote_6',
  crashQuote7: 'map.crash.quote_7',
  crashQuote8: 'map.crash.quote_8',
  crashQuote9: 'map.crash.quote_9',
  crashQuote10: 'map.crash.quote_10',
  crashQuote11: 'map.crash.quote_11',
  crashQuote12: 'map.crash.quote_12',
} as const;

const K = MapLocalizationKeys;

export const mapTranslations: ModuleTranslations = {
  zh_CN: {
    [K.navTitle]: '地图',
    [K.panelTitle]: '地图概览',
    [K.panelSubtitle]: '显示航迹与机场信息',
    [K.followAircraft]: '跟随飞机',
    [K.layerTitle]: '图层',
    [K.layerDark]: '深色',
    [K.layerSatellite]: '卫星',
    [K.layerTerrain]: '地形',
    [K.layerTaxiway]: '滑行道',
    [K.moduleSettings]: '地图模块',
    [K.moduleSettingsDesc]: '管理地图模块的相关设定',
    [K.timerSectionTitle]: '自动计时规则',
    [K.timerSectionDesc]: '配置自动开始与自动停止的触发规则',
    [K.timerAutoEnable]: '启用自动计时',
    [K.timerStartCondition]: '自动开始条件',
    [K.timerStopCondition]: '自动停止条件',
    [K.timerStartRunwayMovement]: '飞机位于跑道并开始计时',
    [K.timerStartPushback]: '飞机从停机位推出后开始计时',
    [K.timerStartAnyMovement]: '飞机只要移动就开始计时',
    [K.timerStopStableLanding]: '飞机稳定降落后自动停止',
    [K.timerStopRunwayExit]: '飞机降落后脱离跑道时停止',
    [K.timerStopParkingArrival]: '飞机抵达任意停机位后停止',
    [K.timerSettingsSaved]: '自动计时规则已保存',
    [K.alertSettingsSectionTitle]: '告警提示设置',
    [K.alertSettingsSectionDesc]: '配置告警开关、提示类型与垂直速度阈值',
    [K.alertSettingsEnableAll]: '启用飞行告警提示',
    [K.alertSettingsSelectAlerts]: '选择要显示的告警类型',
    [K.alertSettingsThresholdTitle]: '垂直速度阈值（fpm）',
    [K.alertThresholdClimbWarningLabel]: '爬升率告警阈值',
    [K.alertThresholdClimbDangerLabel]: '爬升率危险阈值',
    [K.alertThresholdDescentWarningLabel]: '下降率告警阈值',
    [K.alertThresholdDescentDangerLabel]: '下降率危险阈值',
    [K.alertThresholdHint]: '危险阈值必须大于告警阈值',
    [K.alertSettingsSaved]: '告警设置已保存',
    [K.invalidAlertThreshold]: '请输入有效阈值，且危险阈值需大于告警阈值',
    [K.flightDataSectionTitle]: '飞行数据频率',
    [K.flightDataSectionDesc]: '设置地图模块拉取飞行数据的请求间隔',
    [K.flightDataIntervalLabel]: '请求间隔（毫秒）',
    [K.flightDataIntervalHint]: '范围 100 - 2000，默认 300',
    [K.currentFlightDataInterval]: '当前频率: {value} ms',
    [K.invalidFlightDataInterval]: '请输入有效频率（100-2000 毫秒）',
    [K.flightDataIntervalSaved]: '飞行数据频率已保存',
    [K.homeAirportSectionTitle]: '默认机场位置',
    [K.homeAirportSectionDesc]: '用于地图模块的默认定位中心',
    [K.homeAirportIcaoLabel]: '机场 ICAO',
    [K.homeAirportIcaoHint]: '例如 ZBAA、RJTT、KLAX',
    [K.homeAirportCurrent]: '当前默认机场: {value}',
    [K.homeAirportSaved]: '默认机场已保存',
    [K.homeAirportNotFound]: '未找到该机场，请检查 ICAO',
    [K.homeAirportCleared]: '默认机场已清除',
    [K.homeAirportServiceUnavailableTag]: '服务不可用',
    [K.homeAirportServiceUnavailableHint]: '后端服务不可用，无法设置默认机场位置',
    [K.clearButton]: '清除',
    [K.saveButton]: '保存配置',
    [K.saving]: '保存中...',
    [K.toggleRoute]: '航线',
    [K.toggleAirports]: '机场',
    [K.toggleNearbyAirports]: '附近机场',
    [K.toggleRunways]: '跑道',
    [K.toggleParkings]: '停机位',
    [K.toggleAeroway]: '滑行道',
    [K.legendTitle]: '图例',
    [K.legendRadarTitle]: '雷达回波',
    [K.legendRainTitle]: '降雨量',
    [K.legendWindTitle]: '风速',
    [K.legendPressureTitle]: '海平面气压',
    [K.legendTempTitle]: '地面温度',
    [K.legendAirspaceTitle]: '限制空域',
    [K.legendTerrainTitle]: '地形告警',
    [K.legendWeak]: '弱',
    [K.legendStrong]: '强',
    [K.legendAirspaceCritical]: '禁止进入',
    [K.legendAirspaceWarning]: '限制区',
    [K.legendAirspaceAdvisory]: '注意区',
    [K.legendTerrainDanger]: '危险',
    [K.legendTerrainWarning]: '警告',
    [K.legendTerrainCaution]: '注意',
    [K.runwayGlideslope]: '下滑道',
    [K.runwayGlideslopeHint]: '下滑道角度；点击可单独隐藏/显示这一列',
    [K.runwayLocHint]: '航向台识别码 · 频率 · 磁航道',
    [K.runwayDmeHint]: '该进近配有测距台（DME）',
    [K.runwayNoIls]: '无 ILS',
    [K.toggleHoldings]: '等待航线',
    [K.toggleProcedures]: '公布程序',
    [K.toggleTaxiGuidance]: '滑行引导',
    [K.taxiTitle]: '地面滑行引导',
    [K.taxiClearanceHint]: '粘贴管制指令，如 taxi via A5, B, hold short 36L',
    [K.taxiPlanAction]: '规划',
    [K.taxiClear]: '清除路线',
    [K.taxiTotal]: '全程',
    [K.taxiHoldShort]: '在此等待',
    [K.taxiUnnamed]: '无编号',
    [K.taxiToRunway]: '滑到跑道',
    [K.taxiEta]: '约需',
    [K.taxiStartFrom]: '起点',
    [K.taxiStartAircraft]: '本机位置',
    [K.taxiStand]: '机位',
    [K.taxiErrorNoAeroway]: '还没有该机场的地面数据，请稍候再试',
    [K.taxiErrorNoRefs]: '没从指令里认出滑行道编号',
    [K.taxiErrorNoStart]: '定不到起点：本机不在滑行道附近，也没有可用机位',
    [K.taxiErrorUnreachable]: '按这条指令在本场走不通，请核对编号',
    [K.procedureTitle]: '离场 / 进场 / 进近程序',
    [K.procedureKindSid]: '离场',
    [K.procedureKindStar]: '进场',
    [K.procedureKindApproach]: '进近',
    [K.procedureLoading]: '正在读取程序…',
    [K.procedureEmpty]: '该机场没有可用的程序数据',
    [K.procedureNoAirport]: '先选一个机场',
    [K.procedureLegs]: '个航段',
    [K.procedureClear]: '取消选择',
    [K.procedureSearchHint]: '按名称或跑道筛选',
    [K.controlGroupFlight]: '飞行',
    [K.controlGroupAirport]: '机场',
    [K.controlGroupProcedure]: '进近程序',
    [K.controlGroupWeather]: '气象',
    [K.controlGroupHazard]: '告警',
    [K.controlGroupTaxiway]: '滑行道绘制',
    [K.toggleRunwayNavaids]: '进近设施',
    [K.papiHigh]: '过高',
    [K.papiSlightlyHigh]: '略高',
    [K.papiOnSlope]: '坡度正常',
    [K.papiSlightlyLow]: '略低',
    [K.papiLow]: '过低',
    [K.legendCollapse]: '收起图例',
    [K.legendExpand]: '展开图例',
    [K.toggleWeather]: '气象',
    [K.toggleWeatherRainfall]: '降雨量',
    [K.toggleWeatherWind]: '高空风',
    [K.toggleWeatherPressure]: '气压',
    [K.toggleWeatherTemperature]: '温度',
    [K.toggleRestrictedAirspace]: '空域限制',
    [K.toggleTerrainWarning]: '地形告警',
    [K.toggleCompass]: '罗盘',
    [K.toggleCustomTaxiway]: '自定义滑行道',
    [K.toggleTaxiwayDrawing]: '绘制滑行道',
    [K.emptyState]: '暂无航迹数据',
    [K.aircraft]: '飞机',
    [K.altitude]: '高度',
    [K.groundSpeed]: '地速',
    [K.routePoints]: '航迹点',
    [K.airports]: '机场',
    [K.distance]: '航程',
    [K.clearRoute]: '清除轨迹',
    [K.clearSearch]: '清除搜索记录',
    [K.searchHint]: '搜索机场 (ICAO/IATA/名称)',
    [K.searchNoResult]: '未找到相关机场',
    [K.selectedAirport]: '当前机场',
    [K.markerDepartureAirport]: '起飞',
    [K.markerArrivalAirport]: '抵达',
    [K.markerAlternateAirport]: '备降',
    [K.markerHomeAirport]: '默认',
    [K.actionSetAsDepartureAirport]: '设置为起飞机场',
    [K.actionSetAsArrivalAirport]: '设置为抵达机场',
    [K.actionSetAsAlternateAirport]: '设置为备降机场',
    [K.tooltipLayer]: '地图图层',
    [K.tooltipFollow]: '追随飞机',
    [K.tooltipTimerStart]: '开始计时',
    [K.tooltipTimerPause]: '暂停计时',
    [K.tooltipTimerReset]: '重置计时',
    [K.tooltipTaxiwayUndo]: '撤销规划点',
    [K.tooltipTaxiwayRedo]: '恢复规划点',
    [K.tooltipTaxiwayClear]: '清除已绘制滑行道',
    [K.tooltipTaxiwaySave]: '保存自定义滑行道',
    [K.tooltipTaxiwayImport]: '导入自定义滑行道',
    [K.tooltipPlannedRoute]: '显示或隐藏计划航路',
    [K.tooltipZoomIn]: '放大',
    [K.tooltipZoomOut]: '缩小',
    [K.tooltipHideDetail]: '点击隐藏详情',
    [K.tooltipShowDetail]: '点击显示详情',
    [K.plannedRouteTotal]: '计划航程',
    [K.labelTakeoff]: '起飞',
    [K.labelLanding]: '着陆',
    [K.labelLatitudeLongitude]: '经纬度',
    [K.labelHeading]: '航向',
    [K.labelLastEdited]: '最后编辑',
    [K.labelNodeCount]: '节点数',
    [K.clearRouteConfirmTitle]: '确认清除轨迹',
    [K.clearRouteConfirmContent]: '清除后将移除当前航迹点与相关里程计时数据，是否继续？',
    [K.reconnectPromptTitle]: '检测到新的飞行连接',
    [K.reconnectPromptContent]: '当前地图存在上一次飞行轨迹，是否清除后开始本次飞行？',
    [K.reconnectKeepRoute]: '保留轨迹',
    [K.taxiwayExportSuccess]: '自定义滑行道已保存',
    [K.taxiwayImportSuccess]: '自定义滑行道已导入',
    [K.taxiwayImportInvalid]: '导入失败，文件格式无效',
    [K.taxiwayNoRouteToSave]: '当前没有可保存的滑行道',
    [K.taxiwayNodePositionUpdated]: '节点位置已更新',
    [K.taxiwayEditUnsaved]: '节点编辑中 · 未保存',
    [K.taxiwaySaveInProgress]: '保存中',
    [K.taxiwayAutoLoadTitle]: '检测到当前机场滑行道配置',
    [K.taxiwayAutoLoadPrompt]: '是否加载已有节点数据？',
    [K.taxiwayAutoLoadSkip]: '暂不加载',
    [K.taxiwayAutoLoadLoad]: '加载配置',
    [K.taxiwayAutoLoadLoaded]: '已加载节点',
    [K.taxiwayAutoLoadInvalid]: '加载失败，文件数据无效',
    [K.taxiwayNode]: '节点',
    [K.taxiwayNodeSettings]: '节点设置',
    [K.taxiwayNodeName]: '节点名称',
    [K.taxiwayNodeNote]: '备注',
    [K.taxiwayNodeColor]: '节点颜色',
    [K.taxiwayNodeCurrentColor]: '当前颜色',
    [K.taxiwayDeleteNode]: '删除节点',
    [K.taxiwayInsertNode]: '插入节点',
    [K.taxiwayInsertNodeSuccess]: '已在连线中插入节点',
    [K.taxiwayEditConnection]: '编辑连接线',
    [K.taxiwayConnection]: '连接线',
    [K.taxiwayConnectionRange]: '连接范围',
    [K.taxiwayConnectionName]: '连接线名称',
    [K.taxiwayConnectionNote]: '连接线备注',
    [K.taxiwayConnectionColor]: '连接线颜色',
    [K.taxiwayConnectionLineType]: '连接线类型',
    [K.taxiwayConnectionLineTypeStraight]: '直线',
    [K.taxiwayConnectionLineTypeMapMatching]: '匹配地图曲线',
    [K.taxiwayConnectionCurvature]: '连接线弧度',
    [K.taxiwayConnectionCurveDirection]: '开口方向',
    [K.taxiwayConnectionCurveDirectionLeft]: '向左',
    [K.taxiwayConnectionCurveDirectionRight]: '向右',
    [K.taxiwayConnectionDragHint]: '长按并拖动连接线可直接调整弧度和方向',
    [K.taxiwayDangerGeneric]: '飞行参数异常，请立即修正',
    [K.weatherNoData]: '暂无气象信息',
    [K.loadingAirportDetail]: '正在加载机场详情',
    [K.metarRawShort]: '原',
    [K.metarDecodedShort]: '译',
    [K.approachRuleHint]: '按 METAR 能见度与云底高推算的飞行等级',
    [K.alertPitchUpDanger]: '机头上仰过大',
    [K.alertPitchUpWarning]: '俯仰角偏大',
    [K.alertPitchDownDanger]: '机头下俯过大',
    [K.alertPitchDownWarning]: '下俯角偏大',
    [K.alertBankDanger]: '倾斜角危险',
    [K.alertBankWarning]: '倾斜角较大',
    [K.alertStallWarning]: '失速警告',
    [K.alertSinkRateDanger]: '下降率过大',
    [K.alertSinkRateWarning]: '下降率偏高',
    [K.alertInvertedFlightDanger]: '飞机倒飞姿态危险',
    [K.alertKnifeEdgeDanger]: '刀锋飞行姿态危险',
    [K.alertKnifeEdgeWarning]: '接近刀锋飞行姿态',
    [K.alertPullUpDanger]: '急速拉起过猛',
    [K.alertPullUpWarning]: '拉起率偏高',
    [K.alertPushOverDanger]: '急速俯冲过猛',
    [K.alertPushOverWarning]: '俯冲率偏高',
    [K.alertSpiralDiveDanger]: '螺旋俯冲姿态危险',
    [K.alertSpiralDiveWarning]: '接近螺旋俯冲姿态',
    [K.alertUnusualAttitudeDanger]: '异常姿态危险',
    [K.alertUnusualAttitudeWarning]: '异常姿态预警',
    [K.alertClimbRateDanger]: '爬升率过高',
    [K.alertClimbRateWarning]: '爬升率偏高',
    [K.alertDescentRateDanger]: '下降率过高',
    [K.alertDescentRateWarning]: '下降率偏高',
    [K.alertHighGDanger]: '过载过高',
    [K.alertHighGWarning]: '过载偏高',
    [K.alertNegativeGDanger]: '负过载危险',
    [K.alertNegativeGWarning]: '出现负过载',
    [K.alertOverspeedDanger]: '速度超限危险',
    [K.alertOverspeedWarning]: '速度接近超限',
    [K.aircraftInfoPanelTitle]: '航空器信息',
    [K.airportCardCollapse]: '收起',
    [K.airportCardExpand]: '展开',
    [K.airportOnRunway]: '本机位于 {} 跑道',
    [K.airportOnRunwayHint]: '本机当前正位于这条跑道上方',
    [K.airportHere]: '本机',
    [K.alertTerrainPullUpDanger]: '地形逼近，立即拉起',
    [K.alertTerrainPullUpWarning]: '低空下降过快',
    [K.crashTitle]: '你 炸 了',
    [K.crashSubtitle]: 'CRITICAL MISSION FAILURE',
    [K.crashResetButton]: '接受现实 (重置)',
    [K.crashQuote1]: '飞机是挺硬的，但地面更硬点。',
    [K.crashQuote2]: '你是在练习降落吗？还是在垂直钻井？',
    [K.crashQuote3]: '至少你降落在地球上了。',
    [K.crashQuote4]: '模拟器的好处就是：你还能再点一次重置。',
    [K.crashQuote5]: '这次降落可以打 1 分，满分是 100 分。',
    [K.crashQuote6]: '塔台问你是否需要地毯，你给了他们一个坑。',
    [K.crashQuote7]: '航空公司可能会对你的续约表示担忧。',
    [K.crashQuote8]: '这大概就是所谓的一次性飞行器吧。',
    [K.crashQuote9]: 'RIP (Really Interesting Pilot)',
    [K.crashQuote10]: '由于你出色的飞行技巧，地面已经成功拦截了你。',
    [K.crashQuote11]: '刚才那不是降落，那是受控坠毁。',
    [K.crashQuote12]: '恭喜你，你已经成为了大地母亲的一部分。',
  },
  en_US: {
    [K.navTitle]: 'Map',
    [K.panelTitle]: 'Map Overview',
    [K.panelSubtitle]: 'Show route and airports',
    [K.followAircraft]: 'Follow Aircraft',
    [K.layerTitle]: 'Layers',
    [K.layerDark]: 'Dark',
    [K.layerSatellite]: 'Satellite',
    [K.layerTerrain]: 'Terrain',
    [K.layerTaxiway]: 'Taxiway',
    [K.moduleSettings]: 'Map Module',
    [K.moduleSettingsDesc]: 'Manage map module related settings',
    [K.timerSectionTitle]: 'Auto Timer Rules',
    [K.timerSectionDesc]: 'Configure trigger rules for auto start and stop',
    [K.timerAutoEnable]: 'Enable Auto Timer',
    [K.timerStartCondition]: 'Auto Start Condition',
    [K.timerStopCondition]: 'Auto Stop Condition',
    [K.timerStartRunwayMovement]: 'Start timer when moving on runway',
    [K.timerStartPushback]: 'Start timer after pushback',
    [K.timerStartAnyMovement]: 'Start on any aircraft movement',
    [K.timerStopStableLanding]: 'Stop after stable landing',
    [K.timerStopRunwayExit]: 'Stop after runway exit',
    [K.timerStopParkingArrival]: 'Stop at any parking stand',
    [K.timerSettingsSaved]: 'Auto timer rule saved',
    [K.alertSettingsSectionTitle]: 'Alert Settings',
    [K.alertSettingsSectionDesc]: 'Configure alert toggles, alert types and vertical speed limits',
    [K.alertSettingsEnableAll]: 'Enable Flight Alerts',
    [K.alertSettingsSelectAlerts]: 'Select Alert Types',
    [K.alertSettingsThresholdTitle]: 'Vertical Speed Thresholds (fpm)',
    [K.alertThresholdClimbWarningLabel]: 'Climb rate warning threshold',
    [K.alertThresholdClimbDangerLabel]: 'Climb rate danger threshold',
    [K.alertThresholdDescentWarningLabel]: 'Descent rate warning threshold',
    [K.alertThresholdDescentDangerLabel]: 'Descent rate danger threshold',
    [K.alertThresholdHint]: 'Danger threshold must be greater than warning threshold',
    [K.alertSettingsSaved]: 'Alert settings saved',
    [K.invalidAlertThreshold]: 'Enter valid thresholds and keep danger above warning',
    [K.flightDataSectionTitle]: 'Flight Data Frequency',
    [K.flightDataSectionDesc]: 'Configure request interval for map module flight data',
    [K.flightDataIntervalLabel]: 'Request Interval (ms)',
    [K.flightDataIntervalHint]: 'Range 100 - 2000, default 300',
    [K.currentFlightDataInterval]: 'Current frequency: {value} ms',
    [K.invalidFlightDataInterval]: 'Enter a valid frequency (100-2000 ms)',
    [K.flightDataIntervalSaved]: 'Flight data frequency saved',
    [K.homeAirportSectionTitle]: 'Home Airport Location',
    [K.homeAirportSectionDesc]: 'Used as the default center in map module',
    [K.homeAirportIcaoLabel]: 'Airport ICAO',
    [K.homeAirportIcaoHint]: 'e.g. ZBAA, RJTT, KLAX',
    [K.homeAirportCurrent]: 'Current home airport: {value}',
    [K.homeAirportSaved]: 'Home airport saved',
    [K.homeAirportNotFound]: 'Airport not found, please check ICAO',
    [K.homeAirportCleared]: 'Home airport cleared',
    [K.homeAirportServiceUnavailableTag]: 'Service Unavailable',
    [K.homeAirportServiceUnavailableHint]: 'Backend service is unavailable, home airport cannot be configured',
    [K.clearButton]: 'Clear',
    [K.saveButton]: 'Save',
    [K.saving]: 'Saving...',
    [K.toggleRoute]: 'Route',
    [K.toggleAirports]: 'Airport',
    [K.toggleNearbyAirports]: 'Nearby',
    [K.toggleRunways]: 'Runway',
    [K.toggleParkings]: 'Parking',
    [K.toggleAeroway]: 'Taxiways',
    [K.legendTitle]: 'Legend',
    [K.legendRadarTitle]: 'Radar echo',
    [K.legendRainTitle]: 'Precipitation',
    [K.legendWindTitle]: 'Wind speed',
    [K.legendPressureTitle]: 'Sea-level pressure',
    [K.legendTempTitle]: 'Surface temperature',
    [K.legendAirspaceTitle]: 'Restricted airspace',
    [K.legendTerrainTitle]: 'Terrain alert',
    [K.legendWeak]: 'Light',
    [K.legendStrong]: 'Heavy',
    [K.legendAirspaceCritical]: 'Prohibited',
    [K.legendAirspaceWarning]: 'Restricted',
    [K.legendAirspaceAdvisory]: 'Advisory',
    [K.legendTerrainDanger]: 'Danger',
    [K.legendTerrainWarning]: 'Warning',
    [K.legendTerrainCaution]: 'Caution',
    [K.runwayGlideslope]: 'GS',
    [K.runwayGlideslopeHint]: 'Glideslope angle; click to show/hide this column',
    [K.runwayLocHint]: 'Localizer ident · frequency · magnetic course',
    [K.runwayDmeHint]: 'DME available on this approach',
    [K.runwayNoIls]: 'No ILS',
    [K.toggleHoldings]: 'Holding patterns',
    [K.toggleProcedures]: 'Published procedures',
    [K.toggleTaxiGuidance]: 'Taxi guidance',
    [K.taxiTitle]: 'Ground taxi guidance',
    [K.taxiClearanceHint]: 'Paste the clearance, e.g. taxi via A5, B, hold short 36L',
    [K.taxiPlanAction]: 'Plan',
    [K.taxiClear]: 'Clear route',
    [K.taxiTotal]: 'Total',
    [K.taxiHoldShort]: 'Hold short',
    [K.taxiUnnamed]: 'unnamed',
    [K.taxiToRunway]: 'Taxi to runway',
    [K.taxiEta]: 'about',
    [K.taxiStartFrom]: 'From',
    [K.taxiStartAircraft]: 'Aircraft',
    [K.taxiStand]: 'Stand',
    [K.taxiErrorNoAeroway]: 'No ground data for this airport yet, try again shortly',
    [K.taxiErrorNoRefs]: 'No taxiway designators found in the clearance',
    [K.taxiErrorNoStart]: 'Cannot locate a start: aircraft is not near a taxiway and no stand is available',
    [K.taxiErrorUnreachable]: 'That clearance does not connect at this airport — check the designators',
    [K.procedureTitle]: 'SID / STAR / Approach',
    [K.procedureKindSid]: 'SID',
    [K.procedureKindStar]: 'STAR',
    [K.procedureKindApproach]: 'Approach',
    [K.procedureLoading]: 'Loading procedures...',
    [K.procedureEmpty]: 'No procedure data for this airport',
    [K.procedureNoAirport]: 'Select an airport first',
    [K.procedureLegs]: 'legs',
    [K.procedureClear]: 'Clear selection',
    [K.procedureSearchHint]: 'Filter by name or runway',
    [K.controlGroupFlight]: 'Flight',
    [K.controlGroupAirport]: 'Airport',
    [K.controlGroupProcedure]: 'Approach',
    [K.controlGroupWeather]: 'Weather',
    [K.controlGroupHazard]: 'Alerts',
    [K.controlGroupTaxiway]: 'Taxiway drawing',
    [K.toggleRunwayNavaids]: 'Approach aids',
    [K.papiHigh]: 'TOO HIGH',
    [K.papiSlightlyHigh]: 'SLIGHTLY HIGH',
    [K.papiOnSlope]: 'ON SLOPE',
    [K.papiSlightlyLow]: 'SLIGHTLY LOW',
    [K.papiLow]: 'TOO LOW',
    [K.legendCollapse]: 'Collapse legend',
    [K.legendExpand]: 'Expand legend',
    [K.toggleWeather]: 'Weather',
    [K.toggleWeatherRainfall]: 'Rainfall',
    [K.toggleWeatherWind]: 'Wind Aloft',
    [K.toggleWeatherPressure]: 'Pressure',
    [K.toggleWeatherTemperature]: 'Temperature',
    [K.toggleRestrictedAirspace]: 'Airspace Limits',
    [K.toggleTerrainWarning]: 'Terrain Warning',
    [K.toggleCompass]: 'Compass',
    [K.toggleCustomTaxiway]: 'Custom Taxiway',
    [K.toggleTaxiwayDrawing]: 'Draw Taxiway',
    [K.emptyState]: 'No route data',
    [K.aircraft]: 'Aircraft',
    [K.altitude]: 'Altitude',
    [K.groundSpeed]: 'Ground Speed',
    [K.routePoints]: 'Route Points',
    [K.airports]: 'Airports',
    [K.distance]: 'Distance',
    [K.clearRoute]: 'Clear Route',
    [K.clearSearch]: 'Clear Search',
    [K.searchHint]: 'Search airport (ICAO/IATA/Name)',
    [K.searchNoResult]: 'No matching airport found',
    [K.selectedAirport]: 'Current',
    [K.markerDepartureAirport]: 'Departure',
    [K.markerArrivalAirport]: 'Arrival',
    [K.markerAlternateAirport]: 'Alternate',
    [K.markerHomeAirport]: 'Home',
    [K.actionSetAsDepartureAirport]: 'Set as departure airport',
    [K.actionSetAsArrivalAirport]: 'Set as arrival airport',
    [K.actionSetAsAlternateAirport]: 'Set as alternate airport',
    [K.tooltipLayer]: 'Map Layers',
    [K.tooltipFollow]: 'Follow Aircraft',
    [K.tooltipTimerStart]: 'Start Timer',
    [K.tooltipTimerPause]: 'Pause Timer',
    [K.tooltipTimerReset]: 'Reset Timer',
    [K.tooltipTaxiwayUndo]: 'Undo taxiway plan',
    [K.tooltipTaxiwayRedo]: 'Redo taxiway plan',
    [K.tooltipTaxiwayClear]: 'Clear drawn taxiway route',
    [K.tooltipTaxiwaySave]: 'Save custom taxiway',
    [K.tooltipTaxiwayImport]: 'Import custom taxiway',
    [K.tooltipPlannedRoute]: 'Show or hide planned route',
    [K.tooltipZoomIn]: 'Zoom In',
    [K.tooltipZoomOut]: 'Zoom Out',
    [K.tooltipHideDetail]: 'Tap to hide details',
    [K.tooltipShowDetail]: 'Tap to show details',
    [K.plannedRouteTotal]: 'Planned Distance',
    [K.labelTakeoff]: 'Takeoff',
    [K.labelLanding]: 'Landing',
    [K.labelLatitudeLongitude]: 'Lat/Lon',
    [K.labelHeading]: 'Heading',
    [K.labelLastEdited]: 'Last edited',
    [K.labelNodeCount]: 'Nodes',
    [K.clearRouteConfirmTitle]: 'Confirm Clear Route',
    [K.clearRouteConfirmContent]: 'This will clear route points, distance and timer data. Continue?',
    [K.reconnectPromptTitle]: 'New flight connection detected',
    [K.reconnectPromptContent]: 'A previous flight route exists on the map. Clear it before starting this flight?',
    [K.reconnectKeepRoute]: 'Keep Route',
    [K.taxiwayExportSuccess]: 'Custom taxiway saved',
    [K.taxiwayImportSuccess]: 'Custom taxiway imported',
    [K.taxiwayImportInvalid]: 'Import failed, invalid file format',
    [K.taxiwayNoRouteToSave]: 'No taxiway route to save',
    [K.taxiwayNodePositionUpdated]: 'Node position updated',
    [K.taxiwayEditUnsaved]: 'Node editing · Unsaved',
    [K.taxiwaySaveInProgress]: 'Saving',
    [K.taxiwayAutoLoadTitle]: 'Taxiway configuration detected for current airport',
    [K.taxiwayAutoLoadPrompt]: 'Load existing taxiway node data?',
    [K.taxiwayAutoLoadSkip]: 'Not now',
    [K.taxiwayAutoLoadLoad]: 'Load',
    [K.taxiwayAutoLoadLoaded]: 'Nodes loaded',
    [K.taxiwayAutoLoadInvalid]: 'Load failed, invalid file data',
    [K.taxiwayNode]: 'Node',
    [K.taxiwayNodeSettings]: 'Node Settings',
    [K.taxiwayNodeName]: 'Node Name',
    [K.taxiwayNodeNote]: 'Note',
    [K.taxiwayNodeColor]: 'Node Color',
    [K.taxiwayNodeCurrentColor]: 'Current Color',
    [K.taxiwayDeleteNode]: 'Delete Node',
    [K.taxiwayInsertNode]: 'Insert Node',
    [K.taxiwayInsertNodeSuccess]: 'Inserted node on the segment',
    [K.taxiwayEditConnection]: 'Edit Connection',
    [K.taxiwayConnection]: 'Connection',
    [K.taxiwayConnectionRange]: 'Segment',
    [K.taxiwayConnectionName]: 'Connection Name',
    [K.taxiwayConnectionNote]: 'Connection Note',
    [K.taxiwayConnectionColor]: 'Connection Color',
    [K.taxiwayConnectionLineType]: 'Connection Type',
    [K.taxiwayConnectionLineTypeStraight]: 'Straight',
    [K.taxiwayConnectionLineTypeMapMatching]: 'Map Matching',
    [K.taxiwayConnectionCurvature]: 'Curvature',
    [K.taxiwayConnectionCurveDirection]: 'Curve Direction',
    [K.taxiwayConnectionCurveDirectionLeft]: 'Left',
    [K.taxiwayConnectionCurveDirectionRight]: 'Right',
    [K.taxiwayConnectionDragHint]: 'Long press and drag segment to adjust curve',
    [K.taxiwayDangerGeneric]: 'Flight parameters are abnormal. Correct immediately.',
    [K.weatherNoData]: 'No weather data',
    [K.loadingAirportDetail]: 'Loading airport details',
    [K.metarRawShort]: 'RAW',
    [K.metarDecodedShort]: 'DEC',
    [K.approachRuleHint]: 'Flight category derived from METAR visibility and ceiling',
    [K.alertPitchUpDanger]: 'Excessive nose-up attitude',
    [K.alertPitchUpWarning]: 'High pitch angle',
    [K.alertPitchDownDanger]: 'Excessive nose-down attitude',
    [K.alertPitchDownWarning]: 'Steep nose-down attitude',
    [K.alertBankDanger]: 'Dangerous bank angle',
    [K.alertBankWarning]: 'High bank angle',
    [K.alertStallWarning]: 'Stall warning',
    [K.alertSinkRateDanger]: 'Sink rate too high',
    [K.alertSinkRateWarning]: 'High sink rate',
    [K.alertInvertedFlightDanger]: 'Inverted flight attitude danger',
    [K.alertKnifeEdgeDanger]: 'Knife-edge attitude danger',
    [K.alertKnifeEdgeWarning]: 'Approaching knife-edge attitude',
    [K.alertPullUpDanger]: 'Aggressive pull-up danger',
    [K.alertPullUpWarning]: 'High pull-up rate',
    [K.alertPushOverDanger]: 'Aggressive push-over danger',
    [K.alertPushOverWarning]: 'High push-over rate',
    [K.alertSpiralDiveDanger]: 'Spiral dive danger',
    [K.alertSpiralDiveWarning]: 'Approaching spiral dive',
    [K.alertUnusualAttitudeDanger]: 'Unusual attitude danger',
    [K.alertUnusualAttitudeWarning]: 'Unusual attitude warning',
    [K.alertClimbRateDanger]: 'Excessive climb rate',
    [K.alertClimbRateWarning]: 'High climb rate',
    [K.alertDescentRateDanger]: 'Excessive descent rate',
    [K.alertDescentRateWarning]: 'High descent rate',
    [K.alertHighGDanger]: 'Excessive G-force',
    [K.alertHighGWarning]: 'High G-force',
    [K.alertNegativeGDanger]: 'Dangerous negative G-force',
    [K.alertNegativeGWarning]: 'Negative G-force detected',
    [K.alertOverspeedDanger]: 'Dangerous overspeed',
    [K.alertOverspeedWarning]: 'Approaching overspeed',
    [K.aircraftInfoPanelTitle]: 'Aircraft info',
    [K.airportCardCollapse]: 'Collapse',
    [K.airportCardExpand]: 'Expand',
    [K.airportOnRunway]: 'On runway {}',
    [K.airportOnRunwayHint]: 'Your aircraft is currently on this runway',
    [K.airportHere]: 'HERE',
    [K.alertTerrainPullUpDanger]: 'Terrain closure, pull up now',
    [K.alertTerrainPullUpWarning]: 'Rapid descent at low altitude',
    [K.crashTitle]: 'MISSION FAILED',
    [K.crashSubtitle]: 'CRITICAL MISSION FAILURE',
    [K.crashResetButton]: 'Accept Reality (Reset)',
    [K.crashQuote1]: 'Aircraft are sturdy, but the ground is sturdier.',
    [K.crashQuote2]: 'Was that a landing practice or vertical drilling?',
    [K.crashQuote3]: 'At least you landed on Earth.',
    [K.crashQuote4]: 'Good news: in a simulator, reset is always available.',
    [K.crashQuote5]: 'That landing gets 1 point out of 100.',
    [K.crashQuote6]: 'Tower asked if you needed carpet; you gave them a crater.',
    [K.crashQuote7]: 'Your airline might have concerns about contract renewal.',
    [K.crashQuote8]: 'This may qualify as a single-use aircraft.',
    [K.crashQuote9]: 'RIP (Really Interesting Pilot)',
    [K.crashQuote10]: 'With your flying skills, the ground intercepted you successfully.',
    [K.crashQuote11]: 'That was not a landing, it was a controlled crash.',
    [K.crashQuote12]: 'Congratulations, you are now one with Mother Earth.',
  },
};
