import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * Toolbox 模块国际化
 *
 * 对应 Flutter 版 `modules/toolbox/localization/*.dart`（212 个 key）。
 * 由脚本机械转换，key 与文案逐条对齐。
 */
export const ToolboxLocalizationKeys = {
  toolboxTitle: 'toolbox.title',
  unitTab: 'toolbox.tab.unit',
  termsTab: 'toolbox.tab.terms',
  calculatorsTab: 'toolbox.tab.calculators',
  weatherTab: 'toolbox.tab.weather',
  performanceTab: 'toolbox.tab.performance',
  opsTab: 'toolbox.tab.ops',
  commonInputHint: 'toolbox.common.input_hint',
  commonInvalidNumber: 'toolbox.common.invalid_number',
  commonInvalidRange: 'toolbox.common.invalid_range',
  unitSectionTitle: 'toolbox.unit.section_title',
  unitTypeLabel: 'toolbox.unit.type_label',
  unitValueLabel: 'toolbox.unit.value_label',
  unitValueHint: 'toolbox.unit.value_hint',
  unitConvert: 'toolbox.unit.convert',
  unitResult: 'toolbox.unit.result',
  unitInvalidValue: 'toolbox.unit.invalid_value',
  termsSectionTitle: 'toolbox.terms.section_title',
  termsSearchLabel: 'toolbox.terms.search_label',
  termsSearchHint: 'toolbox.terms.search_hint',
  termsCommonTitle: 'toolbox.terms.common_title',
  termsNotFound: 'toolbox.terms.not_found',
  unitHpaToInhg: 'toolbox.unit.hpa_to_inhg',
  unitInhgToHpa: 'toolbox.unit.inhg_to_hpa',
  unitFtToM: 'toolbox.unit.ft_to_m',
  unitMToFt: 'toolbox.unit.m_to_ft',
  unitLbToKg: 'toolbox.unit.lb_to_kg',
  unitKgToLb: 'toolbox.unit.kg_to_lb',
  unitKtToKmh: 'toolbox.unit.kt_to_kmh',
  unitKmhToKt: 'toolbox.unit.kmh_to_kt',
  unitNmToKm: 'toolbox.unit.nm_to_km',
  unitKmToNm: 'toolbox.unit.km_to_nm',
  unitCelsiusToFahrenheit: 'toolbox.unit.celsius_to_fahrenheit',
  unitFahrenheitToCelsius: 'toolbox.unit.fahrenheit_to_celsius',
  calcWindSectionTitle: 'toolbox.calc.wind.section_title',
  calcWindRunwayHeading: 'toolbox.calc.wind.runway_heading',
  calcWindDirection: 'toolbox.calc.wind.direction',
  calcWindSpeed: 'toolbox.calc.wind.speed',
  calcWindButton: 'toolbox.calc.wind.button',
  calcWindResultTitle: 'toolbox.calc.wind.result_title',
  calcWindHeadwind: 'toolbox.calc.wind.headwind',
  calcWindCrosswind: 'toolbox.calc.wind.crosswind',
  calcWindRiskLevel: 'toolbox.calc.wind.risk_level',
  calcWindFromLeft: 'toolbox.calc.wind.from_left',
  calcWindFromRight: 'toolbox.calc.wind.from_right',
  calcWindRiskLow: 'toolbox.calc.wind.risk_low',
  calcWindRiskMedium: 'toolbox.calc.wind.risk_medium',
  calcWindRiskHigh: 'toolbox.calc.wind.risk_high',
  calcDescentSectionTitle: 'toolbox.calc.descent.section_title',
  calcDescentCurrentAlt: 'toolbox.calc.descent.current_alt',
  calcDescentTargetAlt: 'toolbox.calc.descent.target_alt',
  calcDescentGroundSpeed: 'toolbox.calc.descent.ground_speed',
  calcDescentRate: 'toolbox.calc.descent.rate',
  calcDescentDistanceToGo: 'toolbox.calc.descent.distance_to_go',
  calcDescentButton: 'toolbox.calc.descent.button',
  calcDescentResultTitle: 'toolbox.calc.descent.result_title',
  calcDescentAltitudeToLose: 'toolbox.calc.descent.altitude_to_lose',
  calcDescentTime: 'toolbox.calc.descent.time',
  calcDescentTodDistance: 'toolbox.calc.descent.tod_distance',
  calcDescentRuleDistance: 'toolbox.calc.descent.rule_distance',
  calcDescentRequiredVs: 'toolbox.calc.descent.required_vs',
  calcFuelSectionTitle: 'toolbox.calc.fuel.section_title',
  calcFuelDistance: 'toolbox.calc.fuel.distance',
  calcFuelCruiseSpeed: 'toolbox.calc.fuel.cruise_speed',
  calcFuelBurnRate: 'toolbox.calc.fuel.burn_rate',
  calcFuelReserveTime: 'toolbox.calc.fuel.reserve_time',
  calcFuelTaxiFuel: 'toolbox.calc.fuel.taxi_fuel',
  calcFuelExtraPct: 'toolbox.calc.fuel.extra_pct',
  calcFuelButton: 'toolbox.calc.fuel.button',
  calcFuelResultTitle: 'toolbox.calc.fuel.result_title',
  calcFuelTrip: 'toolbox.calc.fuel.trip',
  calcFuelReserve: 'toolbox.calc.fuel.reserve',
  calcFuelTaxi: 'toolbox.calc.fuel.taxi',
  calcFuelExtra: 'toolbox.calc.fuel.extra',
  calcFuelTotal: 'toolbox.calc.fuel.total',
  weatherSectionTitle: 'toolbox.weather.section_title',
  weatherMetarLabel: 'toolbox.weather.metar_label',
  weatherMetarHint: 'toolbox.weather.metar_hint',
  weatherTafLabel: 'toolbox.weather.taf_label',
  weatherTafHint: 'toolbox.weather.taf_hint',
  weatherDecodeButton: 'toolbox.weather.decode_button',
  weatherMetarResultTitle: 'toolbox.weather.metar_result_title',
  weatherTafResultTitle: 'toolbox.weather.taf_result_title',
  weatherRiskResultTitle: 'toolbox.weather.risk_result_title',
  weatherNoMetarInput: 'toolbox.weather.no_metar_input',
  weatherNoTafInput: 'toolbox.weather.no_taf_input',
  weatherFieldWind: 'toolbox.weather.field_wind',
  weatherFieldVisibility: 'toolbox.weather.field_visibility',
  weatherFieldCloud: 'toolbox.weather.field_cloud',
  weatherFieldCeiling: 'toolbox.weather.field_ceiling',
  weatherFieldTempDew: 'toolbox.weather.field_temp_dew',
  weatherFieldQnh: 'toolbox.weather.field_qnh',
  weatherFieldRule: 'toolbox.weather.field_rule',
  weatherTafNormal: 'toolbox.weather.taf_normal',
  weatherTafTempo: 'toolbox.weather.taf_tempo',
  weatherTafBecmg: 'toolbox.weather.taf_becmg',
  weatherTafProb: 'toolbox.weather.taf_prob',
  weatherTafTsCb: 'toolbox.weather.taf_tscb',
  weatherWorstVisibility: 'toolbox.weather.worst_visibility',
  weatherLowestCeiling: 'toolbox.weather.lowest_ceiling',
  weatherRiskLowVis: 'toolbox.weather.risk_low_vis',
  weatherRiskLowCeiling: 'toolbox.weather.risk_low_ceiling',
  weatherRiskWindShear: 'toolbox.weather.risk_wind_shear',
  weatherRiskThunder: 'toolbox.weather.risk_thunder',
  weatherRiskIcing: 'toolbox.weather.risk_icing',
  weatherRiskGust: 'toolbox.weather.risk_gust',
  weatherRiskNone: 'toolbox.weather.risk_none',
  weatherSigmetLabel: 'toolbox.weather.sigmet_label',
  weatherSigmetHint: 'toolbox.weather.sigmet_hint',
  weatherAirmetLabel: 'toolbox.weather.airmet_label',
  weatherAirmetHint: 'toolbox.weather.airmet_hint',
  weatherSigmetResultTitle: 'toolbox.weather.sigmet_result_title',
  weatherAirmetResultTitle: 'toolbox.weather.airmet_result_title',
  weatherNoSigmetInput: 'toolbox.weather.no_sigmet_input',
  weatherNoAirmetInput: 'toolbox.weather.no_airmet_input',
  weatherAdvisoryPeriod: 'toolbox.weather.advisory_period',
  weatherAdvisoryArea: 'toolbox.weather.advisory_area',
  weatherAdvisoryFlightLevel: 'toolbox.weather.advisory_flight_level',
  weatherAdvisoryHazards: 'toolbox.weather.advisory_hazards',
  weatherAdvisoryThunder: 'toolbox.weather.advisory_thunder',
  weatherAdvisoryTurb: 'toolbox.weather.advisory_turb',
  weatherAdvisoryIcing: 'toolbox.weather.advisory_icing',
  weatherAdvisoryMountainWave: 'toolbox.weather.advisory_mountain_wave',
  weatherAdvisoryVolcanic: 'toolbox.weather.advisory_volcanic',
  weatherAdvisoryCyclone: 'toolbox.weather.advisory_cyclone',
  weatherRadarSectionTitle: 'toolbox.weather.radar.section_title',
  weatherRadarRegionLabel: 'toolbox.weather.radar.region_label',
  weatherRadarOpenButton: 'toolbox.weather.radar.open_button',
  weatherRadarGlobal: 'toolbox.weather.radar.global',
  weatherRadarEastAsia: 'toolbox.weather.radar.east_asia',
  weatherRadarEurope: 'toolbox.weather.radar.europe',
  weatherRadarNorthAmerica: 'toolbox.weather.radar.north_america',
  opsNotamSectionTitle: 'toolbox.ops.notam.section_title',
  opsNotamTextLabel: 'toolbox.ops.notam.text_label',
  opsNotamTextHint: 'toolbox.ops.notam.text_hint',
  opsNotamFilterButton: 'toolbox.ops.notam.filter_button',
  opsNotamMatchCount: 'toolbox.ops.notam.match_count',
  opsSeverityHigh: 'toolbox.ops.severity.high',
  opsSeverityMedium: 'toolbox.ops.severity.medium',
  opsSeverityLow: 'toolbox.ops.severity.low',
  opsQuickRefSectionTitle: 'toolbox.ops.quick_ref.section_title',
  opsQuickRefStallTitle: 'toolbox.ops.quick_ref.stall.title',
  opsQuickRefStallTrigger: 'toolbox.ops.quick_ref.stall.trigger',
  opsQuickRefStallAction1: 'toolbox.ops.quick_ref.stall.action1',
  opsQuickRefStallAction2: 'toolbox.ops.quick_ref.stall.action2',
  opsQuickRefStallAction3: 'toolbox.ops.quick_ref.stall.action3',
  opsQuickRefWindshearTitle: 'toolbox.ops.quick_ref.windshear.title',
  opsQuickRefWindshearTrigger: 'toolbox.ops.quick_ref.windshear.trigger',
  opsQuickRefWindshearAction1: 'toolbox.ops.quick_ref.windshear.action1',
  opsQuickRefWindshearAction2: 'toolbox.ops.quick_ref.windshear.action2',
  opsQuickRefWindshearAction3: 'toolbox.ops.quick_ref.windshear.action3',
  opsQuickRefGoAroundTitle: 'toolbox.ops.quick_ref.go_around.title',
  opsQuickRefGoAroundTrigger: 'toolbox.ops.quick_ref.go_around.trigger',
  opsQuickRefGoAroundAction1: 'toolbox.ops.quick_ref.go_around.action1',
  opsQuickRefGoAroundAction2: 'toolbox.ops.quick_ref.go_around.action2',
  opsQuickRefGoAroundAction3: 'toolbox.ops.quick_ref.go_around.action3',
  opsQuickRefEngineFailTitle: 'toolbox.ops.quick_ref.engine_fail.title',
  opsQuickRefEngineFailTrigger: 'toolbox.ops.quick_ref.engine_fail.trigger',
  opsQuickRefEngineFailAction1: 'toolbox.ops.quick_ref.engine_fail.action1',
  opsQuickRefEngineFailAction2: 'toolbox.ops.quick_ref.engine_fail.action2',
  opsQuickRefEngineFailAction3: 'toolbox.ops.quick_ref.engine_fail.action3',
  perfWbSectionTitle: 'toolbox.perf.wb.section_title',
  perfBew: 'toolbox.perf.wb.bew',
  perfBewArm: 'toolbox.perf.wb.bew_arm',
  perfFrontWeight: 'toolbox.perf.wb.front_weight',
  perfRearWeight: 'toolbox.perf.wb.rear_weight',
  perfCargoWeight: 'toolbox.perf.wb.cargo_weight',
  perfFuelWeight: 'toolbox.perf.wb.fuel_weight',
  perfFrontArm: 'toolbox.perf.wb.front_arm',
  perfRearArm: 'toolbox.perf.wb.rear_arm',
  perfCargoArm: 'toolbox.perf.wb.cargo_arm',
  perfFuelArm: 'toolbox.perf.wb.fuel_arm',
  perfMtow: 'toolbox.perf.wb.mtow',
  perfCgForward: 'toolbox.perf.wb.cg_forward',
  perfCgAft: 'toolbox.perf.wb.cg_aft',
  perfWbButton: 'toolbox.perf.wb.button',
  perfWbResultTitle: 'toolbox.perf.wb.result_title',
  perfWbTotalWeight: 'toolbox.perf.wb.total_weight',
  perfWbCgPosition: 'toolbox.perf.wb.cg_position',
  perfWbWeightLimit: 'toolbox.perf.wb.weight_limit',
  perfWbCgLimit: 'toolbox.perf.wb.cg_limit',
  perfWbStatus: 'toolbox.perf.wb.status',
  perfSatisfied: 'toolbox.perf.common.satisfied',
  perfExceeded: 'toolbox.perf.common.exceeded',
  perfDispatchable: 'toolbox.perf.common.dispatchable',
  perfOutOfLimit: 'toolbox.perf.common.out_of_limit',
  perfRunwaySectionTitle: 'toolbox.perf.runway.section_title',
  perfRunwayLength: 'toolbox.perf.runway.length',
  perfPressureAltitude: 'toolbox.perf.runway.pressure_alt',
  perfOat: 'toolbox.perf.runway.oat',
  perfHeadwind: 'toolbox.perf.runway.headwind',
  perfAircraftWeight: 'toolbox.perf.runway.aircraft_weight',
  perfWetRunway: 'toolbox.perf.runway.wet_runway',
  perfRunwayButton: 'toolbox.perf.runway.button',
  perfRunwayResultTitle: 'toolbox.perf.runway.result_title',
  perfTakeoffRequired: 'toolbox.perf.runway.takeoff_required',
  perfLandingRequired: 'toolbox.perf.runway.landing_required',
  perfTakeoffMargin: 'toolbox.perf.runway.takeoff_margin',
  perfLandingMargin: 'toolbox.perf.runway.landing_margin',
  perfRunwayLevel: 'toolbox.perf.runway.level',
  perfMarginHigh: 'toolbox.perf.runway.margin_high',
  perfAcceptable: 'toolbox.perf.runway.acceptable',
  perfNotMet: 'toolbox.perf.runway.not_met',
  perfAircraftType: 'toolbox.perf.runway.aircraft_type',
  perfAircraftTolissA320: 'toolbox.perf.runway.aircraft_toliss_a320',
  perfAircraftPmdgB737: 'toolbox.perf.runway.aircraft_pmdg_b737',
  perfV1: 'toolbox.perf.runway.v1',
  perfVr: 'toolbox.perf.runway.vr',
  perfV2: 'toolbox.perf.runway.v2',
  perfFlexTemp: 'toolbox.perf.runway.flex_temp',
  perfFlexNotRecommended: 'toolbox.perf.runway.flex_not_recommended',
  perfWeightRangeHint: 'toolbox.perf.runway.weight_range',
} as const;

const K = ToolboxLocalizationKeys;

export const toolboxTranslations: ModuleTranslations = {
  zh_CN: {
    [K.toolboxTitle]: '工具箱',
    [K.unitTab]: '单位换算',
    [K.termsTab]: '术语翻译',
    [K.calculatorsTab]: '飞行计算',
    [K.weatherTab]: '天气解码',
    [K.performanceTab]: '性能评估',
    [K.opsTab]: '运行工具',
    [K.unitSectionTitle]: '数值换算',
    [K.unitTypeLabel]: '换算类型',
    [K.unitValueLabel]: '输入数值',
    [K.unitValueHint]: '请输入要换算的数字...',
    [K.unitConvert]: '立即换算',
    [K.unitResult]: '换算结果',
    [K.unitInvalidValue]: '无效数值',
    [K.termsSectionTitle]: '航空术语翻译',
    [K.termsSearchLabel]: '输入英文术语/简写/中文',
    [K.termsSearchHint]: '例如: V1, ILS, 气压...',
    [K.termsCommonTitle]: '常见术语参考',
    [K.termsNotFound]: '未找到相关术语',
    [K.unitHpaToInhg]: 'hPa 转 inHg',
    [K.unitInhgToHpa]: 'inHg 转 hPa',
    [K.unitFtToM]: 'ft 转 m',
    [K.unitMToFt]: 'm 转 ft',
    [K.unitLbToKg]: 'lb 转 kg',
    [K.unitKgToLb]: 'kg 转 lb',
    [K.unitKtToKmh]: 'kt 转 km/h',
    [K.unitKmhToKt]: 'km/h 转 kt',
    [K.unitNmToKm]: 'NM 转 km',
    [K.unitKmToNm]: 'km 转 NM',
    [K.unitCelsiusToFahrenheit]: '摄氏度 转 华氏度',
    [K.unitFahrenheitToCelsius]: '华氏度 转 摄氏度',
    [K.commonInputHint]: '请输入',
    [K.commonInvalidNumber]: '请输入有效数字',
    [K.commonInvalidRange]: '参数范围无效',
    [K.calcWindSectionTitle]: '侧风 / 逆风分量计算',
    [K.calcWindRunwayHeading]: '跑道航向(°)',
    [K.calcWindDirection]: '风向(°)',
    [K.calcWindSpeed]: '风速(kt)',
    [K.calcWindButton]: '计算分量',
    [K.calcWindResultTitle]: '计算结果',
    [K.calcWindHeadwind]: '迎/顺风分量',
    [K.calcWindCrosswind]: '侧风分量',
    [K.calcWindRiskLevel]: '侧风风险等级',
    [K.calcWindFromLeft]: '左侧',
    [K.calcWindFromRight]: '右侧',
    [K.calcWindRiskLow]: '低',
    [K.calcWindRiskMedium]: '中',
    [K.calcWindRiskHigh]: '高',
    [K.calcDescentSectionTitle]: '下降规划 / TOD',
    [K.calcDescentCurrentAlt]: '当前高度(ft)',
    [K.calcDescentTargetAlt]: '目标高度(ft)',
    [K.calcDescentGroundSpeed]: '地速(kt)',
    [K.calcDescentRate]: '下降率(fpm)',
    [K.calcDescentDistanceToGo]: '当前剩余距离(NM)',
    [K.calcDescentButton]: '计算TOD',
    [K.calcDescentResultTitle]: '规划结果',
    [K.calcDescentAltitudeToLose]: '需下降高度',
    [K.calcDescentTime]: '预计下降时间',
    [K.calcDescentTodDistance]: 'TOD 参考距离',
    [K.calcDescentRuleDistance]: '3:1 规则距离',
    [K.calcDescentRequiredVs]: '按剩余距离所需下降率',
    [K.calcFuelSectionTitle]: '燃油快速评估',
    [K.calcFuelDistance]: '计划航程(NM)',
    [K.calcFuelCruiseSpeed]: '巡航速度(kt)',
    [K.calcFuelBurnRate]: '平均耗油(kg/h)',
    [K.calcFuelReserveTime]: '储备时间(min)',
    [K.calcFuelTaxiFuel]: '滑行油量(kg)',
    [K.calcFuelExtraPct]: '额外油量(%)',
    [K.calcFuelButton]: '估算油量',
    [K.calcFuelResultTitle]: '估算结果',
    [K.calcFuelTrip]: '航程油量',
    [K.calcFuelReserve]: '备份油量',
    [K.calcFuelTaxi]: '滑行油量',
    [K.calcFuelExtra]: '额外油量',
    [K.calcFuelTotal]: '总建议油量',
    [K.weatherSectionTitle]: 'METAR / TAF 解码',
    [K.weatherMetarLabel]: 'METAR 原文',
    [K.weatherMetarHint]: '例如: ZBAA 121400Z 34008KT 6000 BKN020 12/04 Q1018',
    [K.weatherTafLabel]: 'TAF 原文',
    [K.weatherTafHint]: '例如: TAF ZBAA 121100Z ...',
    [K.weatherDecodeButton]: '解码天气',
    [K.weatherMetarResultTitle]: 'METAR 解析',
    [K.weatherTafResultTitle]: 'TAF 解析',
    [K.weatherRiskResultTitle]: '风险提示',
    [K.weatherNoMetarInput]: '未输入 METAR',
    [K.weatherNoTafInput]: '未输入 TAF',
    [K.weatherFieldWind]: '风',
    [K.weatherFieldVisibility]: '能见度',
    [K.weatherFieldCloud]: '云况',
    [K.weatherFieldCeiling]: '云底',
    [K.weatherFieldTempDew]: '温度/露点',
    [K.weatherFieldQnh]: '修压',
    [K.weatherFieldRule]: '飞行规则',
    [K.weatherTafNormal]: '结构特征：常规',
    [K.weatherTafTempo]: '包含短时变化 TEMPO',
    [K.weatherTafBecmg]: '包含渐变时段 BECMG',
    [K.weatherTafProb]: '包含概率预报 PROB',
    [K.weatherTafTsCb]: '含雷暴对流信号',
    [K.weatherWorstVisibility]: '最差能见度',
    [K.weatherLowestCeiling]: '最低云底',
    [K.weatherRiskLowVis]: '当前能见度低于 3SM',
    [K.weatherRiskLowCeiling]: '当前云底低于 1000ft',
    [K.weatherRiskWindShear]: '存在风切变信号',
    [K.weatherRiskThunder]: '存在雷暴风险',
    [K.weatherRiskIcing]: '存在结冰风险',
    [K.weatherRiskGust]: '存在阵风波动',
    [K.weatherRiskNone]: '未识别到高风险关键字',
    [K.weatherSigmetLabel]: 'SIGMET 原文',
    [K.weatherSigmetHint]: '例如: ZBPE SIGMET 2 VALID 121200/121600 ZBAA- TS FCST',
    [K.weatherAirmetLabel]: 'AIRMET 原文',
    [K.weatherAirmetHint]: '例如: ZBPE AIRMET 1 VALID 121200/121800 ZBAA- MOD TURB FL100/180',
    [K.weatherSigmetResultTitle]: 'SIGMET 解析',
    [K.weatherAirmetResultTitle]: 'AIRMET 解析',
    [K.weatherNoSigmetInput]: '未输入 SIGMET',
    [K.weatherNoAirmetInput]: '未输入 AIRMET',
    [K.weatherAdvisoryPeriod]: '生效时段',
    [K.weatherAdvisoryArea]: '影响区域',
    [K.weatherAdvisoryFlightLevel]: '高度层',
    [K.weatherAdvisoryHazards]: '危险要素',
    [K.weatherAdvisoryThunder]: '雷暴/积雨云',
    [K.weatherAdvisoryTurb]: '中度以上颠簸',
    [K.weatherAdvisoryIcing]: '结冰',
    [K.weatherAdvisoryMountainWave]: '山地波',
    [K.weatherAdvisoryVolcanic]: '火山灰',
    [K.weatherAdvisoryCyclone]: '热带气旋',
    [K.weatherRadarSectionTitle]: '降水雷达',
    [K.weatherRadarRegionLabel]: '雷达区域',
    [K.weatherRadarOpenButton]: '打开雷达图',
    [K.weatherRadarGlobal]: '全球',
    [K.weatherRadarEastAsia]: '东亚',
    [K.weatherRadarEurope]: '欧洲',
    [K.weatherRadarNorthAmerica]: '北美',
    [K.opsNotamSectionTitle]: 'NOTAM 关键筛选',
    [K.opsNotamTextLabel]: 'NOTAM 文本',
    [K.opsNotamTextHint]: '粘贴多行 NOTAM 文本',
    [K.opsNotamFilterButton]: '筛选关键项',
    [K.opsNotamMatchCount]: '匹配结果',
    [K.opsSeverityHigh]: '高',
    [K.opsSeverityMedium]: '中',
    [K.opsSeverityLow]: '低',
    [K.opsQuickRefSectionTitle]: '应急速查卡',
    [K.opsQuickRefStallTitle]: '失速警告',
    [K.opsQuickRefStallTrigger]: 'Airspeed 下降并触发失速告警',
    [K.opsQuickRefStallAction1]: '减小迎角，解除抬头趋势',
    [K.opsQuickRefStallAction2]: '平稳加油门并保持机翼水平',
    [K.opsQuickRefStallAction3]: '按程序逐步收回减阻构型',
    [K.opsQuickRefWindshearTitle]: '风切变逃逸',
    [K.opsQuickRefWindshearTrigger]: '近地面风速或垂直速度突变',
    [K.opsQuickRefWindshearAction1]: '按风切变口令执行最大持续推力',
    [K.opsQuickRefWindshearAction2]: '保持机翼水平，目标姿态约 15°',
    [K.opsQuickRefWindshearAction3]: '除非撞地风险，不要改变构型',
    [K.opsQuickRefGoAroundTitle]: '复飞程序',
    [K.opsQuickRefGoAroundTrigger]: '进近不稳定或跑道条件不满足',
    [K.opsQuickRefGoAroundAction1]: '执行 TOGA 推力并建立正爬升',
    [K.opsQuickRefGoAroundAction2]: '按标准复飞高度和航向执行',
    [K.opsQuickRefGoAroundAction3]: '确认构型并完成复飞检查单',
    [K.opsQuickRefEngineFailTitle]: '发动机失效（起飞后）',
    [K.opsQuickRefEngineFailTrigger]: '起飞后出现推力不对称',
    [K.opsQuickRefEngineFailAction1]: '方向舵保持航向并控制姿态',
    [K.opsQuickRefEngineFailAction2]: '维持安全速度并确认单发程序',
    [K.opsQuickRefEngineFailAction3]: '根据场景决定继续爬升或返航',
    [K.perfWbSectionTitle]: '重量重心估算',
    [K.perfBew]: '基础空重(kg)',
    [K.perfBewArm]: '基础空重臂位',
    [K.perfFrontWeight]: '前舱载荷(kg)',
    [K.perfRearWeight]: '后舱载荷(kg)',
    [K.perfCargoWeight]: '货舱载荷(kg)',
    [K.perfFuelWeight]: '燃油重量(kg)',
    [K.perfFrontArm]: '前舱臂位',
    [K.perfRearArm]: '后舱臂位',
    [K.perfCargoArm]: '货舱臂位',
    [K.perfFuelArm]: '燃油臂位',
    [K.perfMtow]: '最大起飞重量(kg)',
    [K.perfCgForward]: '重心前限',
    [K.perfCgAft]: '重心后限',
    [K.perfWbButton]: '评估重心',
    [K.perfWbResultTitle]: '重心评估',
    [K.perfWbTotalWeight]: '总重',
    [K.perfWbCgPosition]: '重心位置',
    [K.perfWbWeightLimit]: '重量限制',
    [K.perfWbCgLimit]: '重心限制',
    [K.perfWbStatus]: '结果',
    [K.perfSatisfied]: '满足',
    [K.perfExceeded]: '超出',
    [K.perfDispatchable]: '可放行',
    [K.perfOutOfLimit]: '超限',
    [K.perfRunwaySectionTitle]: '起降性能评估',
    [K.perfRunwayLength]: '可用跑道长度(m)',
    [K.perfPressureAltitude]: '气压高度(ft)',
    [K.perfOat]: '室外温度(°C)',
    [K.perfHeadwind]: '迎风分量(kt, 顺风填负值)',
    [K.perfAircraftWeight]: '当前重量(kg)',
    [K.perfWetRunway]: '湿跑道修正',
    [K.perfRunwayButton]: '评估起降性能',
    [K.perfRunwayResultTitle]: '性能评估',
    [K.perfTakeoffRequired]: '起飞距离需求',
    [K.perfLandingRequired]: '着陆距离需求',
    [K.perfTakeoffMargin]: '起飞裕度',
    [K.perfLandingMargin]: '着陆裕度',
    [K.perfRunwayLevel]: '评估结果',
    [K.perfMarginHigh]: '安全裕度高',
    [K.perfAcceptable]: '可接受',
    [K.perfNotMet]: '不满足',
    [K.perfAircraftType]: '机型',
    [K.perfAircraftTolissA320]: 'Toliss A320 系列',
    [K.perfAircraftPmdgB737]: 'PMDG 737 系列',
    [K.perfV1]: 'V1',
    [K.perfVr]: 'VR',
    [K.perfV2]: 'V2',
    [K.perfFlexTemp]: 'FLEX/ASSUMED 温度',
    [K.perfFlexNotRecommended]: '不建议使用减推',
    [K.perfWeightRangeHint]: '机型参考重量范围',
  },
  en_US: {
    [K.toolboxTitle]: 'Toolbox',
    [K.unitTab]: 'Unit Conversion',
    [K.termsTab]: 'Term Translation',
    [K.calculatorsTab]: 'Flight Calculators',
    [K.weatherTab]: 'Weather Decode',
    [K.performanceTab]: 'Performance',
    [K.opsTab]: 'Ops Tools',
    [K.unitSectionTitle]: 'Unit Converter',
    [K.unitTypeLabel]: 'Conversion Type',
    [K.unitValueLabel]: 'Input Value',
    [K.unitValueHint]: 'Enter a value to convert...',
    [K.unitConvert]: 'Convert Now',
    [K.unitResult]: 'Result',
    [K.unitInvalidValue]: 'Invalid value',
    [K.termsSectionTitle]: 'Aviation Term Translator',
    [K.termsSearchLabel]: 'Enter English term / abbreviation / Chinese',
    [K.termsSearchHint]: 'For example: V1, ILS, QNH...',
    [K.termsCommonTitle]: 'Common Terms',
    [K.termsNotFound]: 'No matching terms found',
    [K.unitHpaToInhg]: 'hPa to inHg',
    [K.unitInhgToHpa]: 'inHg to hPa',
    [K.unitFtToM]: 'ft to m',
    [K.unitMToFt]: 'm to ft',
    [K.unitLbToKg]: 'lb to kg',
    [K.unitKgToLb]: 'kg to lb',
    [K.unitKtToKmh]: 'kt to km/h',
    [K.unitKmhToKt]: 'km/h to kt',
    [K.unitNmToKm]: 'NM to km',
    [K.unitKmToNm]: 'km to NM',
    [K.unitCelsiusToFahrenheit]: 'Celsius to Fahrenheit',
    [K.unitFahrenheitToCelsius]: 'Fahrenheit to Celsius',
    [K.commonInputHint]: 'Enter value',
    [K.commonInvalidNumber]: 'Please enter valid numbers',
    [K.commonInvalidRange]: 'Invalid parameter range',
    [K.calcWindSectionTitle]: 'Crosswind / Headwind',
    [K.calcWindRunwayHeading]: 'Runway Heading (°)',
    [K.calcWindDirection]: 'Wind Direction (°)',
    [K.calcWindSpeed]: 'Wind Speed (kt)',
    [K.calcWindButton]: 'Calculate Components',
    [K.calcWindResultTitle]: 'Calculation Result',
    [K.calcWindHeadwind]: 'Head/Tailwind Component',
    [K.calcWindCrosswind]: 'Crosswind Component',
    [K.calcWindRiskLevel]: 'Crosswind Risk Level',
    [K.calcWindFromLeft]: 'Left',
    [K.calcWindFromRight]: 'Right',
    [K.calcWindRiskLow]: 'Low',
    [K.calcWindRiskMedium]: 'Medium',
    [K.calcWindRiskHigh]: 'High',
    [K.calcDescentSectionTitle]: 'Descent Planning / TOD',
    [K.calcDescentCurrentAlt]: 'Current Altitude (ft)',
    [K.calcDescentTargetAlt]: 'Target Altitude (ft)',
    [K.calcDescentGroundSpeed]: 'Ground Speed (kt)',
    [K.calcDescentRate]: 'Descent Rate (fpm)',
    [K.calcDescentDistanceToGo]: 'Distance To Go (NM)',
    [K.calcDescentButton]: 'Calculate TOD',
    [K.calcDescentResultTitle]: 'Planning Result',
    [K.calcDescentAltitudeToLose]: 'Altitude to Lose',
    [K.calcDescentTime]: 'Estimated Descent Time',
    [K.calcDescentTodDistance]: 'TOD Reference Distance',
    [K.calcDescentRuleDistance]: '3:1 Rule Distance',
    [K.calcDescentRequiredVs]: 'Required Vertical Speed for Remaining Distance',
    [K.calcFuelSectionTitle]: 'Fuel Quick Estimation',
    [K.calcFuelDistance]: 'Planned Distance (NM)',
    [K.calcFuelCruiseSpeed]: 'Cruise Speed (kt)',
    [K.calcFuelBurnRate]: 'Average Burn (kg/h)',
    [K.calcFuelReserveTime]: 'Reserve Time (min)',
    [K.calcFuelTaxiFuel]: 'Taxi Fuel (kg)',
    [K.calcFuelExtraPct]: 'Extra Fuel (%)',
    [K.calcFuelButton]: 'Estimate Fuel',
    [K.calcFuelResultTitle]: 'Estimation Result',
    [K.calcFuelTrip]: 'Trip Fuel',
    [K.calcFuelReserve]: 'Reserve Fuel',
    [K.calcFuelTaxi]: 'Taxi Fuel',
    [K.calcFuelExtra]: 'Extra Fuel',
    [K.calcFuelTotal]: 'Recommended Total Fuel',
    [K.weatherSectionTitle]: 'METAR / TAF Decode',
    [K.weatherMetarLabel]: 'METAR Raw',
    [K.weatherMetarHint]: 'e.g. ZBAA 121400Z 34008KT 6000 BKN020 12/04 Q1018',
    [K.weatherTafLabel]: 'TAF Raw',
    [K.weatherTafHint]: 'e.g. TAF ZBAA 121100Z ...',
    [K.weatherDecodeButton]: 'Decode Weather',
    [K.weatherMetarResultTitle]: 'METAR Analysis',
    [K.weatherTafResultTitle]: 'TAF Analysis',
    [K.weatherRiskResultTitle]: 'Risk Alerts',
    [K.weatherNoMetarInput]: 'No METAR input',
    [K.weatherNoTafInput]: 'No TAF input',
    [K.weatherFieldWind]: 'Wind',
    [K.weatherFieldVisibility]: 'Visibility',
    [K.weatherFieldCloud]: 'Clouds',
    [K.weatherFieldCeiling]: 'Ceiling',
    [K.weatherFieldTempDew]: 'Temp/Dew',
    [K.weatherFieldQnh]: 'Pressure',
    [K.weatherFieldRule]: 'Flight Rule',
    [K.weatherTafNormal]: 'Structure: Normal',
    [K.weatherTafTempo]: 'Contains temporary change TEMPO',
    [K.weatherTafBecmg]: 'Contains gradual change BECMG',
    [K.weatherTafProb]: 'Contains probability group PROB',
    [K.weatherTafTsCb]: 'Contains convective signal',
    [K.weatherWorstVisibility]: 'Worst Visibility',
    [K.weatherLowestCeiling]: 'Lowest Ceiling',
    [K.weatherRiskLowVis]: 'Current visibility below 3SM',
    [K.weatherRiskLowCeiling]: 'Current ceiling below 1000ft',
    [K.weatherRiskWindShear]: 'Wind shear signal detected',
    [K.weatherRiskThunder]: 'Thunderstorm risk detected',
    [K.weatherRiskIcing]: 'Icing risk detected',
    [K.weatherRiskGust]: 'Gust fluctuation detected',
    [K.weatherRiskNone]: 'No high-risk keywords detected',
    [K.weatherSigmetLabel]: 'SIGMET Raw',
    [K.weatherSigmetHint]: 'e.g. ZBPE SIGMET 2 VALID 121200/121600 ZBAA- TS FCST',
    [K.weatherAirmetLabel]: 'AIRMET Raw',
    [K.weatherAirmetHint]: 'e.g. ZBPE AIRMET 1 VALID 121200/121800 ZBAA- MOD TURB FL100/180',
    [K.weatherSigmetResultTitle]: 'SIGMET Analysis',
    [K.weatherAirmetResultTitle]: 'AIRMET Analysis',
    [K.weatherNoSigmetInput]: 'No SIGMET input',
    [K.weatherNoAirmetInput]: 'No AIRMET input',
    [K.weatherAdvisoryPeriod]: 'Valid Period',
    [K.weatherAdvisoryArea]: 'Area',
    [K.weatherAdvisoryFlightLevel]: 'Flight Level',
    [K.weatherAdvisoryHazards]: 'Hazards',
    [K.weatherAdvisoryThunder]: 'Thunderstorm / CB',
    [K.weatherAdvisoryTurb]: 'Moderate+ Turbulence',
    [K.weatherAdvisoryIcing]: 'Icing',
    [K.weatherAdvisoryMountainWave]: 'Mountain Wave',
    [K.weatherAdvisoryVolcanic]: 'Volcanic Ash',
    [K.weatherAdvisoryCyclone]: 'Tropical Cyclone',
    [K.weatherRadarSectionTitle]: 'Precipitation Radar',
    [K.weatherRadarRegionLabel]: 'Radar Region',
    [K.weatherRadarOpenButton]: 'Open Radar',
    [K.weatherRadarGlobal]: 'Global',
    [K.weatherRadarEastAsia]: 'East Asia',
    [K.weatherRadarEurope]: 'Europe',
    [K.weatherRadarNorthAmerica]: 'North America',
    [K.opsNotamSectionTitle]: 'NOTAM Key Filter',
    [K.opsNotamTextLabel]: 'NOTAM Text',
    [K.opsNotamTextHint]: 'Paste multiple NOTAM lines',
    [K.opsNotamFilterButton]: 'Filter Key Items',
    [K.opsNotamMatchCount]: 'Matched Items',
    [K.opsSeverityHigh]: 'High',
    [K.opsSeverityMedium]: 'Medium',
    [K.opsSeverityLow]: 'Low',
    [K.opsQuickRefSectionTitle]: 'Emergency Quick Reference',
    [K.opsQuickRefStallTitle]: 'Stall Warning',
    [K.opsQuickRefStallTrigger]: 'Airspeed drops with stall warning',
    [K.opsQuickRefStallAction1]: 'Reduce angle of attack and stop pitch-up',
    [K.opsQuickRefStallAction2]: 'Smoothly add thrust and keep wings level',
    [K.opsQuickRefStallAction3]: 'Retract drag devices step by step as required',
    [K.opsQuickRefWindshearTitle]: 'Windshear Escape',
    [K.opsQuickRefWindshearTrigger]: 'Sudden low-level wind or vertical speed change',
    [K.opsQuickRefWindshearAction1]: 'Apply maximum continuous thrust by procedure',
    [K.opsQuickRefWindshearAction2]: 'Keep wings level with about 15° pitch target',
    [K.opsQuickRefWindshearAction3]: 'Do not change configuration unless terrain risk',
    [K.opsQuickRefGoAroundTitle]: 'Go-Around Procedure',
    [K.opsQuickRefGoAroundTrigger]: 'Unstable approach or runway criteria not met',
    [K.opsQuickRefGoAroundAction1]: 'Apply TOGA thrust and establish positive climb',
    [K.opsQuickRefGoAroundAction2]: 'Follow standard go-around altitude and heading',
    [K.opsQuickRefGoAroundAction3]: 'Confirm configuration and complete checklist',
    [K.opsQuickRefEngineFailTitle]: 'Engine Failure (After Takeoff)',
    [K.opsQuickRefEngineFailTrigger]: 'Asymmetric thrust after takeoff',
    [K.opsQuickRefEngineFailAction1]: 'Use rudder to hold heading and control attitude',
    [K.opsQuickRefEngineFailAction2]: 'Maintain safe speed and confirm OEI procedure',
    [K.opsQuickRefEngineFailAction3]: 'Decide climb continuation or return based on scenario',
    [K.perfWbSectionTitle]: 'Weight & Balance Estimation',
    [K.perfBew]: 'Basic Empty Weight (kg)',
    [K.perfBewArm]: 'BEW Arm',
    [K.perfFrontWeight]: 'Front Cabin Load (kg)',
    [K.perfRearWeight]: 'Rear Cabin Load (kg)',
    [K.perfCargoWeight]: 'Cargo Load (kg)',
    [K.perfFuelWeight]: 'Fuel Weight (kg)',
    [K.perfFrontArm]: 'Front Arm',
    [K.perfRearArm]: 'Rear Arm',
    [K.perfCargoArm]: 'Cargo Arm',
    [K.perfFuelArm]: 'Fuel Arm',
    [K.perfMtow]: 'Maximum Takeoff Weight (kg)',
    [K.perfCgForward]: 'Forward CG Limit',
    [K.perfCgAft]: 'Aft CG Limit',
    [K.perfWbButton]: 'Evaluate CG',
    [K.perfWbResultTitle]: 'CG Evaluation',
    [K.perfWbTotalWeight]: 'Total Weight',
    [K.perfWbCgPosition]: 'CG Position',
    [K.perfWbWeightLimit]: 'Weight Limit',
    [K.perfWbCgLimit]: 'CG Limit',
    [K.perfWbStatus]: 'Result',
    [K.perfSatisfied]: 'Within',
    [K.perfExceeded]: 'Exceeded',
    [K.perfDispatchable]: 'Dispatchable',
    [K.perfOutOfLimit]: 'Out of Limit',
    [K.perfRunwaySectionTitle]: 'Takeoff/Landing Performance',
    [K.perfRunwayLength]: 'Available Runway Length (m)',
    [K.perfPressureAltitude]: 'Pressure Altitude (ft)',
    [K.perfOat]: 'Outside Air Temp (°C)',
    [K.perfHeadwind]: 'Headwind (kt, tailwind as negative)',
    [K.perfAircraftWeight]: 'Current Weight (kg)',
    [K.perfWetRunway]: 'Wet Runway Correction',
    [K.perfRunwayButton]: 'Evaluate T/O & Landing',
    [K.perfRunwayResultTitle]: 'Performance Result',
    [K.perfTakeoffRequired]: 'Takeoff Distance Required',
    [K.perfLandingRequired]: 'Landing Distance Required',
    [K.perfTakeoffMargin]: 'Takeoff Margin',
    [K.perfLandingMargin]: 'Landing Margin',
    [K.perfRunwayLevel]: 'Evaluation',
    [K.perfMarginHigh]: 'High Safety Margin',
    [K.perfAcceptable]: 'Acceptable',
    [K.perfNotMet]: 'Not Met',
    [K.perfAircraftType]: 'Aircraft',
    [K.perfAircraftTolissA320]: 'Toliss A320 Family',
    [K.perfAircraftPmdgB737]: 'PMDG 737 Family',
    [K.perfV1]: 'V1',
    [K.perfVr]: 'VR',
    [K.perfV2]: 'V2',
    [K.perfFlexTemp]: 'FLEX/Assumed Temp',
    [K.perfFlexNotRecommended]: 'Reduced thrust not recommended',
    [K.perfWeightRangeHint]: 'Aircraft reference weight range',
  },
};
