import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * Home 模块国际化
 *
 * 对应 Flutter 版 `modules/home/localization/{home_localization_keys,home_translations}.dart`
 * （133 个 key，zh_CN / en_US 两种语言，逐条对齐）。
 */
export const HomeLocalizationKeys = {
  homeTitle: 'home.nav.title',

  // ── 欢迎卡片 ──
  welcomeNotConnectedTitle: 'home.welcome.not_connected',
  welcomeNotConnectedSubtitle: 'home.welcome.not_connected_subtitle',
  welcomePausedTitle: 'home.welcome.paused',
  welcomePausedSubtitle: 'home.welcome.paused_subtitle',
  welcomeReadyTitle: 'home.welcome.ready',
  welcomeReadySubtitle: 'home.welcome.ready_subtitle_with_aircraft',
  welcomeReadySubtitleWaiting: 'home.welcome.ready_subtitle_waiting',
  welcomeSupportSims: 'home.welcome.support_sims',

  // ── 应答机 ──
  transponderPrefix: 'home.welcome.transponder_prefix',
  transponderEmergency: 'home.welcome.transponder_7700',
  transponderHijack: 'home.welcome.transponder_7500',
  transponderRadioFailure: 'home.welcome.transponder_7600',

  // ── 模拟器连接 ──
  simTitle: 'home.sim.title',
  simConnected: 'home.sim.connected',
  simDisconnected: 'home.sim.disconnected',
  simDisconnect: 'home.sim.disconnect',
  simConnect: 'home.sim.connect',
  simConnectXplane: 'home.sim.connect_xplane',
  simConnectMsfs: 'home.sim.connect_msfs',
  simConnectingTitle: 'home.sim.connecting_title',
  simConnectingSubtitle: 'home.sim.connecting_subtitle',
  simConnectFailedTitle: 'home.sim.connect_failed_title',
  simConnectFailedContent: 'home.sim.connect_failed_content',
  simRecording: 'home.sim.recording',

  // ── 检查单阶段卡片 ──
  checklistTitle: 'home.checklist.title',
  checklistEmpty: 'home.checklist.empty',

  // ── 航班号 ──
  flightNumberTitle: 'home.flight_number.title',
  flightNumberEmpty: 'home.flight_number.empty',
  flightNumberSet: 'home.flight_number.set',
  flightNumberEdit: 'home.flight_number.edit',
  flightNumberDialogTitle: 'home.flight_number.dialog_title',
  flightNumberDialogHint: 'home.flight_number.dialog_hint',
  flightNumberDialogFormat: 'home.flight_number.dialog_format',
  flightNumberDialogConfirm: 'home.flight_number.dialog_confirm',
  flightNumberDialogCancel: 'home.flight_number.dialog_cancel',
  flightNumberDialogEditTitle: 'home.flight_number.dialog_edit_title',
  flightNumberDialogEditContent: 'home.flight_number.dialog_edit_content',
  flightNumberDialogContinue: 'home.flight_number.dialog_continue',
  flightNumberDialogInputHint: 'home.flight_number.dialog_input_hint',
  flightNumberDialogInvalid: 'home.flight_number.dialog_invalid',

  // ── 仪表盘 ──
  dashboardTitle: 'home.dashboard.title',
  dashboardNoConnectionTitle: 'home.dashboard.no_connection_title',
  dashboardNoConnectionSubtitle: 'home.dashboard.no_connection_subtitle',

  // ── 后端离线遮罩 ──
  homeMaskConnectBackendTitle: 'home.mask.connect_backend_title',
  homeMaskConnectBackendSubtitle: 'home.mask.connect_backend_subtitle',
  homeMaskRetryButton: 'home.mask.retry_button',
  homeMaskRetryingButton: 'home.mask.retrying_button',

  // ── 主飞行数据面板 ──
  primaryAirspeed: 'home.dashboard.primary.airspeed',
  primaryAltitude: 'home.dashboard.primary.altitude',
  primaryHeading: 'home.dashboard.primary.heading',
  primaryVerticalSpeed: 'home.dashboard.primary.vertical_speed',
  primaryFuelStatus: 'home.dashboard.primary.fuel_status',
  primaryFuelOk: 'home.dashboard.primary.fuel_ok',
  primaryFuelLow: 'home.dashboard.primary.fuel_low',
  primaryFuelUnknown: 'home.dashboard.primary.fuel_unknown',

  // ── 导航与位置面板 ──
  navTitle: 'home.dashboard.nav.title',
  navGroundSpeed: 'home.dashboard.nav.ground_speed',
  navTrueAirspeed: 'home.dashboard.nav.true_airspeed',
  navLatitude: 'home.dashboard.nav.latitude',
  navLongitude: 'home.dashboard.nav.longitude',
  navAircraft: 'home.dashboard.nav.aircraft',
  navAircraftIcao: 'home.dashboard.nav.aircraft_icao',
  navArrival: 'home.dashboard.nav.arrival',
  navCom1: 'home.dashboard.nav.com1',
  navSetDeparture: 'home.dashboard.nav.set_departure',
  navSetDestination: 'home.dashboard.nav.set_destination',
  navSetAlternate: 'home.dashboard.nav.set_alternate',
  navPickDepartureTitle: 'home.dashboard.nav.pick_departure_title',
  navPickDestinationTitle: 'home.dashboard.nav.pick_destination_title',
  navPickAlternateTitle: 'home.dashboard.nav.pick_alternate_title',
  navRecentAirports: 'home.dashboard.nav.recent_airports',
  navClearSelection: 'home.dashboard.nav.clear_selection',
  navCancel: 'home.dashboard.nav.cancel',

  // ── 环境数据面板 ──
  environmentTitle: 'home.dashboard.environment.title',
  environmentOat: 'home.dashboard.environment.oat',
  environmentTat: 'home.dashboard.environment.tat',
  environmentWind: 'home.dashboard.environment.wind',
  environmentQnh: 'home.dashboard.environment.qnh',
  environmentVisibility: 'home.dashboard.environment.visibility',

  // ── 发动机与燃油面板 ──
  engineTitle: 'home.dashboard.engine.title',
  engineFob: 'home.dashboard.engine.fob',
  engineFf: 'home.dashboard.engine.ff',
  engineEng1N1: 'home.dashboard.engine.eng1_n1',
  engineEng2N1: 'home.dashboard.engine.eng2_n1',
  engineEng1Egt: 'home.dashboard.engine.eng1_egt',
  engineEng2Egt: 'home.dashboard.engine.eng2_egt',

  // ── METAR ──
  metarTitle: 'home.dashboard.metar.title',
  metarUpdatedAt: 'home.dashboard.metar.updated_at',
  metarWind: 'home.dashboard.metar.wind',
  metarVisibility: 'home.dashboard.metar.visibility',
  metarTemperature: 'home.dashboard.metar.temperature',
  metarAltimeter: 'home.dashboard.metar.altimeter',
  metarErrorTitle: 'home.dashboard.metar.error_title',
  metarErrorSubtitle: 'home.dashboard.metar.error_subtitle',
  metarErrorDefault: 'home.dashboard.metar.error_default',

  // ── 系统状态面板 ──
  systemTitle: 'home.dashboard.system.title',
  systemSectionWarning: 'home.dashboard.system.section_warning',
  systemSectionFlightControl: 'home.dashboard.system.section_flight_control',
  systemSectionGear: 'home.dashboard.system.section_gear',
  systemSectionFlaps: 'home.dashboard.system.section_flaps',
  systemSectionPower: 'home.dashboard.system.section_power',
  systemSectionLights: 'home.dashboard.system.section_lights',
  systemMasterWarning: 'home.dashboard.system.master_warning',
  systemMasterCaution: 'home.dashboard.system.master_caution',
  systemFireEngine1: 'home.dashboard.system.fire_engine1',
  systemFireEngine2: 'home.dashboard.system.fire_engine2',
  systemFireApu: 'home.dashboard.system.fire_apu',
  systemOnGround: 'home.dashboard.system.on_ground',
  systemParkingBrake: 'home.dashboard.system.parking_brake',
  systemSpeedBrake: 'home.dashboard.system.speed_brake',
  systemSpoilers: 'home.dashboard.system.spoilers',
  systemAutoBrake: 'home.dashboard.system.auto_brake',
  systemGear: 'home.dashboard.system.gear',
  systemNoseGear: 'home.dashboard.system.nose_gear',
  systemLeftGear: 'home.dashboard.system.left_gear',
  systemRightGear: 'home.dashboard.system.right_gear',
  systemFlaps: 'home.dashboard.system.flaps',
  systemApu: 'home.dashboard.system.apu',
  systemEngineSingle: 'home.dashboard.system.engine_single',
  systemEngineLeft: 'home.dashboard.system.engine_left',
  systemEngineRight: 'home.dashboard.system.engine_right',
  systemAutopilot: 'home.dashboard.system.autopilot',
  systemAutothrottle: 'home.dashboard.system.autothrottle',
  systemBeacon: 'home.dashboard.system.beacon',
  systemStrobe: 'home.dashboard.system.strobe',
  systemNavLights: 'home.dashboard.system.nav_lights',
  systemLogoLights: 'home.dashboard.system.logo_lights',
  systemWingLights: 'home.dashboard.system.wing_lights',
  systemLandingLights: 'home.dashboard.system.landing_lights',
  systemTaxiLights: 'home.dashboard.system.taxi_lights',
  systemRunwayTurnoff: 'home.dashboard.system.runway_turnoff',
  systemWheelWell: 'home.dashboard.system.wheel_well',
} as const;

const K = HomeLocalizationKeys;

export const homeTranslations: ModuleTranslations = {
  zh_CN: {
    [K.homeTitle]: '首页',
    [K.welcomeNotConnectedTitle]: '未连接模拟器！',
    [K.welcomeNotConnectedSubtitle]: '等待建立数据链路...',
    [K.welcomePausedTitle]: '模拟器已暂停',
    [K.welcomePausedSubtitle]: '检测到模拟器处于暂停状态 ({aircraft})',
    [K.welcomeReadyTitle]: '飞行准备就绪',
    [K.welcomeReadySubtitle]: '当前机型: {aircraft}',
    [K.welcomeReadySubtitleWaiting]: '等待识别机型...',
    [K.welcomeSupportSims]: '支持 MSFS 2020/2024 & X-Plane 11/12',
    [K.transponderPrefix]: 'XPDR',
    [K.transponderEmergency]: '紧急情况',
    [K.transponderHijack]: '劫机',
    [K.transponderRadioFailure]: '通信失效',
    [K.simTitle]: '模拟器连接',
    [K.simConnected]: '已连接到 {sim}',
    [K.simDisconnected]: '未连接',
    [K.simDisconnect]: '断开',
    [K.simConnect]: '连接',
    [K.simConnectXplane]: '连接 X-Plane 11/12',
    [K.simConnectMsfs]: '连接 MSFS 2020/2024',
    [K.simConnectingTitle]: '正在建立与 {sim} 的连接...',
    [K.simConnectingSubtitle]: '请确保模拟器已启动并处于飞行状态',
    [K.simConnectFailedTitle]: '连接失败',
    [K.simConnectFailedContent]: '原因不明，请检查模拟器设置或网络连接。',
    [K.simRecording]: '正在录制',
    [K.checklistTitle]: '当前检查阶段',
    [K.checklistEmpty]: '暂无检查阶段',
    [K.flightNumberTitle]: '航班号',
    [K.flightNumberEmpty]: '未设置航班号',
    [K.flightNumberSet]: '设置',
    [K.flightNumberEdit]: '修改',
    [K.flightNumberDialogTitle]: '航班号设置',
    [K.flightNumberDialogHint]: '请输入当前航班号',
    [K.flightNumberDialogFormat]: '格式：2位航司代码 + 1-4位数字（如 CCA1234）',
    [K.flightNumberDialogConfirm]: '确定',
    [K.flightNumberDialogCancel]: '取消',
    [K.flightNumberDialogEditTitle]: '修改航班号',
    [K.flightNumberDialogEditContent]: '当前已配置航班号 {number}，确定要修改吗？',
    [K.flightNumberDialogContinue]: '继续',
    [K.flightNumberDialogInputHint]: '例: CCA1234',
    [K.flightNumberDialogInvalid]: '请输入正确的航班号格式',
    [K.dashboardTitle]: '实时飞行数据',
    [K.dashboardNoConnectionTitle]: '连接模拟器以查看实时飞行数据',
    [K.dashboardNoConnectionSubtitle]: '点击上方"连接"按钮开始',
    [K.homeMaskConnectBackendTitle]: '连接中间件服务后端以建立通信连接',
    [K.homeMaskConnectBackendSubtitle]:
      '请先启动中间件服务并确认通讯地址、网络代理配置正确，然后重试连接。',
    [K.homeMaskRetryButton]: '重试连接后端',
    [K.homeMaskRetryingButton]: '正在检测后端...',
    [K.primaryAirspeed]: '指示空速',
    [K.primaryAltitude]: '高度',
    [K.primaryHeading]: '航向',
    [K.primaryVerticalSpeed]: '垂直速度',
    [K.primaryFuelStatus]: '燃油状态',
    [K.primaryFuelOk]: '充足',
    [K.primaryFuelLow]: '不足!',
    [K.primaryFuelUnknown]: '未知',
    [K.navTitle]: '导航与位置',
    [K.navGroundSpeed]: '地速',
    [K.navTrueAirspeed]: '真空速',
    [K.navLatitude]: '纬度',
    [K.navLongitude]: '经度',
    [K.navAircraft]: '机型',
    [K.navAircraftIcao]: '机型ICAO',
    [K.navArrival]: '目的机场',
    [K.navCom1]: '通信频率',
    [K.navSetDeparture]: '设置起飞机场',
    [K.navSetDestination]: '设置抵达机场',
    [K.navSetAlternate]: '设置备降机场',
    [K.navPickDepartureTitle]: '设置起飞机场',
    [K.navPickDestinationTitle]: '设置目的地机场',
    [K.navPickAlternateTitle]: '设置备降机场',
    [K.navRecentAirports]: '最近或常用机场',
    [K.navClearSelection]: '清除选择',
    [K.navCancel]: '取消',
    [K.environmentTitle]: '环境数据',
    [K.environmentOat]: 'OAT (外部)',
    [K.environmentTat]: 'TAT (总温)',
    [K.environmentWind]: '风速/风向',
    [K.environmentQnh]: '海压 (QNH)',
    [K.environmentVisibility]: '报告能见度',
    [K.engineTitle]: '发动机与燃油',
    [K.engineFob]: 'FOB (当前燃油)',
    [K.engineFf]: 'FF (燃油流量)',
    [K.engineEng1N1]: 'ENG1 N1',
    [K.engineEng2N1]: 'ENG2 N1',
    [K.engineEng1Egt]: 'ENG1 EGT',
    [K.engineEng2Egt]: 'ENG2 EGT',
    [K.metarTitle]: '气象报文 (METAR)',
    [K.metarUpdatedAt]: '更新于: {time}',
    [K.metarWind]: '风',
    [K.metarVisibility]: '能见度',
    [K.metarTemperature]: '温/露',
    [K.metarAltimeter]: '修正海压',
    [K.metarErrorTitle]: '气象报文获取失败',
    [K.metarErrorSubtitle]: '发生错误',
    [K.metarErrorDefault]: '获取失败',
    [K.systemTitle]: '系统状态',
    [K.systemSectionWarning]: '警告系统',
    [K.systemSectionFlightControl]: '飞行与控制',
    [K.systemSectionGear]: '起落架',
    [K.systemSectionFlaps]: '襟翼状态',
    [K.systemSectionPower]: '动力与自动化',
    [K.systemSectionLights]: '外部灯光',
    [K.systemMasterWarning]: '主警告',
    [K.systemMasterCaution]: '主告警',
    [K.systemFireEngine1]: '左发火警',
    [K.systemFireEngine2]: '右发火警',
    [K.systemFireApu]: 'APU火警',
    [K.systemOnGround]: '地面',
    [K.systemParkingBrake]: '停机刹车',
    [K.systemSpeedBrake]: '减速板 {value}',
    [K.systemSpoilers]: '扰流板',
    [K.systemAutoBrake]: '自动刹车 {value}',
    [K.systemGear]: '起落架',
    [K.systemNoseGear]: '前轮',
    [K.systemLeftGear]: '左主轮',
    [K.systemRightGear]: '右主轮',
    [K.systemFlaps]: '襟翼 {value}',
    [K.systemApu]: 'APU',
    [K.systemEngineSingle]: '发动机',
    [K.systemEngineLeft]: '左发动机',
    [K.systemEngineRight]: '右发动机',
    [K.systemAutopilot]: '自动驾驶',
    [K.systemAutothrottle]: '自动油门',
    [K.systemBeacon]: '信标灯',
    [K.systemStrobe]: '频闪灯',
    [K.systemNavLights]: '导航灯',
    [K.systemLogoLights]: 'Logo灯',
    [K.systemWingLights]: '机翼灯',
    [K.systemLandingLights]: '着陆灯',
    [K.systemTaxiLights]: '滑行灯',
    [K.systemRunwayTurnoff]: '跑道脱离灯',
    [K.systemWheelWell]: '轮舱灯',
  },
  en_US: {
    [K.homeTitle]: 'Home',
    [K.welcomeNotConnectedTitle]: 'Simulator not connected!',
    [K.welcomeNotConnectedSubtitle]: 'Waiting for data link...',
    [K.welcomePausedTitle]: 'Simulator paused',
    [K.welcomePausedSubtitle]: 'Simulator is paused ({aircraft})',
    [K.welcomeReadyTitle]: 'Ready for flight',
    [K.welcomeReadySubtitle]: 'Current aircraft: {aircraft}',
    [K.welcomeReadySubtitleWaiting]: 'Waiting for aircraft detection...',
    [K.welcomeSupportSims]: 'Supports MSFS 2020/2024 & X-Plane 11/12',
    [K.transponderPrefix]: 'XPDR',
    [K.transponderEmergency]: 'Emergency',
    [K.transponderHijack]: 'Hijack',
    [K.transponderRadioFailure]: 'Radio Failure',
    [K.simTitle]: 'Simulator Connection',
    [K.simConnected]: 'Connected to {sim}',
    [K.simDisconnected]: 'Disconnected',
    [K.simDisconnect]: 'Disconnect',
    [K.simConnect]: 'Connect',
    [K.simConnectXplane]: 'Connect X-Plane 11/12',
    [K.simConnectMsfs]: 'Connect MSFS 2020/2024',
    [K.simConnectingTitle]: 'Connecting to {sim}...',
    [K.simConnectingSubtitle]: 'Make sure the simulator is running and in flight',
    [K.simConnectFailedTitle]: 'Connection failed',
    [K.simConnectFailedContent]: 'Unknown error. Check simulator settings or network.',
    [K.simRecording]: 'Recording',
    [K.checklistTitle]: 'Checklist Phase',
    [K.checklistEmpty]: 'No checklist phase',
    [K.flightNumberTitle]: 'Flight Number',
    [K.flightNumberEmpty]: 'Flight number not set',
    [K.flightNumberSet]: 'Set',
    [K.flightNumberEdit]: 'Edit',
    [K.flightNumberDialogTitle]: 'Flight Number',
    [K.flightNumberDialogHint]: 'Enter current flight number',
    [K.flightNumberDialogFormat]:
      'Format: 2-letter airline code + 1-4 digits (e.g., CCA1234)',
    [K.flightNumberDialogConfirm]: 'Confirm',
    [K.flightNumberDialogCancel]: 'Cancel',
    [K.flightNumberDialogEditTitle]: 'Edit Flight Number',
    [K.flightNumberDialogEditContent]: 'Flight number {number} is already set. Continue?',
    [K.flightNumberDialogContinue]: 'Continue',
    [K.flightNumberDialogInputHint]: 'e.g., CCA1234',
    [K.flightNumberDialogInvalid]: 'Invalid flight number format',
    [K.dashboardTitle]: 'Live Flight Data',
    [K.dashboardNoConnectionTitle]: 'Connect simulator to view live flight data',
    [K.dashboardNoConnectionSubtitle]: 'Use the Connect button above to start',
    [K.homeMaskConnectBackendTitle]:
      'Connect to the middleware backend to establish communication',
    [K.homeMaskConnectBackendSubtitle]:
      'Start the middleware service first, then verify endpoint and proxy settings before retrying.',
    [K.homeMaskRetryButton]: 'Retry backend connection',
    [K.homeMaskRetryingButton]: 'Checking backend...',
    [K.primaryAirspeed]: 'Indicated Airspeed',
    [K.primaryAltitude]: 'Altitude',
    [K.primaryHeading]: 'Heading',
    [K.primaryVerticalSpeed]: 'Vertical Speed',
    [K.primaryFuelStatus]: 'Fuel Status',
    [K.primaryFuelOk]: 'Sufficient',
    [K.primaryFuelLow]: 'Low!',
    [K.primaryFuelUnknown]: 'Unknown',
    [K.navTitle]: 'Navigation & Position',
    [K.navGroundSpeed]: 'Ground Speed',
    [K.navTrueAirspeed]: 'True Airspeed',
    [K.navLatitude]: 'Latitude',
    [K.navLongitude]: 'Longitude',
    [K.navAircraft]: 'Aircraft',
    [K.navAircraftIcao]: 'Aircraft ICAO',
    [K.navArrival]: 'Arrival',
    [K.navCom1]: 'COM1',
    [K.navSetDeparture]: 'Set departure airport',
    [K.navSetDestination]: 'Set arrival airport',
    [K.navSetAlternate]: 'Set alternate airport',
    [K.navPickDepartureTitle]: 'Set departure airport',
    [K.navPickDestinationTitle]: 'Set destination airport',
    [K.navPickAlternateTitle]: 'Set alternate airport',
    [K.navRecentAirports]: 'Recent or frequent airports',
    [K.navClearSelection]: 'Clear selection',
    [K.navCancel]: 'Cancel',
    [K.environmentTitle]: 'Environment',
    [K.environmentOat]: 'OAT',
    [K.environmentTat]: 'TAT',
    [K.environmentWind]: 'Wind',
    [K.environmentQnh]: 'QNH',
    [K.environmentVisibility]: 'Visibility',
    [K.engineTitle]: 'Engine & Fuel',
    [K.engineFob]: 'FOB',
    [K.engineFf]: 'FF',
    [K.engineEng1N1]: 'ENG1 N1',
    [K.engineEng2N1]: 'ENG2 N1',
    [K.engineEng1Egt]: 'ENG1 EGT',
    [K.engineEng2Egt]: 'ENG2 EGT',
    [K.metarTitle]: 'METAR',
    [K.metarUpdatedAt]: 'Updated: {time}',
    [K.metarWind]: 'Wind',
    [K.metarVisibility]: 'Visibility',
    [K.metarTemperature]: 'Temp/Dew',
    [K.metarAltimeter]: 'Altimeter',
    [K.metarErrorTitle]: 'METAR fetch failed',
    [K.metarErrorSubtitle]: 'Error',
    [K.metarErrorDefault]: 'Failed to fetch',
    [K.systemTitle]: 'System Status',
    [K.systemSectionWarning]: 'Warnings',
    [K.systemSectionFlightControl]: 'Flight & Control',
    [K.systemSectionGear]: 'Landing Gear',
    [K.systemSectionFlaps]: 'Flaps',
    [K.systemSectionPower]: 'Power & Automation',
    [K.systemSectionLights]: 'External Lights',
    [K.systemMasterWarning]: 'Master Warning',
    [K.systemMasterCaution]: 'Master Caution',
    [K.systemFireEngine1]: 'Engine 1 Fire',
    [K.systemFireEngine2]: 'Engine 2 Fire',
    [K.systemFireApu]: 'APU Fire',
    [K.systemOnGround]: 'On Ground',
    [K.systemParkingBrake]: 'Parking Brake',
    [K.systemSpeedBrake]: 'Speed Brake {value}',
    [K.systemSpoilers]: 'Spoilers',
    [K.systemAutoBrake]: 'Auto Brake {value}',
    [K.systemGear]: 'Gear',
    [K.systemNoseGear]: 'Nose Gear',
    [K.systemLeftGear]: 'Left Gear',
    [K.systemRightGear]: 'Right Gear',
    [K.systemFlaps]: 'Flaps {value}',
    [K.systemApu]: 'APU',
    [K.systemEngineSingle]: 'Engine',
    [K.systemEngineLeft]: 'Left Engine',
    [K.systemEngineRight]: 'Right Engine',
    [K.systemAutopilot]: 'Autopilot',
    [K.systemAutothrottle]: 'Autothrottle',
    [K.systemBeacon]: 'Beacon',
    [K.systemStrobe]: 'Strobe',
    [K.systemNavLights]: 'Nav Lights',
    [K.systemLogoLights]: 'Logo Lights',
    [K.systemWingLights]: 'Wing Lights',
    [K.systemLandingLights]: 'Landing Lights',
    [K.systemTaxiLights]: 'Taxi Lights',
    [K.systemRunwayTurnoff]: 'Runway Turnoff',
    [K.systemWheelWell]: 'Wheel Well',
  },
};
