import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * Briefing 模块国际化
 *
 * 对应 Flutter 版 `modules/briefing/localization/*.dart`（49 个 key）。
 * 由脚本机械转换，key 与文案逐条对齐。
 */
export const BriefingLocalizationKeys = {
  navTitle: 'briefing.nav.title',
  pageTitle: 'briefing.page.title',
  pageSubtitle: 'briefing.page.subtitle',
  generateTitle: 'briefing.generate.title',
  generateSubtitle: 'briefing.generate.subtitle',
  historyTitle: 'briefing.history.title',
  historySubtitle: 'briefing.history.subtitle',
  inputTitle: 'briefing.input.title',
  outputTitle: 'briefing.output.title',
  fieldDeparture: 'briefing.field.departure',
  // SimBrief 导入
  simbriefTitle: 'briefing.simbrief.title',
  simbriefHint: 'briefing.simbrief.hint',
  simbriefIdentity: 'briefing.simbrief.identity',
  simbriefImport: 'briefing.simbrief.import',
  simbriefImporting: 'briefing.simbrief.importing',
  simbriefSuccess: 'briefing.simbrief.success',
  simbriefFailed: 'briefing.simbrief.failed',
  simbriefNeedIdentity: 'briefing.simbrief.need_identity',
  profileTitle: 'briefing.profile.title',
  profileSubtitle: 'briefing.profile.subtitle',
  profileWind: 'briefing.profile.wind',
  profileTailwind: 'briefing.profile.tailwind',
  profileTemperature: 'briefing.profile.temperature',
  profileLoading: 'briefing.profile.loading',
  profileNeedPlan: 'briefing.profile.need_plan',
  profileFailed: 'briefing.profile.failed',
  profileRefresh: 'briefing.profile.refresh',
  profileCruise: 'briefing.profile.cruise',
  fieldArrival: 'briefing.field.arrival',
  fieldAlternate: 'briefing.field.alternate',
  fieldDepartureRunway: 'briefing.field.departure_runway',
  fieldArrivalRunway: 'briefing.field.arrival_runway',
  fieldAlternateRunway: 'briefing.field.alternate_runway',
  fieldFlightNumber: 'briefing.field.flight_number',
  fieldRoute: 'briefing.field.route',
  fieldCruiseAltitude: 'briefing.field.cruise_altitude',
  generateAction: 'briefing.action.generate',
  historyEmpty: 'briefing.history.empty',
  outputEmpty: 'briefing.output.empty',
  refresh: 'briefing.action.refresh',
  importFile: 'briefing.action.import',
  exportFile: 'briefing.action.export',
  importSuccess: 'briefing.message.import_success',
  importFailed: 'briefing.message.import_failed',
  exportSuccess: 'briefing.message.export_success',
  exportFailed: 'briefing.message.export_failed',
  refreshSuccess: 'briefing.message.refresh_success',
  refreshEmpty: 'briefing.message.refresh_empty',
  refreshFailed: 'briefing.message.refresh_failed',
  fieldIcaoHint: 'briefing.field.icao_hint',
  fieldFlightNumberHint: 'briefing.field.flight_number_hint',
  fieldRouteHint: 'briefing.field.route_hint',
  fieldCruiseAltitudeHint: 'briefing.field.cruise_altitude_hint',
  fieldRunwayHint: 'briefing.field.runway_hint',
  runwayAutoOption: 'briefing.field.runway_auto_option',
  requiredField: 'briefing.validation.required_field',
  requiredAllFields: 'briefing.validation.required_all_fields',
  invalidIcao: 'briefing.validation.invalid_icao',
  invalidFlightNumber: 'briefing.validation.invalid_flight_number',
  invalidCruiseAltitude: 'briefing.validation.invalid_cruise_altitude',
  airportValidateFailed: 'briefing.validation.airport_validate_failed',
  airportNotFound: 'briefing.validation.airport_not_found',
  airportResolving: 'briefing.validation.airport_resolving',
  airportLookupFailed: 'briefing.validation.airport_lookup_failed',
  runwayNeedAirport: 'briefing.field.runway_need_airport',
  runwayNoData: 'briefing.field.runway_no_data',
  deleteAction: 'briefing.action.delete',
  deleteConfirmTitle: 'briefing.delete.confirm_title',
  deleteConfirmContent: 'briefing.delete.confirm_content',
  deleteSuccess: 'briefing.delete.success',
  deleteFailed: 'briefing.delete.failed',
  copySuccess: 'briefing.message.copy_success',
} as const;

const K = BriefingLocalizationKeys;

export const briefingTranslations: ModuleTranslations = {
  zh_CN: {
    [K.navTitle]: '简报',
    [K.pageTitle]: '飞行简报',
    [K.pageSubtitle]: '输入航班信息，生成飞行简报',
    [K.generateTitle]: '生成简报',
    [K.generateSubtitle]: '输入航班信息，生成专业飞行简报',
    [K.historyTitle]: '历史简报',
    [K.historySubtitle]: '查看和管理历史简报记录',
    [K.inputTitle]: '航班输入',
    [K.outputTitle]: '简报输出',
    [K.fieldDeparture]: '起飞机场',
    [K.simbriefTitle]: '从 SimBrief 导入',
    [K.simbriefHint]: '填 SimBrief 用户名或 Pilot ID（纯数字），导入你最新的飞行计划。读取无需 API key。',
    [K.simbriefIdentity]: 'SimBrief 用户名 / Pilot ID',
    [K.simbriefImport]: '导入',
    [K.simbriefImporting]: '导入中…',
    [K.simbriefSuccess]: '已导入 {} → {}',
    [K.simbriefFailed]: '导入失败，请检查用户名或 Pilot ID',
    [K.simbriefNeedIdentity]: '请先填写 SimBrief 用户名或 Pilot ID',
    [K.profileTitle]: '航路气象剖面',
    [K.profileSubtitle]: '沿航线的高空风与温度，取自巡航高度',
    [K.profileWind]: '风速',
    [K.profileTailwind]: '顺风分量',
    [K.profileTemperature]: '温度',
    [K.profileLoading]: '正在取高空气象…',
    [K.profileNeedPlan]: '先导入 SimBrief 飞行计划',
    [K.profileFailed]: '高空气象取不到，稍后再试',
    [K.profileRefresh]: '重新获取',
    [K.profileCruise]: '巡航',
    [K.fieldArrival]: '到达机场',
    [K.fieldAlternate]: '备降机场',
    [K.fieldDepartureRunway]: '起飞跑道',
    [K.fieldArrivalRunway]: '降落跑道',
    [K.fieldAlternateRunway]: '备降跑道',
    [K.fieldFlightNumber]: '航班号',
    [K.fieldRoute]: '航路',
    [K.fieldCruiseAltitude]: '巡航高度(ft)',
    [K.generateAction]: '生成简报',
    [K.historyEmpty]: '暂无历史简报',
    [K.outputEmpty]: '暂无简报内容',
    [K.refresh]: '刷新',
    [K.importFile]: '导入',
    [K.exportFile]: '导出',
    [K.importSuccess]: '简报已导入',
    [K.importFailed]: '简报导入失败',
    [K.exportSuccess]: '简报已导出',
    [K.exportFailed]: '简报导出失败',
    [K.refreshSuccess]: '已加载 {} 条简报',
    [K.refreshEmpty]: '未找到可用的简报',
    [K.refreshFailed]: '简报刷新失败',
    [K.fieldIcaoHint]: '请输入4位ICAO，例如 ZBAA',
    [K.fieldFlightNumberHint]: '例如 CA1234',
    [K.fieldRouteHint]: '例如 B346 G212 W120',
    [K.fieldCruiseAltitudeHint]: '请输入巡航高度，例如 35000',
    [K.fieldRunwayHint]: '根据机场自动加载，可手动选择',
    [K.runwayAutoOption]: '自动推荐',
    [K.requiredField]: '{} 不能为空',
    [K.requiredAllFields]: '请填写完整表单后再生成简报',
    [K.invalidIcao]: '{} ICAO 无效，请输入4位字母或数字',
    [K.invalidFlightNumber]: '航班号无效，请输入2-3位航司代码加1-4位数字（可选1位字母后缀）',
    [K.invalidCruiseAltitude]: '巡航高度必须为大于0的数字',
    [K.airportValidateFailed]: '{} 机场信息校验失败，请检查ICAO',
    [K.airportNotFound]: '机场库中查无此码',
    [K.airportResolving]: '正在查询机场…',
    [K.airportLookupFailed]: '机场库不可用，无法校验',
    [K.runwayNeedAirport]: '先填写机场 ICAO',
    [K.runwayNoData]: '该机场无跑道数据',
    [K.deleteAction]: '删除',
    [K.deleteConfirmTitle]: '删除简报',
    [K.deleteConfirmContent]: '确认删除该历史简报吗？',
    [K.deleteSuccess]: '简报已删除',
    [K.deleteFailed]: '删除失败，请稍后重试',
    [K.copySuccess]: '简报已复制到剪贴板',
  },
  en_US: {
    [K.navTitle]: 'Briefing',
    [K.pageTitle]: 'Flight Briefing',
    [K.pageSubtitle]: 'Provide flight info to generate briefing',
    [K.generateTitle]: 'Generate Briefing',
    [K.generateSubtitle]: 'Enter flight info to generate briefing',
    [K.historyTitle]: 'Briefing History',
    [K.historySubtitle]: 'Review and manage history briefings',
    [K.inputTitle]: 'Flight Input',
    [K.outputTitle]: 'Briefing Output',
    [K.fieldDeparture]: 'Departure',
    [K.simbriefTitle]: 'Import from SimBrief',
    [K.simbriefHint]: 'Enter your SimBrief username or numeric Pilot ID to import your latest flight plan. No API key needed to fetch.',
    [K.simbriefIdentity]: 'SimBrief Username / Pilot ID',
    [K.simbriefImport]: 'Import',
    [K.simbriefImporting]: 'Importing…',
    [K.simbriefSuccess]: 'Imported {} → {}',
    [K.simbriefFailed]: 'Import failed — check the username or Pilot ID',
    [K.simbriefNeedIdentity]: 'Enter a SimBrief username or Pilot ID first',
    [K.profileTitle]: 'Route weather profile',
    [K.profileSubtitle]: 'Upper winds and temperature along the route, at cruise level',
    [K.profileWind]: 'Wind',
    [K.profileTailwind]: 'Tailwind',
    [K.profileTemperature]: 'Temp',
    [K.profileLoading]: 'Fetching upper-air data...',
    [K.profileNeedPlan]: 'Import a SimBrief flight plan first',
    [K.profileFailed]: 'Upper-air data unavailable, try again later',
    [K.profileRefresh]: 'Reload',
    [K.profileCruise]: 'Cruise',
    [K.fieldArrival]: 'Arrival',
    [K.fieldAlternate]: 'Alternate',
    [K.fieldDepartureRunway]: 'Departure Runway',
    [K.fieldArrivalRunway]: 'Arrival Runway',
    [K.fieldAlternateRunway]: 'Alternate Runway',
    [K.fieldFlightNumber]: 'Flight Number',
    [K.fieldRoute]: 'Route',
    [K.fieldCruiseAltitude]: 'Cruise Altitude(ft)',
    [K.generateAction]: 'Generate',
    [K.historyEmpty]: 'No briefing history',
    [K.outputEmpty]: 'No briefing output',
    [K.refresh]: 'Refresh',
    [K.importFile]: 'Import',
    [K.exportFile]: 'Export',
    [K.importSuccess]: 'Briefings imported',
    [K.importFailed]: 'Import failed',
    [K.exportSuccess]: 'Briefings exported',
    [K.exportFailed]: 'Export failed',
    [K.refreshSuccess]: 'Loaded {} briefings',
    [K.refreshEmpty]: 'No briefings found',
    [K.refreshFailed]: 'Refresh failed',
    [K.fieldIcaoHint]: 'Enter 4-char ICAO, e.g. ZBAA',
    [K.fieldFlightNumberHint]: 'e.g. CA1234',
    [K.fieldRouteHint]: 'e.g. B346 G212 W120',
    [K.fieldCruiseAltitudeHint]: 'Enter cruise altitude, e.g. 35000',
    [K.fieldRunwayHint]: 'Auto-loaded from airport, selectable manually',
    [K.runwayAutoOption]: 'Auto select',
    [K.requiredField]: '{} is required',
    [K.requiredAllFields]: 'Please complete the form before generating briefing',
    [K.invalidIcao]: '{} ICAO is invalid, use 4 letters or digits',
    [K.invalidFlightNumber]: 'Invalid flight number, use 2-3 letters + 1-4 digits (optional suffix)',
    [K.invalidCruiseAltitude]: 'Cruise altitude must be a positive number',
    [K.airportValidateFailed]: '{} airport validation failed, please check ICAO',
    [K.airportNotFound]: 'Not found in airport database',
    [K.airportResolving]: 'Looking up airport…',
    [K.airportLookupFailed]: 'Airport database unavailable',
    [K.runwayNeedAirport]: 'Enter an airport ICAO first',
    [K.runwayNoData]: 'No runway data for this airport',
    [K.deleteAction]: 'Delete',
    [K.deleteConfirmTitle]: 'Delete Briefing',
    [K.deleteConfirmContent]: 'Are you sure you want to delete this briefing record?',
    [K.deleteSuccess]: 'Briefing deleted',
    [K.deleteFailed]: 'Delete failed, please retry',
    [K.copySuccess]: 'Briefing copied to clipboard',
  },
};
