/**
 * 核心层国际化 Key 常量表
 *
 * 对应 Flutter 版 `lib/core/localization/localization_keys.dart`（167 项，逐项对齐）。
 * 各业务模块在自己的 `localization/*-localization-keys.ts` 中定义模块 key。
 */
export const LocalizationKeys = {
  settings: 'settings',
  confirmExitTitle: 'confirm_exit_title',
  confirmExitContent: 'confirm_exit_content',
  confirm: 'confirm',
  cancel: 'cancel',
  language: 'language',
  selectLanguage: 'select_language',
  setupLanguageTitle: 'setup_language_title',
  setupLanguageDesc: 'setup_language_desc',
  nextStep: 'next_step',
  previousStep: 'previous_step',
  loading: 'loading',
  savingAndExiting: 'saving_and_exiting',
  save: 'save',
  generalSettings: 'general_settings',
  settingsAutomaticLandingReports: 'settings_automatic_landing_reports',
  settingsAutomaticLandingReportsDesc: 'settings_automatic_landing_reports_desc',
  storageLocation: 'storage_location',
  storageLocationDesc: 'storage_location_desc',
  storageLocationChangeConfirm: 'storage_location_change_confirm',
  storageLocationChangeSuccess: 'storage_location_change_success',
  logSettings: 'log_settings',
  logSettingsDesc: 'log_settings_desc',
  logMaxSize: 'log_max_size',
  dangerZone: 'danger_zone',
  resetApp: 'reset_app',
  resetAppDesc: 'reset_app_desc',
  resetAppConfirmTitle: 'reset_app_confirm_title',
  resetAppConfirmContent: 'reset_app_confirm_content',
  resetSuccess: 'reset_success',
  success: 'success',
  doubleBackExit: 'double_back_exit',

  // Wizard Steps
  languageStep: 'language_step',
  storagePathStep: 'storage_path_step',
  logSettingsStep: 'log_settings_step',
  summaryStep: 'summary_step',

  storagePathTitle: 'storage_path_title',
  storagePathHint: 'storage_path_hint',

  enableLogging: 'enable_logging',
  enableLoggingDesc: 'enable_logging_desc',
  logSettingsHint: 'log_settings_hint',

  summaryTitle: 'summary_title',
  configSummary: 'config_summary',
  configCompleted: 'config_completed',
  finishSetupHint: 'finish_setup_hint',
  originalSelection: 'original_selection',
  finalStorage: 'final_storage',
  directoryName: 'directory_name',
  pathType: 'path_type',
  logging: 'logging',
  enabled: 'enabled',
  disabled: 'disabled',
  docsDir: 'docs_dir',
  appDataDir: 'app_data_dir',
  desktop: 'desktop',
  downloadsDir: 'downloads_dir',
  customPath: 'custom_path',

  // Setup Wizard specific
  exitConfirmContentWelcome: 'exit_confirm_content_welcome',
  exitConfirmContentConfig: 'exit_confirm_content_config',
  allReady: 'all_ready',
  welcomeTitle: 'welcome_title',
  welcomeDesc: 'welcome_desc',
  startConfig: 'start_config',
  letsStart: 'lets_start',
  setupGuide: 'setup_guide',
  remainingItems: 'remaining_items',
  finishInitialization: 'finish_initialization',

  // Settings Pages General
  themeSettings: 'theme_settings',
  themeSettingsDesc: 'theme_settings_desc',
  aboutApp: 'about_app',
  aboutAppDesc: 'about_app_desc',
  resetToDefault: 'reset_to_default',
  resetToDefaultSuccess: 'reset_to_default_success',

  // Theme Settings Page
  currentTheme: 'current_theme',
  switchThemeMode: 'switch_theme_mode',
  switchToLightMode: 'switch_to_light_mode',
  switchToDarkMode: 'switch_to_dark_mode',
  themeColors: 'theme_colors',
  themeColorsDesc: 'theme_colors_desc',
  themeChangedTo: 'theme_changed_to',
  customTheme: 'custom_theme',
  customThemeDesc: 'custom_theme_desc',
  currentCustomTheme: 'current_custom_theme',
  createCustomTheme: 'create_custom_theme',
  customThemeColor: 'custom_theme_color',
  themeName: 'theme_name',
  selectThemeColor: 'select_theme_color',
  selectColorShade: 'select_color_shade',
  customThemeApplied: 'custom_theme_applied',
  contrastAdjustment: 'contrast_adjustment',
  darkModeEnhanced: 'dark_mode_enhanced',
  lightModePurified: 'light_mode_purified',
  darkContrastDesc: 'dark_contrast_desc',
  lightContrastDesc: 'light_contrast_desc',
  defaultLabel: 'default_label',
  extremeDark: 'extreme_dark',
  pureLight: 'pure_light',
  designConstants: 'design_constants',

  // About Page
  appInfo: 'app_info',
  appNameLabel: 'app_name_label',
  packageNameLabel: 'package_name_label',
  versionLabel: 'version_label',
  developerInfo: 'developer_info',
  developerLabel: 'developer_label',
  emailLabel: 'email_label',
  openSourceLicense: 'open_source_license',
  licenseLabel: 'license_label',
  projectSourceCode: 'project_source_code',

  // Theme Names
  themeDefaultPurple: 'theme_default_purple',
  themeChristmasRed: 'theme_christmas_red',
  themeOceanBlue: 'theme_ocean_blue',
  themeNaturalGreen: 'theme_natural_green',
  themeWarmOrange: 'theme_warm_orange',
  themeElegantPurple: 'theme_elegant_purple',

  // Theme Modes
  themeModeSystem: 'theme_mode_system',
  themeModeLight: 'theme_mode_light',
  themeModeDark: 'theme_mode_dark',

  // Sidebar & Profile
  userGreeting: 'user_greeting',
  collapseSidebar: 'collapse_sidebar',
  expandSidebar: 'expand_sidebar',

  // Storage Path strings
  storagePathSelectionTitle: 'storage_path_selection_title',
  storagePathSelectionSubtitle: 'storage_path_selection_subtitle',
  storagePathSelectionDialogTitle: 'storage_path_selection_dialog_title',
  storagePathNotSelected: 'storage_path_not_selected',
  storagePathChangeButton: 'storage_path_change_button',

  // Common UI Tooltips
  themeSettingsTooltip: 'theme_settings_tooltip',
  back: 'back',
  close: 'close',
  appLogo: 'app_logo',
  windowMinimize: 'window_minimize',
  windowMaximize: 'window_maximize',
  windowRestore: 'window_restore',
  windowClose: 'window_close',
  badgeLabel: 'badge_label',

  // Bootstrap Config
  bootstrapConfig: 'bootstrap_config',
  bootstrapConfigDesc: 'bootstrap_config_desc',
  openDirectory: 'open_directory',
  openLogFolder: 'open_log_folder',
  clearCache: 'clear_cache',
  clearCacheDesc: 'clear_cache_desc',
  clearCacheConfirmTitle: 'clear_cache_confirm_title',
  clearCacheConfirmContent: 'clear_cache_confirm_content',
  clearCacheSuccess: 'clear_cache_success',
  cacheSize: 'cache_size',

  // Update Check
  updateCheck: 'update_check',
  updateCheckDesc: 'update_check_desc',
  checkForUpdates: 'check_for_updates',
  checkingForUpdates: 'checking_for_updates',
  updateAvailable: 'update_available',
  noUpdateAvailable: 'no_update_available',
  updateCheckFailed: 'update_check_failed',
  updateCheckTimeout: 'update_check_timeout',
  currentVersionLabel: 'current_version_label',
  latestVersionLabel: 'latest_version_label',
  updateContent: 'update_content',
  downloadUpdate: 'download_update',
  viewReleasePage: 'view_release_page',
  alreadyLatestVersion: 'already_latest_version',
  community: 'community',
  discordCommunityDesc: 'discord_community_desc',
  joinDiscord: 'join_discord',
  contributors: 'contributors',
  contributorsDesc: 'contributors_desc',
  contributorsLoading: 'contributors_loading',
  contributorsEmpty: 'contributors_empty',
  contributorsRetry: 'contributors_retry',
  contributorsUnknown: 'contributors_unknown',
  dataPathMissingTitle: 'data_path_missing_title',
  dataPathMissingContent: 'data_path_missing_content',

  // ── Web 版新增（桌面能力降级后的替代文案）──
  webStorageLocation: 'web_storage_location',
  webStorageLocationDesc: 'web_storage_location_desc',
  webNotificationPermission: 'web_notification_permission',
  webNotificationPermissionDesc: 'web_notification_permission_desc',
  webNotificationGranted: 'web_notification_granted',
  webNotificationDenied: 'web_notification_denied',
  webNotificationRequest: 'web_notification_request',
  exportFile: 'export_file',
  importFile: 'import_file',
  webProxyBanner: 'web_proxy_banner',
  webSettingsBackendBacked: 'web_settings_backend_backed',
  webSettingsLocalOnly: 'web_settings_local_only',
  webSettingsLabel: 'web_settings_label',
  webRecordStorageLabel: 'web_record_storage_label',
} as const;

/** 所有核心 key 的联合类型 */
