import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * AirportSearch 模块国际化
 *
 * 对应 Flutter 版 `modules/airport_search/localization/*.dart`（46 个 key）。
 * 由脚本机械转换，key 与文案逐条对齐。
 */
export const AirportSearchLocalizationKeys = {
  navTitle: 'airport_search.nav_title',
  pageTitle: 'airport_search.page_title',
  pageSubtitle: 'airport_search.page_subtitle',
  icaoLabel: 'airport_search.icao_label',
  icaoHint: 'airport_search.icao_hint',
  searchButton: 'airport_search.search_button',
  formatHint: 'airport_search.format_hint',
  fuzzyHint: 'airport_search.fuzzy_hint',
  suggestionsTitle: 'airport_search.suggestions_title',
  suggestionsEmpty: 'airport_search.suggestions_empty',
  noResultHint: 'airport_search.no_result_hint',
  latestResultTitle: 'airport_search.latest_result_title',
  airportNameLabel: 'airport_search.airport_name_label',
  airportIcaoLabel: 'airport_search.airport_icao_label',
  airportLatLonLabel: 'airport_search.airport_latlon_label',
  runwaysTitle: 'airport_search.runways_title',
  runwaysEmpty: 'airport_search.runways_empty',
  runwayNameLabel: 'airport_search.runway_name_label',
  runwayLengthLabel: 'airport_search.runway_length_label',
  runwayTypeLabel: 'airport_search.runway_type_label',
  frequenciesTitle: 'airport_search.frequencies_title',
  frequenciesEmpty: 'airport_search.frequencies_empty',
  frequencyTypeLabel: 'airport_search.frequency_type_label',
  frequencyValueLabel: 'airport_search.frequency_value_label',
  metarRawLabel: 'airport_search.metar_raw_label',
  metarDecodedLabel: 'airport_search.metar_decoded_label',
  metarWind: 'airport_search.metar_wind',
  metarVisibility: 'airport_search.metar_visibility',
  metarTemperature: 'airport_search.metar_temperature',
  metarAltimeter: 'airport_search.metar_altimeter',
  metarEmpty: 'airport_search.metar_empty',
  positionSectionTitle: 'airport_search.position_section',
  weatherSectionTitle: 'airport_search.weather_section',
  runwaySectionTitle: 'airport_search.runway_section',
  favoriteAdd: 'airport_search.favorite_add',
  favoriteRemove: 'airport_search.favorite_remove',
  favoriteRefresh: 'airport_search.favorite_refresh',
  favoritesTitle: 'airport_search.favorites_title',
  favoritesEmpty: 'airport_search.favorites_empty',
  favoriteOpen: 'airport_search.favorite_open',
  updatedAtLabel: 'airport_search.updated_at_label',
  invalidIcao: 'airport_search.error_invalid_icao',
  queryFailed: 'airport_search.error_query_failed',
  favoriteSaveFailed: 'airport_search.error_favorite_save',
  favoriteLoadFailed: 'airport_search.error_favorite_load',
  favoriteUpdateFailed: 'airport_search.error_favorite_update',
} as const;

const K = AirportSearchLocalizationKeys;

export const airportSearchTranslations: ModuleTranslations = {
  zh_CN: {
    [K.navTitle]: '机场查询',
    [K.pageTitle]: '机场搜索',
    [K.pageSubtitle]: '输入四位 ICAO 代码查询机场与实时气象',
    [K.icaoLabel]: 'ICAO 代码',
    [K.icaoHint]: '例如 ZBAA / KJFK / UUDD',
    [K.searchButton]: '查询',
    [K.formatHint]: '仅支持四位字母或数字组合',
    [K.fuzzyHint]: '支持输入 1-4 位 ICAO 进行模糊搜索',
    [K.suggestionsTitle]: '匹配建议',
    [K.suggestionsEmpty]: '暂无匹配机场',
    [K.noResultHint]: '暂无查询结果',
    [K.latestResultTitle]: '查询结果',
    [K.airportNameLabel]: '机场名称',
    [K.airportIcaoLabel]: 'ICAO',
    [K.airportLatLonLabel]: '经纬度',
    [K.runwaysTitle]: '跑道信息',
    [K.runwaysEmpty]: '暂无跑道数据',
    [K.runwayNameLabel]: '跑道名称',
    [K.runwayLengthLabel]: '长度',
    [K.runwayTypeLabel]: '类型',
    [K.frequenciesTitle]: '通讯频率',
    [K.frequenciesEmpty]: '暂无通讯频率',
    [K.frequencyTypeLabel]: '频率类型',
    [K.frequencyValueLabel]: '频率值',
    [K.metarRawLabel]: '原始报文',
    [K.metarDecodedLabel]: '译文',
    [K.metarWind]: '风',
    [K.metarVisibility]: '能见度',
    [K.metarTemperature]: '温/露',
    [K.metarAltimeter]: '修正海压',
    [K.metarEmpty]: '暂无METAR数据',
    [K.positionSectionTitle]: '位置与坐标',
    [K.weatherSectionTitle]: '最新象情',
    [K.runwaySectionTitle]: '跑道详情',
    [K.favoriteAdd]: '收藏机场',
    [K.favoriteRemove]: '取消收藏',
    [K.favoriteRefresh]: '更新缓存',
    [K.favoritesTitle]: '已收藏机场',
    [K.favoritesEmpty]: '尚未收藏机场',
    [K.favoriteOpen]: '打开',
    [K.updatedAtLabel]: '更新时间',
    [K.invalidIcao]: 'ICAO 格式错误，请输入四位字母或数字',
    [K.queryFailed]: '机场或METAR查询失败',
    [K.favoriteSaveFailed]: '收藏保存失败',
    [K.favoriteLoadFailed]: '本地收藏读取失败',
    [K.favoriteUpdateFailed]: '收藏缓存更新失败',
  },
  en_US: {
    [K.navTitle]: 'Airport Search',
    [K.pageTitle]: 'Airport Query',
    [K.pageSubtitle]: 'Search airport info and METAR by 4-character ICAO',
    [K.icaoLabel]: 'ICAO Code',
    [K.icaoHint]: 'e.g. ZBAA / KJFK / UUDD',
    [K.searchButton]: 'Search',
    [K.formatHint]: 'Only 4 letters or digits are allowed',
    [K.fuzzyHint]: 'Supports fuzzy search with 1-4 ICAO characters',
    [K.suggestionsTitle]: 'Suggestions',
    [K.suggestionsEmpty]: 'No matching airport',
    [K.noResultHint]: 'No query result yet',
    [K.latestResultTitle]: 'Query Result',
    [K.airportNameLabel]: 'Airport Name',
    [K.airportIcaoLabel]: 'ICAO',
    [K.airportLatLonLabel]: 'Lat/Lon',
    [K.runwaysTitle]: 'Runways',
    [K.runwaysEmpty]: 'No runway data',
    [K.runwayNameLabel]: 'Runway',
    [K.runwayLengthLabel]: 'Length',
    [K.runwayTypeLabel]: 'Type',
    [K.frequenciesTitle]: 'Frequencies',
    [K.frequenciesEmpty]: 'No frequency data',
    [K.frequencyTypeLabel]: 'Type',
    [K.frequencyValueLabel]: 'Frequency',
    [K.metarRawLabel]: 'Raw',
    [K.metarDecodedLabel]: 'Decoded',
    [K.metarWind]: 'Wind',
    [K.metarVisibility]: 'Visibility',
    [K.metarTemperature]: 'Temp/Dew',
    [K.metarAltimeter]: 'Altimeter',
    [K.metarEmpty]: 'No METAR data',
    [K.positionSectionTitle]: 'Position',
    [K.weatherSectionTitle]: 'Latest Weather',
    [K.runwaySectionTitle]: 'Runway Details',
    [K.favoriteAdd]: 'Favorite',
    [K.favoriteRemove]: 'Unfavorite',
    [K.favoriteRefresh]: 'Refresh Cache',
    [K.favoritesTitle]: 'Favorited Airports',
    [K.favoritesEmpty]: 'No favorites yet',
    [K.favoriteOpen]: 'Open',
    [K.updatedAtLabel]: 'Updated',
    [K.invalidIcao]: 'Invalid ICAO format, please use 4 letters or digits',
    [K.queryFailed]: 'Airport or METAR query failed',
    [K.favoriteSaveFailed]: 'Failed to save favorite',
    [K.favoriteLoadFailed]: 'Failed to load local favorites',
    [K.favoriteUpdateFailed]: 'Failed to refresh favorite cache',
  },
};
