import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * Http 模块国际化
 *
 * 对应 Flutter 版 `modules/http/localization/*.dart`（53 个 key）。
 * 由脚本机械转换，key 与文案逐条对齐。
 */
export const HttpLocalizationKeys = {
  settingsTitle: 'http.settings.title',
  settingsDescription: 'http.settings.description',
  backendSectionTitle: 'http.settings.backend_section_title',
  backendSectionDescription: 'http.settings.backend_section_description',
  wsSectionTitle: 'http.settings.ws_section_title',
  wsSectionDescription: 'http.settings.ws_section_description',
  hostLabel: 'http.settings.host_label',
  hostHint: 'http.settings.host_hint',
  portLabel: 'http.settings.port_label',
  portHint: 'http.settings.port_hint',
  wsHostLabel: 'http.settings.ws_host_label',
  wsHostHint: 'http.settings.ws_host_hint',
  wsPortLabel: 'http.settings.ws_port_label',
  wsPortHint: 'http.settings.ws_port_hint',
  flightDataSectionTitle: 'http.settings.flight_data_section_title',
  flightDataSectionDescription: 'http.settings.flight_data_section_description',
  flightDataIntervalLabel: 'http.settings.flight_data_interval_label',
  flightDataIntervalHint: 'http.settings.flight_data_interval_hint',
  currentFlightDataInterval: 'http.settings.current_flight_data_interval',
  invalidFlightDataInterval: 'http.settings.invalid_flight_data_interval',
  flightLogIntervalLabel: 'http.settings.flight_log_interval_label',
  flightLogIntervalHint: 'http.settings.flight_log_interval_hint',
  currentFlightLogInterval: 'http.settings.current_flight_log_interval',
  invalidFlightLogInterval: 'http.settings.invalid_flight_log_interval',
  uiRefreshIntervalLabel: 'http.settings.ui_refresh_interval_label',
  uiRefreshIntervalHint: 'http.settings.ui_refresh_interval_hint',
  currentUiRefreshInterval: 'http.settings.current_ui_refresh_interval',
  invalidUiRefreshInterval: 'http.settings.invalid_ui_refresh_interval',
  lowPerformanceModeLabel: 'http.settings.low_performance_mode_label',
  lowPerformanceModeHint: 'http.settings.low_performance_mode_hint',
  flightDataIntervalSaved: 'http.settings.flight_data_interval_saved',
  diagnoseSectionTitle: 'http.settings.diagnose_section_title',
  diagnoseSectionDescription: 'http.settings.diagnose_section_description',
  runDiagnosis: 'http.settings.run_diagnosis',
  diagnoseBackendOk: 'http.settings.diagnose_backend_ok',
  diagnoseBackendFail: 'http.settings.diagnose_backend_fail',
  diagnoseWsOk: 'http.settings.diagnose_ws_ok',
  diagnoseWsFail: 'http.settings.diagnose_ws_fail',
  diagnoseTokenOk: 'http.settings.diagnose_token_ok',
  diagnoseTokenFail: 'http.settings.diagnose_token_fail',
  diagnoseSimulatorOk: 'http.settings.diagnose_simulator_ok',
  diagnoseSimulatorFail: 'http.settings.diagnose_simulator_fail',
  diagnoseQualityOk: 'http.settings.diagnose_quality_ok',
  diagnoseQualityFail: 'http.settings.diagnose_quality_fail',
  qualitySectionTitle: 'http.settings.quality_section_title',
  qualityUpstream: 'http.settings.quality_upstream',
  qualityDownstream: 'http.settings.quality_downstream',
  qualitySampleRate: 'http.settings.quality_sample_rate',
  qualityRepeatRatio: 'http.settings.quality_repeat_ratio',
  qualityStallCount: 'http.settings.quality_stall_count',
  qualityMaxGap: 'http.settings.quality_max_gap',
  qualityLatency: 'http.settings.quality_latency',
  qualityPushCount: 'http.settings.quality_push_count',
  qualityFailureCount: 'http.settings.quality_failure_count',
  qualityBytesSent: 'http.settings.quality_bytes_sent',
  qualityStalled: 'http.settings.quality_stalled',
  qualityHealthy: 'http.settings.quality_healthy',
  qualityNoSample: 'http.settings.quality_no_sample',
  currentAddress: 'http.settings.current_address',
  currentWsAddress: 'http.settings.current_ws_address',
  navSourceSectionTitle: 'http.settings.nav_source_section_title',
  navSourceSectionDescription: 'http.settings.nav_source_section_description',
  navSourceLabel: 'http.settings.nav_source_label',
  navSourceAuto: 'http.settings.nav_source_auto',
  navSourceCurrent: 'http.settings.nav_source_current',
  navSourceSaved: 'http.settings.nav_source_saved',
  navSourceSaveFailed: 'http.settings.nav_source_save_failed',
  navSourceEmpty: 'http.settings.nav_source_empty',
  navSourceFallbackHint: 'http.settings.nav_source_fallback_hint',
  navSourceReloadHint: 'http.settings.nav_source_reload_hint',
  saveButton: 'http.settings.save_button',
  testButton: 'http.settings.test_button',
  saving: 'http.settings.saving',
  testing: 'http.settings.testing',
  saveSuccess: 'http.settings.save_success',
  testSuccess: 'http.settings.test_success',
  invalidHost: 'http.settings.invalid_host',
  invalidPort: 'http.settings.invalid_port',
  testFailed: 'http.settings.test_failed',
} as const;

const K = HttpLocalizationKeys;

export const httpTranslations: ModuleTranslations = {
  zh_CN: {
    [K.settingsTitle]: '中间件通信',
    [K.settingsDescription]: '配置后端通讯的 IP 与端口',
    [K.backendSectionTitle]: '后端连接地址',
    [K.backendSectionDescription]: '保存后将作为模块默认请求地址',
    [K.wsSectionTitle]: 'WebSocket 连接地址',
    [K.wsSectionDescription]: '保存后将作为实时数据推送连接地址',
    [K.hostLabel]: '后端 IP / 域名',
    [K.hostHint]: '例如 127.0.0.1 或 localhost',
    [K.portLabel]: '后端端口',
    [K.portHint]: '范围 1 - 65535',
    [K.wsHostLabel]: 'WebSocket IP / 域名',
    [K.wsHostHint]: '例如 127.0.0.1 或 localhost',
    [K.wsPortLabel]: 'WebSocket 端口',
    [K.wsPortHint]: '范围 1 - 65535',
    [K.flightDataSectionTitle]: '飞行数据频率',
    [K.flightDataSectionDescription]: '设置飞行时请求后端数据的频率',
    [K.flightDataIntervalLabel]: '请求间隔（毫秒）',
    [K.flightDataIntervalHint]: '范围 100 - 2000，默认 300',
    [K.flightLogIntervalLabel]: '日志采样间隔（毫秒）',
    [K.flightLogIntervalHint]: '范围 100 - 2000，默认 100',
    [K.currentFlightLogInterval]: '当前日志采样: {value} ms',
    [K.invalidFlightLogInterval]: '请输入有效日志采样频率（100-2000 毫秒）',
    [K.uiRefreshIntervalLabel]: 'UI 刷新间隔（毫秒）',
    [K.uiRefreshIntervalHint]: '范围 60 - 2000，建议 120',
    [K.currentUiRefreshInterval]: '当前 UI 刷新: {value} ms',
    [K.invalidUiRefreshInterval]: '请输入有效 UI 刷新间隔（60-2000 毫秒）',
    [K.lowPerformanceModeLabel]: '低性能模式',
    [K.lowPerformanceModeHint]: '开启后自动限制重绘频率，降低实时渲染压力',
    [K.currentFlightDataInterval]: '当前频率: {value} ms',
    [K.invalidFlightDataInterval]: '请输入有效频率（100-2000 毫秒）',
    [K.flightDataIntervalSaved]: '飞行数据频率已保存',
    [K.diagnoseSectionTitle]: '一键排障',
    [K.diagnoseSectionDescription]: '检测后端连通、WebSocket通道、会话连接与模拟器状态',
    [K.runDiagnosis]: '开始诊断',
    [K.diagnoseBackendOk]: '后端连通正常',
    [K.diagnoseBackendFail]: '后端连通异常',
    [K.diagnoseWsOk]: 'WebSocket 接口正常',
    [K.diagnoseWsFail]: 'WebSocket 接口异常',
    [K.diagnoseTokenOk]: '会话 Token 已建立',
    [K.diagnoseTokenFail]: '会话 Token 未建立',
    [K.diagnoseSimulatorOk]: '模拟器状态接口正常',
    [K.diagnoseSimulatorFail]: '模拟器状态接口异常',
    [K.diagnoseQualityOk]: '数据质量指标已获取',
    [K.diagnoseQualityFail]: '数据质量接口异常',
    [K.qualitySectionTitle]: '数据质量',
    [K.qualityUpstream]: '上游：模拟器 → 中间件',
    [K.qualityDownstream]: '下行：中间件 → 前端',
    [K.qualitySampleRate]: '到包率',
    [K.qualityRepeatRatio]: '重复帧率',
    [K.qualityStallCount]: '断流次数',
    [K.qualityMaxGap]: '最长空档',
    [K.qualityLatency]: '推送耗时（平均/峰值）',
    [K.qualityPushCount]: '已推送（全量/增量/跳过）',
    [K.qualityFailureCount]: '写失败',
    [K.qualityBytesSent]: '已发送',
    [K.qualityStalled]: '上游断流：模拟器没有在送新数据',
    [K.qualityHealthy]: '链路正常',
    [K.qualityNoSample]: '尚无采样，连接模拟器后开始统计',
    [K.currentAddress]: '当前地址: {address}',
    [K.currentWsAddress]: '当前 WebSocket: {address}',
    [K.navSourceSectionTitle]: '导航数据来源',
    [K.navSourceSectionDescription]: '切换中间件读取机场与航路数据的模拟器数据库',
    [K.navSourceLabel]: '数据源',
    [K.navSourceAuto]: '自动选择',
    [K.navSourceCurrent]: '当前生效: {value}',
    [K.navSourceSaved]: '导航数据源已切换',
    [K.navSourceSaveFailed]: '切换失败，该数据源当前不可用',
    [K.navSourceEmpty]: '没有可用的数据源，请先在中间件里配置模拟器路径',
    [K.navSourceFallbackHint]: '配置里的数据源当前不可用，已回退到自动选择的源',
    [K.navSourceReloadHint]: '切换后已缓存的机场数据会重新加载，首次查询可能稍慢',
    [K.saveButton]: '保存配置',
    [K.testButton]: '测试连接',
    [K.saving]: '保存中...',
    [K.testing]: '测试中...',
    [K.saveSuccess]: '后端地址已保存',
    [K.testSuccess]: '连接测试通过',
    [K.invalidHost]: '请输入有效的后端 IP 或域名',
    [K.invalidPort]: '请输入有效端口（1-65535）',
    [K.testFailed]: '连接测试失败',
  },
  en_US: {
    [K.settingsTitle]: 'Middleware Connection',
    [K.settingsDescription]: 'Configure backend communication IP and port',
    [K.backendSectionTitle]: 'Backend Address',
    [K.backendSectionDescription]: 'The saved value is used as the default request target',
    [K.wsSectionTitle]: 'WebSocket Address',
    [K.wsSectionDescription]: 'The saved value is used as the realtime stream target',
    [K.hostLabel]: 'Backend IP / Host',
    [K.hostHint]: 'For example 127.0.0.1 or localhost',
    [K.portLabel]: 'Backend Port',
    [K.portHint]: 'Range 1 - 65535',
    [K.wsHostLabel]: 'WebSocket Host',
    [K.wsHostHint]: 'For example 127.0.0.1 or localhost',
    [K.wsPortLabel]: 'WebSocket Port',
    [K.wsPortHint]: 'Range 1 - 65535',
    [K.flightDataSectionTitle]: 'Flight Data Frequency',
    [K.flightDataSectionDescription]: 'Configure how often flight data is requested from backend',
    [K.flightDataIntervalLabel]: 'Request Interval (ms)',
    [K.flightDataIntervalHint]: 'Range 100 - 2000, default 300',
    [K.flightLogIntervalLabel]: 'Log Sample Interval (ms)',
    [K.flightLogIntervalHint]: 'Range 100 - 2000, default 100',
    [K.currentFlightLogInterval]: 'Current log sample: {value} ms',
    [K.invalidFlightLogInterval]: 'Enter a valid log sampling interval (100-2000 ms)',
    [K.uiRefreshIntervalLabel]: 'UI Refresh Interval (ms)',
    [K.uiRefreshIntervalHint]: 'Range 60 - 2000, recommended 120',
    [K.currentUiRefreshInterval]: 'Current UI refresh: {value} ms',
    [K.invalidUiRefreshInterval]: 'Enter a valid UI refresh interval (60-2000 ms)',
    [K.lowPerformanceModeLabel]: 'Low Performance Mode',
    [K.lowPerformanceModeHint]: 'Throttle UI redraw cadence to reduce rendering pressure',
    [K.currentFlightDataInterval]: 'Current frequency: {value} ms',
    [K.invalidFlightDataInterval]: 'Enter a valid frequency (100-2000 ms)',
    [K.flightDataIntervalSaved]: 'Flight data frequency saved',
    [K.diagnoseSectionTitle]: 'One-click Diagnosis',
    [K.diagnoseSectionDescription]: 'Check backend reachability, WebSocket, session and simulator status',
    [K.runDiagnosis]: 'Run Diagnosis',
    [K.diagnoseBackendOk]: 'Backend reachable',
    [K.diagnoseBackendFail]: 'Backend unreachable',
    [K.diagnoseWsOk]: 'WebSocket endpoint reachable',
    [K.diagnoseWsFail]: 'WebSocket endpoint unavailable',
    [K.diagnoseTokenOk]: 'Session token established',
    [K.diagnoseTokenFail]: 'Session token missing',
    [K.diagnoseSimulatorOk]: 'Simulator state endpoint reachable',
    [K.diagnoseSimulatorFail]: 'Simulator state endpoint unavailable',
    [K.diagnoseQualityOk]: 'Data quality metrics retrieved',
    [K.diagnoseQualityFail]: 'Diagnostics endpoint unavailable',
    [K.qualitySectionTitle]: 'Data quality',
    [K.qualityUpstream]: 'Upstream: simulator → middleware',
    [K.qualityDownstream]: 'Downstream: middleware → frontend',
    [K.qualitySampleRate]: 'Packet rate',
    [K.qualityRepeatRatio]: 'Repeated frames',
    [K.qualityStallCount]: 'Stalls',
    [K.qualityMaxGap]: 'Longest gap',
    [K.qualityLatency]: 'Push latency (avg/peak)',
    [K.qualityPushCount]: 'Pushed (full/delta/skipped)',
    [K.qualityFailureCount]: 'Write failures',
    [K.qualityBytesSent]: 'Bytes sent',
    [K.qualityStalled]: 'Upstream stalled: the simulator is not sending new data',
    [K.qualityHealthy]: 'Link healthy',
    [K.qualityNoSample]: 'No samples yet — statistics start once a simulator is connected',
    [K.currentAddress]: 'Current address: {address}',
    [K.currentWsAddress]: 'Current WebSocket: {address}',
    [K.navSourceSectionTitle]: 'Navigation Data Source',
    [K.navSourceSectionDescription]:
      'Switch which simulator database the middleware reads airports and routes from',
    [K.navSourceLabel]: 'Data source',
    [K.navSourceAuto]: 'Automatic',
    [K.navSourceCurrent]: 'In effect: {value}',
    [K.navSourceSaved]: 'Navigation data source switched',
    [K.navSourceSaveFailed]: 'Switch failed — that source is currently unavailable',
    [K.navSourceEmpty]: 'No source available. Configure a simulator path in the middleware first.',
    [K.navSourceFallbackHint]:
      'The configured source is unavailable; fell back to an automatically selected one',
    [K.navSourceReloadHint]:
      'Cached airport data reloads after switching, so the first query may be slower',
    [K.saveButton]: 'Save',
    [K.testButton]: 'Test Connection',
    [K.saving]: 'Saving...',
    [K.testing]: 'Testing...',
    [K.saveSuccess]: 'Backend address saved',
    [K.testSuccess]: 'Connection test succeeded',
    [K.invalidHost]: 'Enter a valid backend IP or host',
    [K.invalidPort]: 'Enter a valid port (1-65535)',
    [K.testFailed]: 'Connection test failed',
  },
};
