import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * Monitor 模块国际化
 *
 * 对应 Flutter 版 `modules/monitor/localization/*.dart`（44 个 key）。
 * 由脚本机械转换，key 与文案逐条对齐。
 */
export const MonitorLocalizationKeys = {
  navTitle: 'monitor.nav.title',
  pageTitle: 'monitor.page.title',
  pageSubtitleConnected: 'monitor.page.subtitle.connected',
  pageSubtitleDisconnected: 'monitor.page.subtitle.disconnected',
  pausedLabel: 'monitor.page.paused',
  masterWarningMessage: 'monitor.page.master_warning_message',
  masterCautionMessage: 'monitor.page.master_caution_message',
  noConnectionTitle: 'monitor.empty.title',
  noConnectionSubtitle: 'monitor.empty.subtitle',
  noConnectionStepHome: 'monitor.empty.step_home',
  noConnectionStepConnect: 'monitor.empty.step_connect',
  noConnectionStepStart: 'monitor.empty.step_start',
  compassTitle: 'monitor.compass.title',
  systemsTitle: 'monitor.systems.title',
  parkingBrakeLabel: 'monitor.systems.parking_brake',
  parkingBrakeSet: 'monitor.systems.parking_brake_set',
  parkingBrakeReleased: 'monitor.systems.parking_brake_released',
  transponderLabel: 'monitor.systems.transponder',
  transponderEmpty: 'monitor.systems.transponder_empty',
  flapsLabel: 'monitor.systems.flaps',
  flapsUp: 'monitor.systems.flaps_up',
  speedBrakeLabel: 'monitor.systems.speed_brake',
  speedBrakeUnknown: 'monitor.systems.speed_brake_unknown',
  fireLabel: 'monitor.systems.fire',
  fireEngine1: 'monitor.systems.fire_engine1',
  fireEngine2: 'monitor.systems.fire_engine2',
  fireApu: 'monitor.systems.fire_apu',
  fireSuffix: 'monitor.systems.fire_suffix',
  landingGearTitle: 'monitor.gear.title',
  gearNoseLabel: 'monitor.gear.nose',
  gearLeftLabel: 'monitor.gear.left',
  gearRightLabel: 'monitor.gear.right',
  gearPositionUp: 'monitor.gear.position_up',
  gearPositionOff: 'monitor.gear.position_off',
  gearPositionDown: 'monitor.gear.position_down',
  gearHandleLabel: 'monitor.gear.handle_label',
  gearLimitTitle: 'monitor.gear.limit_title',
  gearLimitContent: 'monitor.gear.limit_content',
  chartGForceTitle: 'monitor.chart.g_force',
  chartAltitudeTitle: 'monitor.chart.altitude',
  chartBaroTitle: 'monitor.chart.baro',
  unitG: 'monitor.unit.g',
  unitFt: 'monitor.unit.ft',
  unitInHg: 'monitor.unit.inhg',
} as const;

const K = MonitorLocalizationKeys;

export const monitorTranslations: ModuleTranslations = {
  zh_CN: {
    [K.navTitle]: '监控',
    [K.pageTitle]: '实时飞行监控',
    [K.pageSubtitleConnected]: '正在接收来自模拟器的实时数据',
    [K.pageSubtitleDisconnected]: '模拟器未连接',
    [K.pausedLabel]: '已暂停',
    [K.masterWarningMessage]: '主警告 (MASTER WARNING) - 请检查警报面板',
    [K.masterCautionMessage]: '主告警 (MASTER CAUTION) - 系统异常',
    [K.noConnectionTitle]: '数据链路未就绪',
    [K.noConnectionSubtitle]: '实时飞行监控系统需要激活的模拟器连接。目前由于缺少数据流，仪表盘已进入待机模式。',
    [K.noConnectionStepHome]: '前往首页',
    [K.noConnectionStepConnect]: '连接模拟器',
    [K.noConnectionStepStart]: '开始使用',
    [K.compassTitle]: '磁航向 (Magnetic Heading)',
    [K.systemsTitle]: '飞行系统状态 (Systems Status)',
    [K.parkingBrakeLabel]: '停机刹车 (Parking Brake)',
    [K.parkingBrakeSet]: 'SET',
    [K.parkingBrakeReleased]: 'RELEASED',
    [K.transponderLabel]: '应答机 (Transponder)',
    [K.transponderEmpty]: 'N/A',
    [K.flapsLabel]: '襟翼位置 (Flaps)',
    [K.flapsUp]: 'UP',
    [K.speedBrakeLabel]: '减速板 (Speed Brake)',
    [K.speedBrakeUnknown]: '--',
    [K.fireLabel]: '火警警告 (FIRE)',
    [K.fireEngine1]: 'ENG1',
    [K.fireEngine2]: 'ENG2',
    [K.fireApu]: 'APU',
    [K.fireSuffix]: 'FIRE',
    [K.landingGearTitle]: '起落架状态 (Landing Gear)',
    [K.gearNoseLabel]: 'NOSE\nGEAR',
    [K.gearLeftLabel]: 'LEFT\nGEAR',
    [K.gearRightLabel]: 'RIGHT\nGEAR',
    [K.gearPositionUp]: 'UP',
    [K.gearPositionOff]: 'OFF',
    [K.gearPositionDown]: 'DN',
    [K.gearHandleLabel]: 'LANDING GEAR',
    [K.gearLimitTitle]: 'LANDING GEAR LIMIT (IAS)',
    [K.gearLimitContent]: 'OPERATING EXTEND 270K - 82M\nRETRACT 235K\nEXTENDED 320K - 82M',
    [K.chartGForceTitle]: '重力监控 (G-Force)',
    [K.chartAltitudeTitle]: '高度趋势 (Altitude)',
    [K.chartBaroTitle]: '大气压强 (Baro)',
    [K.unitG]: 'G',
    [K.unitFt]: 'FT',
    [K.unitInHg]: 'inHg',
  },
  en_US: {
    [K.navTitle]: 'Monitor',
    [K.pageTitle]: 'Flight Monitor',
    [K.pageSubtitleConnected]: 'Receiving live simulator data',
    [K.pageSubtitleDisconnected]: 'Simulator disconnected',
    [K.pausedLabel]: 'Paused',
    [K.masterWarningMessage]: 'MASTER WARNING - Check warning panel',
    [K.masterCautionMessage]: 'MASTER CAUTION - System alert',
    [K.noConnectionTitle]: 'Data link unavailable',
    [K.noConnectionSubtitle]: 'Live monitor requires an active simulator connection. The dashboard is standing by without data.',
    [K.noConnectionStepHome]: 'Go to Home',
    [K.noConnectionStepConnect]: 'Connect Simulator',
    [K.noConnectionStepStart]: 'Start',
    [K.compassTitle]: 'Magnetic Heading',
    [K.systemsTitle]: 'Systems Status',
    [K.parkingBrakeLabel]: 'Parking Brake',
    [K.parkingBrakeSet]: 'SET',
    [K.parkingBrakeReleased]: 'RELEASED',
    [K.transponderLabel]: 'Transponder',
    [K.transponderEmpty]: 'N/A',
    [K.flapsLabel]: 'Flaps',
    [K.flapsUp]: 'UP',
    [K.speedBrakeLabel]: 'Speed Brake',
    [K.speedBrakeUnknown]: '--',
    [K.fireLabel]: 'Fire Warning',
    [K.fireEngine1]: 'ENG1',
    [K.fireEngine2]: 'ENG2',
    [K.fireApu]: 'APU',
    [K.fireSuffix]: 'FIRE',
    [K.landingGearTitle]: 'Landing Gear',
    [K.gearNoseLabel]: 'NOSE\nGEAR',
    [K.gearLeftLabel]: 'LEFT\nGEAR',
    [K.gearRightLabel]: 'RIGHT\nGEAR',
    [K.gearPositionUp]: 'UP',
    [K.gearPositionOff]: 'OFF',
    [K.gearPositionDown]: 'DN',
    [K.gearHandleLabel]: 'LANDING GEAR',
    [K.gearLimitTitle]: 'LANDING GEAR LIMIT (IAS)',
    [K.gearLimitContent]: 'OPERATING EXTEND 270K - 82M\nRETRACT 235K\nEXTENDED 320K - 82M',
    [K.chartGForceTitle]: 'G-Force',
    [K.chartAltitudeTitle]: 'Altitude Trend',
    [K.chartBaroTitle]: 'Barometric Pressure',
    [K.unitG]: 'G',
    [K.unitFt]: 'FT',
    [K.unitInHg]: 'inHg',
  },
};
