import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * FlightLogs 模块国际化
 *
 * 对应 Flutter 版 `modules/flight_logs/localization/*.dart`（126 个 key）。
 * 由脚本机械转换，key 与文案逐条对齐。
 */
export const FlightLogsLocalizationKeys = {
  navTitle: 'flight_logs.nav.title',
  pageTitle: 'flight_logs.page.title',
  logsTabsLabel: 'flight_logs.tabs.label',
  logsFlightTab: 'flight_logs.tabs.flight_logs',
  logsLandingReportsTab: 'flight_logs.tabs.landing_reports',
  landingReportsLoading: 'flight_logs.landing_reports.loading',
  landingReportsEmptyTitle: 'flight_logs.landing_reports.empty.title',
  landingReportsEmptySubtitle: 'flight_logs.landing_reports.empty.subtitle',
  landingReportsLoadError: 'flight_logs.landing_reports.load_error',
  landingReportsLoadErrorHint: 'flight_logs.landing_reports.load_error_hint',
  landingReportsRetry: 'flight_logs.landing_reports.retry',
  landingReportOpen: 'flight_logs.landing_reports.open',
  landingReportDelete: 'flight_logs.landing_reports.delete',
  landingReportBack: 'flight_logs.landing_reports.back',
  landingReportOverview: 'flight_logs.landing_reports.overview',
  landingReportTouchdownTime: 'flight_logs.landing_reports.touchdown_time',
  landingReportTouchdownUnavailable: 'flight_logs.landing_reports.touchdown_unavailable',
  landingReportSimulator: 'flight_logs.landing_reports.simulator',
  landingReportStatus: 'flight_logs.landing_reports.status',
  landingReportEndReason: 'flight_logs.landing_reports.end_reason',
  landingReportHeightSource: 'flight_logs.landing_reports.height_source',
  landingReportMetrics: 'flight_logs.landing_reports.metrics',
  landingReportAircraft: 'flight_logs.landing_reports.aircraft',
  landingReportAirport: 'flight_logs.landing_reports.airport',
  landingReportExportJson: 'flight_logs.landing_reports.export_json',
  landingReportConfiguration: 'flight_logs.landing_reports.configuration',
  landingReportWeather: 'flight_logs.landing_reports.weather',
  landingReportMixedSources: 'flight_logs.landing_reports.height_source.mixed',
  landingReportFlaps: 'flight_logs.landing_reports.configuration.flaps',
  landingReportGear: 'flight_logs.landing_reports.configuration.gear',
  landingReportAutobrake: 'flight_logs.landing_reports.configuration.autobrake',
  landingReportSpoilers: 'flight_logs.landing_reports.configuration.spoilers',
  landingReportAutopilot: 'flight_logs.landing_reports.configuration.autopilot',
  landingReportAutothrottle: 'flight_logs.landing_reports.configuration.autothrottle',
  landingReportLandingLights: 'flight_logs.landing_reports.configuration.landing_lights',
  landingReportWind: 'flight_logs.landing_reports.weather.wind',
  landingReportGust: 'flight_logs.landing_reports.weather.gust',
  landingReportTemperature: 'flight_logs.landing_reports.weather.temperature',
  landingReportPressure: 'flight_logs.landing_reports.weather.pressure',
  landingReportCrosswind: 'flight_logs.landing_reports.weather.crosswind',
  landingReportTouchdownSequenceTime: 'flight_logs.landing_reports.touchdown_sequence.time',
  landingReportTouchdownSequenceG: 'flight_logs.landing_reports.touchdown_sequence.g',
  landingReportTouchdownSequenceSink: 'flight_logs.landing_reports.touchdown_sequence.sink',
  landingReportTouchdownSequenceHeight: 'flight_logs.landing_reports.touchdown_sequence.height',
  landingReportBounces: 'flight_logs.landing_reports.bounces',
  landingGroundSpeed: 'flight_logs.landing_reports.ground_speed',
  landingRoll: 'flight_logs.landing_reports.roll',
  landingHeightSourceRadio: 'flight_logs.landing_reports.height_source.radio',
  landingHeightSourceAglFallback: 'flight_logs.landing_reports.height_source.agl_fallback',
  landingHeightSourceUnavailable: 'flight_logs.landing_reports.height_source.unavailable',
  landingStatusCompleted: 'flight_logs.landing_reports.status.completed',
  landingStatusIncomplete: 'flight_logs.landing_reports.status.incomplete',
  landingReasonStableLanding: 'flight_logs.landing_reports.reason.stable_landing',
  landingReasonTouchAndGo: 'flight_logs.landing_reports.reason.touch_and_go',
  landingReasonUserStopped: 'flight_logs.landing_reports.reason.user_stopped',
  landingReasonSimulatorDisconnected: 'flight_logs.landing_reports.reason.simulator_disconnected',
  landingReasonPageClosed: 'flight_logs.landing_reports.reason.page_closed',
  landingReasonInterrupted: 'flight_logs.landing_reports.reason.interrupted',
  landingReasonUnavailable: 'flight_logs.landing_reports.reason.unavailable',
  landingDeleteConfirmTitle: 'flight_logs.landing_reports.delete_confirm.title',
  landingDeleteConfirmContent: 'flight_logs.landing_reports.delete_confirm.content',
  landingDeleteConfirm: 'flight_logs.landing_reports.delete_confirm.action',
  landingDeleteSuccess: 'flight_logs.landing_reports.delete_success',
  landingDeleteError: 'flight_logs.landing_reports.delete_error',
  landingDismissError: 'flight_logs.landing_reports.dismiss_error',
  emptyTitle: 'flight_logs.empty.title',
  emptySubtitle: 'flight_logs.empty.subtitle',
  importLog: 'flight_logs.action.import',
  exportLog: 'flight_logs.action.export',
  deleteLog: 'flight_logs.action.delete',
  deleteConfirmTitle: 'flight_logs.delete.title',
  deleteConfirmContent: 'flight_logs.delete.content',
  deleteConfirm: 'flight_logs.delete.confirm',
  cancel: 'flight_logs.action.cancel',
  notConnected: 'flight_logs.message.not_connected',
  importSuccess: 'flight_logs.message.import_success',
  exportSuccess: 'flight_logs.message.export_success',
  deleteSuccess: 'flight_logs.message.delete_success',
  startRecord: 'flight_logs.action.start_record',
  stopRecord: 'flight_logs.action.stop_record',
  startRecordStarted: 'flight_logs.message.start_record_started',
  stopRecordSaved: 'flight_logs.message.stop_record_saved',
  stopRecordDiscarded: 'flight_logs.message.stop_record_discarded',
  detailTitle: 'flight_logs.detail.title',
  detailTrack: 'flight_logs.detail.track',
  trackPointTimeUtc: 'flight_logs.track_point.time_utc',
  trackPhaseTaxiOut: 'flight_logs.track_phase.taxi_out',
  trackPhaseClimb: 'flight_logs.track_phase.climb',
  trackPhaseCruise: 'flight_logs.track_phase.cruise',
  trackPhaseArrival: 'flight_logs.track_phase.arrival',
  trackPhaseApproach: 'flight_logs.track_phase.approach',
  trackPhaseTaxiIn: 'flight_logs.track_phase.taxi_in',
  // 航迹回放
  replayPlay: 'flight_logs.replay.play',
  replayPause: 'flight_logs.replay.pause',
  replayReset: 'flight_logs.replay.reset',
  replayLive: 'flight_logs.replay.live',
  replaySpeed: 'flight_logs.replay.speed',
  replayHeading: 'flight_logs.replay.heading',
  landingTouchdownSequence: 'flight_logs.detail.touchdown_sequence',
  detailProfile: 'flight_logs.detail.profile',
  eventTakeoff: 'flight_logs.detail.takeoff',
  eventLanding: 'flight_logs.detail.landing',
  listDeparture: 'flight_logs.list.departure',
  listArrival: 'flight_logs.list.arrival',
  listUnknownAirport: 'flight_logs.list.unknown_airport',
  listIncompleteFlight: 'flight_logs.list.incomplete',
  runway: 'flight_logs.detail.runway',
  airspeed: 'flight_logs.detail.airspeed',
  verticalSpeed: 'flight_logs.detail.vertical_speed',
  gForce: 'flight_logs.detail.g_force',
  pitch: 'flight_logs.detail.pitch',
  heading: 'flight_logs.detail.heading',
  remainingRunway: 'flight_logs.detail.remaining_runway',
  metricUnavailableNoTakeoff: 'flight_logs.metric_na.no_takeoff',
  metricUnavailableNoLanding: 'flight_logs.metric_na.no_landing',
  metricUnavailableNoRotation: 'flight_logs.metric_na.no_rotation',
  metricUnavailableNoAgl: 'flight_logs.metric_na.no_agl',
  metricUnavailableFewSamples: 'flight_logs.metric_na.few_samples',
  metricUnavailableNoRunway: 'flight_logs.metric_na.no_runway',
  takeoffStability: 'flight_logs.detail.takeoff_stability',
  rotationSpeed: 'flight_logs.detail.rotation_speed',
  rotationToLiftoff: 'flight_logs.detail.rotation_to_liftoff',
  crosswindLiftoff: 'flight_logs.detail.crosswind_liftoff',
  pitchAt35Ft: 'flight_logs.detail.pitch_35ft',
  approachStability: 'flight_logs.detail.approach_stability',
  flareHeight: 'flight_logs.detail.flare_height',
  sinkRateAt50: 'flight_logs.detail.sink_rate_50',
  crosswindTouchdown: 'flight_logs.detail.crosswind_touchdown',
  bounceCount: 'flight_logs.detail.bounce_count',
  ratingPerfect: 'flight_logs.rating.perfect',
  ratingSoft: 'flight_logs.rating.soft',
  ratingAcceptable: 'flight_logs.rating.acceptable',
  ratingHard: 'flight_logs.rating.hard',
  ratingFired: 'flight_logs.rating.fired',
  ratingRip: 'flight_logs.rating.rip',
  blackBoxTitle: 'flight_logs.black_box.title',
  blackBoxRows: 'flight_logs.black_box.rows',
  blackBoxTime: 'flight_logs.black_box.time',
  blackBoxAltitude: 'flight_logs.black_box.altitude',
  blackBoxGroundSpeed: 'flight_logs.black_box.ground_speed',
  blackBoxHeading: 'flight_logs.black_box.heading',
  blackBoxPosition: 'flight_logs.black_box.position',
  blackBoxVerticalSpeed: 'flight_logs.black_box.vertical_speed',
  blackBoxGForce: 'flight_logs.black_box.g_force',
  blackBoxGSource: 'flight_logs.black_box.g_source',
  blackBoxAoa: 'flight_logs.black_box.aoa',
  blackBoxApAt: 'flight_logs.black_box.ap_at',
  blackBoxFlightPhase: 'flight_logs.black_box.flight_phase',
  blackBoxApHeadingTarget: 'flight_logs.black_box.ap_heading_target',
  blackBoxFlapsGear: 'flight_logs.black_box.flaps_gear',
  blackBoxWind: 'flight_logs.black_box.wind',
  blackBoxEngine: 'flight_logs.black_box.engine',
  blackBoxSystem: 'flight_logs.black_box.system',
  blackBoxBaro: 'flight_logs.black_box.baro',
  blackBoxEvent: 'flight_logs.black_box.event',
  blackBoxAlert: 'flight_logs.black_box.alert',
  blackBoxAnomalyAlert: 'flight_logs.black_box.anomaly',
  blackBoxJumpToPage: 'flight_logs.black_box.jump_to_page',
  blackBoxJumpAction: 'flight_logs.black_box.jump_action',
  blackBoxPageUnit: 'flight_logs.black_box.page_unit',
  summaryTitle: 'flight_logs.summary.title',
  summaryDuration: 'flight_logs.summary.duration',
  summaryAirborneDuration: 'flight_logs.summary.airborne_duration',
  summaryMaxAlt: 'flight_logs.summary.max_alt',
  summaryMaxGs: 'flight_logs.summary.max_gs',
  summaryFuel: 'flight_logs.summary.fuel',
  summaryMaxG: 'flight_logs.summary.max_g',
  summaryMinG: 'flight_logs.summary.min_g',
  summaryTouchdownG: 'flight_logs.summary.touchdown_g',
  chartAltitude: 'flight_logs.chart.altitude',
  chartSpeed: 'flight_logs.chart.speed',
  chartPitch: 'flight_logs.chart.pitch',
  chartVerticalSpeed: 'flight_logs.chart.vertical_speed',
  chartGForce: 'flight_logs.chart.g_force',
  chartBaro: 'flight_logs.chart.baro',
  chartAoa: 'flight_logs.chart.aoa',
  chartEngine1N1: 'flight_logs.chart.engine1_n1',
  chartEngine2N1: 'flight_logs.chart.engine2_n1',
  chartEngine1N2: 'flight_logs.chart.engine1_n2',
  chartEngine2N2: 'flight_logs.chart.engine2_n2',
  chartEngine1Egt: 'flight_logs.chart.engine1_egt',
  chartEngine2Egt: 'flight_logs.chart.engine2_egt',
  chartAileronInput: 'flight_logs.chart.aileron_input',
  chartElevatorInput: 'flight_logs.chart.elevator_input',
  chartRudderInput: 'flight_logs.chart.rudder_input',
  chartAileronTrim: 'flight_logs.chart.aileron_trim',
  chartElevatorTrim: 'flight_logs.chart.elevator_trim',
  chartRudderTrim: 'flight_logs.chart.rudder_trim',
  chartCrosswind: 'flight_logs.chart.crosswind',
  chartRadioAltitude: 'flight_logs.chart.radio_altitude',
  chartGustDelta: 'flight_logs.chart.gust_delta',
  chartNoData: 'flight_logs.chart.no_data',
  chartCombined: 'flight_logs.chart.combined',
  chartShowCombined: 'flight_logs.chart.show_combined',
  chartHideCombined: 'flight_logs.chart.hide_combined',
  chartEvents: 'flight_logs.chart.events',
  chartScaleHelp: 'flight_logs.chart.scale_help',
  chartMinuteUnit: 'flight_logs.chart.minute_unit',
  chartEventTakeoff: 'flight_logs.chart.event.takeoff',
  chartEventFlaps: 'flight_logs.chart.event.flaps',
  chartEventFlapsDeploy: 'flight_logs.chart.event.flaps_deploy',
  chartEventFlapsRetract: 'flight_logs.chart.event.flaps_retract',
  chartEventAutopilotLateral: 'flight_logs.chart.event.autopilot_lateral',
  chartEventAutopilotVertical: 'flight_logs.chart.event.autopilot_vertical',
  chartEventGearDown: 'flight_logs.chart.event.gear_down',
  chartEventGearUp: 'flight_logs.chart.event.gear_up',
  chartEventTouchdown: 'flight_logs.chart.event.touchdown',
  chartEventFinalTouchdown: 'flight_logs.chart.event.final_touchdown',
  chartTooltipAlt: 'flight_logs.chart.tooltip_alt',
  chartTooltipSpeed: 'flight_logs.chart.tooltip_speed',
  flareTab: 'flight_logs.flare.tab',
  flareTitle: 'flight_logs.flare.title',
  flareSubtitle: 'flight_logs.flare.subtitle',
  flareSecondsBeforeTouchdown: 'flight_logs.flare.seconds_before_touchdown',
  flareUtcTime: 'flight_logs.flare.utc_time',
  flareTouchdown: 'flight_logs.flare.touchdown',
  flareSinkReduction: 'flight_logs.flare.sink_reduction',
  flareLegend: 'flight_logs.flare.legend',
  flareVerticalAcceleration: 'flight_logs.flare.vertical_acceleration',
  flareCalibratedAirspeed: 'flight_logs.flare.calibrated_airspeed',
  flareEngineN1: 'flight_logs.flare.engine_n1',
  flareGroundAir: 'flight_logs.flare.ground_air',
  flareRadioAltitude: 'flight_logs.flare.radio_altitude',
  flareRoll: 'flight_logs.flare.roll',
  flareGroundSpeed: 'flight_logs.flare.ground_speed',
  flareNoLandingTitle: 'flight_logs.flare.no_landing_title',
  flareNoLandingDescription: 'flight_logs.flare.no_landing_description',
  flareAxisZeroAtBottom: 'flight_logs.flare.axis_zero_at_bottom',
  simulatorMsfs: 'flight_logs.simulator.msfs',
  simulatorXplane: 'flight_logs.simulator.xplane',
  simulatorUnknown: 'flight_logs.simulator.unknown',
} as const;

const K = FlightLogsLocalizationKeys;

export const flightLogsTranslations: ModuleTranslations = {
  zh_CN: {
    [K.navTitle]: '飞行日志',
    [K.pageTitle]: '飞行日志',
    [K.logsTabsLabel]: '日志类型',
    [K.logsFlightTab]: '飞行日志',
    [K.logsLandingReportsTab]: '落地报告',
    [K.landingReportsLoading]: '正在加载落地报告',
    [K.landingReportsEmptyTitle]: '暂无落地报告',
    [K.landingReportsEmptySubtitle]: '启用自动生成后，完成进近即可在此查看报告',
    [K.landingReportsLoadError]: '无法加载落地报告',
    [K.landingReportsLoadErrorHint]: '检查存储连接后重试。',
    [K.landingReportsRetry]: '重试',
    [K.landingReportOpen]: '落地报告 {id}',
    [K.landingReportDelete]: '删除落地报告 {id}',
    [K.landingReportBack]: '返回',
    [K.landingReportOverview]: '落地报告概览',
    [K.landingReportTouchdownTime]: '接地时间',
    [K.landingReportTouchdownUnavailable]: '未记录接地',
    [K.landingReportSimulator]: '模拟器',
    [K.landingReportStatus]: '状态',
    [K.landingReportEndReason]: '结束原因',
    [K.landingReportHeightSource]: '高度来源',
    [K.landingReportMetrics]: '落地指标',
    [K.landingReportAircraft]: '机型',
    [K.landingReportAirport]: '机场',
    [K.landingReportExportJson]: '导出 JSON',
    [K.landingReportConfiguration]: '接地构型',
    [K.landingReportWeather]: '接地天气',
    [K.landingReportMixedSources]: '混合来源',
    [K.landingReportFlaps]: '襟翼',
    [K.landingReportGear]: '起落架',
    [K.landingReportAutobrake]: '自动刹车',
    [K.landingReportSpoilers]: '扰流板',
    [K.landingReportAutopilot]: '自动驾驶',
    [K.landingReportAutothrottle]: '自动油门',
    [K.landingReportLandingLights]: '着陆灯',
    [K.landingReportWind]: '风',
    [K.landingReportGust]: '阵风 {value}',
    [K.landingReportTemperature]: '气温',
    [K.landingReportPressure]: '气压',
    [K.landingReportCrosswind]: '侧风',
    [K.landingReportTouchdownSequenceTime]: '时间',
    [K.landingReportTouchdownSequenceG]: 'G 值',
    [K.landingReportTouchdownSequenceSink]: '下沉率',
    [K.landingReportTouchdownSequenceHeight]: '高度',
    [K.landingReportBounces]: '{count} 次弹跳',
    [K.landingGroundSpeed]: '地速',
    [K.landingRoll]: '横滚角',
    [K.landingHeightSourceRadio]: '无线电高度表',
    [K.landingHeightSourceAglFallback]: '离地高度估算',
    [K.landingHeightSourceUnavailable]: '无可用高度来源',
    [K.landingStatusCompleted]: '已完成',
    [K.landingStatusIncomplete]: '未完成',
    [K.landingReasonStableLanding]: '稳定落地',
    [K.landingReasonTouchAndGo]: '连续起降',
    [K.landingReasonUserStopped]: '用户停止',
    [K.landingReasonSimulatorDisconnected]: '模拟器连接中断',
    [K.landingReasonPageClosed]: '页面关闭',
    [K.landingReasonInterrupted]: '录制中断',
    [K.landingReasonUnavailable]: '原因不可用',
    [K.landingDeleteConfirmTitle]: '删除落地报告',
    [K.landingDeleteConfirmContent]: '确定要删除这份落地报告吗？此操作不可撤销。',
    [K.landingDeleteConfirm]: '删除',
    [K.landingDeleteSuccess]: '已删除落地报告',
    [K.landingDeleteError]: '无法删除落地报告，请重试。',
    [K.landingDismissError]: '关闭错误提示',
    [K.emptyTitle]: '尚未记录任何飞行日志',
    [K.emptySubtitle]: '接入数据后即可在这里看到飞行记录',
    [K.importLog]: '导入日志',
    [K.exportLog]: '导出',
    [K.deleteLog]: '删除',
    [K.deleteConfirmTitle]: '删除飞行日志',
    [K.deleteConfirmContent]: '确定要删除这条飞行记录吗？此操作不可撤销。',
    [K.deleteConfirm]: '删除',
    [K.cancel]: '取消',
    [K.notConnected]: '尚未接入日志数据接口',
    [K.importSuccess]: '导入飞行日志成功',
    [K.exportSuccess]: '导出飞行日志成功',
    [K.deleteSuccess]: '已删除飞行日志',
    [K.startRecord]: '开始录制',
    [K.stopRecord]: '停止录制',
    [K.startRecordStarted]: '已开始飞行日志录制',
    [K.stopRecordSaved]: '已停止录制并保存飞行日志',
    [K.stopRecordDiscarded]: '录制未保存：时长不足1分钟，请延长录制后再停止',
    [K.detailTitle]: '飞行分析',
    [K.detailTrack]: '飞行轨迹',
    [K.trackPointTimeUtc]: '时间 (UTC)',
    [K.trackPhaseTaxiOut]: '起飞前滑行',
    [K.trackPhaseClimb]: '爬升中',
    [K.trackPhaseCruise]: '巡航中',
    [K.trackPhaseArrival]: '到达/下降',
    [K.trackPhaseApproach]: '进近中',
    [K.trackPhaseTaxiIn]: '落地后滑行',
    [K.replayPlay]: '播放',
    [K.replayPause]: '暂停',
    [K.replayReset]: '回到起点',
    [K.replayLive]: '全程',
    [K.replaySpeed]: '倍速',
    [K.replayHeading]: '航向',
    [K.landingTouchdownSequence]: '接地序列',
    [K.detailProfile]: '飞行质量报告',
    [K.eventTakeoff]: '起飞数据',
    [K.eventLanding]: '降落数据',
    [K.listDeparture]: '起飞',
    [K.listArrival]: '到达',
    [K.listUnknownAirport]: '未知',
    [K.listIncompleteFlight]: '未完成的飞行',
    [K.runway]: '跑道',
    [K.airspeed]: '空速',
    [K.verticalSpeed]: '垂直速度',
    [K.gForce]: '着陆G值',
    [K.pitch]: '俯仰角',
    [K.heading]: '航向',
    [K.remainingRunway]: '剩余跑道',
    [K.metricUnavailableNoTakeoff]: '本次未记录到起飞',
    [K.metricUnavailableNoLanding]: '本次未记录到落地',
    [K.metricUnavailableNoRotation]: '未采到抬轮过程',
    [K.metricUnavailableNoAgl]: '本机型未提供离地高度',
    [K.metricUnavailableFewSamples]: '采样点不足，无法评分',
    [K.metricUnavailableNoRunway]: '未能定位所在跑道',
    [K.takeoffStability]: '起飞稳定性',
    [K.rotationSpeed]: '抬轮速度',
    [K.rotationToLiftoff]: '抬轮到离地耗时',
    [K.crosswindLiftoff]: '离地侧风',
    [K.pitchAt35Ft]: '35英尺俯仰角',
    [K.approachStability]: '进近稳定性',
    [K.flareHeight]: '拉平高度',
    [K.sinkRateAt50]: '50英尺下沉率',
    [K.crosswindTouchdown]: '接地侧风',
    [K.bounceCount]: '弹跳次数',
    [K.ratingPerfect]: '完美着陆',
    [K.ratingSoft]: '软着陆',
    [K.ratingAcceptable]: '可接受着陆',
    [K.ratingHard]: '硬着陆',
    [K.ratingFired]: '你被开除了',
    [K.ratingRip]: 'R.I.P.',
    [K.blackBoxTitle]: '黑匣子数据明细',
    [K.blackBoxRows]: '条记录',
    [K.blackBoxTime]: '时间 (UTC)',
    [K.blackBoxAltitude]: '高度(ft)',
    [K.blackBoxGroundSpeed]: '地速(kts)',
    [K.blackBoxHeading]: '航向(°)',
    [K.blackBoxPosition]: '经纬度',
    [K.blackBoxVerticalSpeed]: 'VS(fpm)',
    [K.blackBoxGForce]: 'G值',
    [K.blackBoxGSource]: 'G来源',
    [K.blackBoxAoa]: 'AOA(°)',
    [K.blackBoxApAt]: 'AP/AT',
    [K.blackBoxFlightPhase]: '飞行阶段',
    [K.blackBoxApHeadingTarget]: 'AP航向目标(°)',
    [K.blackBoxFlapsGear]: '襟翼/起落架',
    [K.blackBoxWind]: '风速/风向',
    [K.blackBoxEngine]: '发动机',
    [K.blackBoxSystem]: '系统状态',
    [K.blackBoxBaro]: '修正海压',
    [K.blackBoxEvent]: '事件节点',
    [K.blackBoxAlert]: '警告/告警',
    [K.blackBoxAnomalyAlert]: '异常姿态告警',
    [K.blackBoxJumpToPage]: '跳转页码',
    [K.blackBoxJumpAction]: '跳转',
    [K.blackBoxPageUnit]: '页',
    [K.summaryTitle]: '分析摘要',
    [K.summaryDuration]: '总记录时长',
    [K.summaryAirborneDuration]: '真实飞行时长',
    [K.summaryMaxAlt]: '最大高度',
    [K.summaryMaxGs]: '最高地速',
    [K.summaryFuel]: '燃油消耗',
    [K.summaryMaxG]: '最大重力',
    [K.summaryMinG]: '最小重力',
    [K.summaryTouchdownG]: '接地瞬时G值',
    [K.chartAltitude]: '高度 (ft)',
    [K.chartSpeed]: '地速 (kts)',
    [K.chartPitch]: '俯仰角 (°)',
    [K.chartVerticalSpeed]: '垂直速度 (fpm)',
    [K.chartGForce]: '实时G值',
    [K.chartBaro]: '气压高度 (inHg)',
    [K.chartAoa]: 'AOA (°)',
    [K.chartEngine1N1]: '发动机1 N1 (%)',
    [K.chartEngine2N1]: '发动机2 N1 (%)',
    [K.chartEngine1N2]: '发动机1 N2 (%)',
    [K.chartEngine2N2]: '发动机2 N2 (%)',
    [K.chartEngine1Egt]: '发动机1 EGT (°C)',
    [K.chartEngine2Egt]: '发动机2 EGT (°C)',
    [K.chartAileronInput]: '副翼输入',
    [K.chartElevatorInput]: '升降舵输入',
    [K.chartRudderInput]: '方向舵输入',
    [K.chartAileronTrim]: '副翼配平',
    [K.chartElevatorTrim]: '升降舵配平',
    [K.chartRudderTrim]: '方向舵配平',
    [K.chartCrosswind]: '侧风分量 (kts)',
    [K.chartRadioAltitude]: '无线电高度 (ft)',
    [K.chartGustDelta]: '阵风增量 (kts)',
    [K.chartNoData]: '无数据',
    [K.chartScaleHelp]: '提示：拖动横轴或纵轴刻度文本可拉宽/收紧图表间隔',
    [K.chartMinuteUnit]: '分',
    [K.chartCombined]: '\u5408\u5e76\u56fe\u8868',
    [K.chartShowCombined]: '\u663e\u793a\u5408\u5e76\u56fe\u8868',
    [K.chartHideCombined]: '\u9690\u85cf\u5408\u5e76\u56fe\u8868',
    [K.chartEvents]: '\u98de\u884c\u4e8b\u4ef6',
    [K.chartEventTakeoff]: '起飞点',
    [K.chartEventFlaps]: '襟翼放下',
    [K.chartEventFlapsDeploy]: '襟翼放下',
    [K.chartEventFlapsRetract]: '襟翼收起',
    [K.chartEventAutopilotLateral]: 'AP横向模式',
    [K.chartEventAutopilotVertical]: 'AP纵向模式',
    [K.chartEventGearDown]: '起落架放下',
    [K.chartEventGearUp]: '起落架收起',
    [K.chartEventTouchdown]: '接地点',
    [K.chartEventFinalTouchdown]: '最终接地点',
    [K.chartTooltipAlt]: '高度',
    [K.chartTooltipSpeed]: '速度',
    [K.flareAxisZeroAtBottom]: '基准线 0 置底',
    [K.simulatorMsfs]: 'MSFS',
    [K.simulatorXplane]: 'X-Plane',
    [K.simulatorUnknown]: '未知模拟器',
  },
  en_US: {
    [K.navTitle]: 'Flight Logs',
    [K.pageTitle]: 'Flight Logs',
    [K.logsTabsLabel]: 'Log type',
    [K.logsFlightTab]: 'Flight Logs',
    [K.logsLandingReportsTab]: 'Landing Reports',
    [K.landingReportsLoading]: 'Loading landing reports',
    [K.landingReportsEmptyTitle]: 'No landing reports yet',
    [K.landingReportsEmptySubtitle]: 'Completed approaches appear here when automatic reports are enabled.',
    [K.landingReportsLoadError]: 'Could not load landing reports',
    [K.landingReportsLoadErrorHint]: 'Check the storage connection, then try again.',
    [K.landingReportsRetry]: 'Retry',
    [K.landingReportOpen]: 'Landing report {id}',
    [K.landingReportDelete]: 'Delete landing report {id}',
    [K.landingReportBack]: 'Back',
    [K.landingReportOverview]: 'Landing report overview',
    [K.landingReportTouchdownTime]: 'Touchdown time',
    [K.landingReportTouchdownUnavailable]: 'No touchdown recorded',
    [K.landingReportSimulator]: 'Simulator',
    [K.landingReportStatus]: 'Status',
    [K.landingReportEndReason]: 'End reason',
    [K.landingReportHeightSource]: 'Height source',
    [K.landingReportMetrics]: 'Landing metrics',
    [K.landingReportAircraft]: 'Aircraft',
    [K.landingReportAirport]: 'Airport',
    [K.landingReportExportJson]: 'Export JSON',
    [K.landingReportConfiguration]: 'Configuration at touchdown',
    [K.landingReportWeather]: 'Weather at touchdown',
    [K.landingReportMixedSources]: 'Mixed sources',
    [K.landingReportFlaps]: 'Flaps',
    [K.landingReportGear]: 'Gear',
    [K.landingReportAutobrake]: 'Autobrake',
    [K.landingReportSpoilers]: 'Spoilers',
    [K.landingReportAutopilot]: 'Autopilot',
    [K.landingReportAutothrottle]: 'Autothrottle',
    [K.landingReportLandingLights]: 'Landing lights',
    [K.landingReportWind]: 'Wind',
    [K.landingReportGust]: 'gust {value}',
    [K.landingReportTemperature]: 'Temperature',
    [K.landingReportPressure]: 'Pressure',
    [K.landingReportCrosswind]: 'Crosswind',
    [K.landingReportTouchdownSequenceTime]: 'Time',
    [K.landingReportTouchdownSequenceG]: 'G',
    [K.landingReportTouchdownSequenceSink]: 'Sink rate',
    [K.landingReportTouchdownSequenceHeight]: 'Height',
    [K.landingReportBounces]: '{count} bounces',
    [K.landingGroundSpeed]: 'Ground speed',
    [K.landingRoll]: 'Roll',
    [K.landingHeightSourceRadio]: 'Radio altimeter',
    [K.landingHeightSourceAglFallback]: 'AGL fallback',
    [K.landingHeightSourceUnavailable]: 'Height source unavailable',
    [K.landingStatusCompleted]: 'Completed',
    [K.landingStatusIncomplete]: 'Incomplete',
    [K.landingReasonStableLanding]: 'Stable landing',
    [K.landingReasonTouchAndGo]: 'Touch-and-go',
    [K.landingReasonUserStopped]: 'Stopped by user',
    [K.landingReasonSimulatorDisconnected]: 'Simulator disconnected',
    [K.landingReasonPageClosed]: 'Page closed',
    [K.landingReasonInterrupted]: 'Recording interrupted',
    [K.landingReasonUnavailable]: 'Reason unavailable',
    [K.landingDeleteConfirmTitle]: 'Delete landing report',
    [K.landingDeleteConfirmContent]: 'Are you sure you want to delete this landing report? This action cannot be undone.',
    [K.landingDeleteConfirm]: 'Delete',
    [K.landingDeleteSuccess]: 'Landing report deleted',
    [K.landingDeleteError]: 'Landing report could not be deleted. Try again.',
    [K.landingDismissError]: 'Dismiss error',
    [K.emptyTitle]: 'No flight logs recorded',
    [K.emptySubtitle]: 'Connect data sources to view flight logs here',
    [K.importLog]: 'Import Log',
    [K.exportLog]: 'Export',
    [K.deleteLog]: 'Delete',
    [K.deleteConfirmTitle]: 'Delete flight log',
    [K.deleteConfirmContent]: 'Are you sure you want to delete this log? This action cannot be undone.',
    [K.deleteConfirm]: 'Delete',
    [K.cancel]: 'Cancel',
    [K.notConnected]: 'Flight log adapter is not connected',
    [K.importSuccess]: 'Flight log imported',
    [K.exportSuccess]: 'Flight log exported',
    [K.deleteSuccess]: 'Flight log deleted',
    [K.startRecord]: 'Start Recording',
    [K.stopRecord]: 'Stop Recording',
    [K.startRecordStarted]: 'Flight log recording started',
    [K.stopRecordSaved]: 'Recording stopped and flight log saved',
    [K.stopRecordDiscarded]: 'Recording not saved: duration is less than 1 minute',
    [K.detailTitle]: 'Flight Analysis',
    [K.detailTrack]: 'Flight Track',
    [K.trackPointTimeUtc]: 'Time (UTC)',
    [K.trackPhaseTaxiOut]: 'Taxi out',
    [K.trackPhaseClimb]: 'Climb',
    [K.trackPhaseCruise]: 'Cruise',
    [K.trackPhaseArrival]: 'Arrival / descent',
    [K.trackPhaseApproach]: 'Approach',
    [K.trackPhaseTaxiIn]: 'Taxi in',
    [K.replayPlay]: 'Play',
    [K.replayPause]: 'Pause',
    [K.replayReset]: 'Restart',
    [K.replayLive]: 'Full Track',
    [K.replaySpeed]: 'Speed',
    [K.replayHeading]: 'Heading',
    [K.landingTouchdownSequence]: 'Touchdown Sequence',
    [K.detailProfile]: 'Flight Quality Report',
    [K.eventTakeoff]: 'Takeoff Data',
    [K.eventLanding]: 'Landing Data',
    [K.listDeparture]: 'Departure',
    [K.listArrival]: 'Arrival',
    [K.listUnknownAirport]: 'Unknown',
    [K.listIncompleteFlight]: 'Incomplete Flight',
    [K.runway]: 'Runway',
    [K.airspeed]: 'Airspeed',
    [K.verticalSpeed]: 'Vertical Speed',
    [K.gForce]: 'Landing G',
    [K.pitch]: 'Pitch',
    [K.heading]: 'Heading',
    [K.remainingRunway]: 'Remaining Runway',
    [K.metricUnavailableNoTakeoff]: 'No takeoff recorded',
    [K.metricUnavailableNoLanding]: 'No landing recorded',
    [K.metricUnavailableNoRotation]: 'Rotation not captured',
    [K.metricUnavailableNoAgl]: 'No AGL data from this aircraft',
    [K.metricUnavailableFewSamples]: 'Too few samples to score',
    [K.metricUnavailableNoRunway]: 'Runway could not be identified',
    [K.takeoffStability]: 'Takeoff Stability',
    [K.rotationSpeed]: 'Rotation Speed',
    [K.rotationToLiftoff]: 'Rotation to Liftoff',
    [K.crosswindLiftoff]: 'Liftoff Crosswind',
    [K.pitchAt35Ft]: 'Pitch at 35ft',
    [K.approachStability]: 'Approach Stability',
    [K.flareHeight]: 'Flare Height',
    [K.sinkRateAt50]: 'Sink Rate at 50ft',
    [K.crosswindTouchdown]: 'Touchdown Crosswind',
    [K.bounceCount]: 'Bounce Count',
    [K.ratingPerfect]: 'Perfect',
    [K.ratingSoft]: 'Soft',
    [K.ratingAcceptable]: 'Acceptable',
    [K.ratingHard]: 'Hard',
    [K.ratingFired]: 'Fired',
    [K.ratingRip]: 'R.I.P.',
    [K.blackBoxTitle]: 'Black Box Data',
    [K.blackBoxRows]: 'records',
    [K.blackBoxTime]: 'Time (UTC)',
    [K.blackBoxAltitude]: 'Altitude(ft)',
    [K.blackBoxGroundSpeed]: 'Ground Speed(kts)',
    [K.blackBoxHeading]: 'Heading(°)',
    [K.blackBoxPosition]: 'Lat/Lon',
    [K.blackBoxVerticalSpeed]: 'VS(fpm)',
    [K.blackBoxGForce]: 'G',
    [K.blackBoxGSource]: 'G Source',
    [K.blackBoxAoa]: 'AOA(°)',
    [K.blackBoxApAt]: 'AP/AT',
    [K.blackBoxFlightPhase]: 'Flight Phase',
    [K.blackBoxApHeadingTarget]: 'AP Heading Target(°)',
    [K.blackBoxFlapsGear]: 'Flaps/Gear',
    [K.blackBoxWind]: 'Wind',
    [K.blackBoxEngine]: 'Engine',
    [K.blackBoxSystem]: 'System',
    [K.blackBoxBaro]: 'Baro',
    [K.blackBoxEvent]: 'Event Node',
    [K.blackBoxAlert]: 'Alert',
    [K.blackBoxAnomalyAlert]: 'Attitude Alert',
    [K.blackBoxJumpToPage]: 'Go to page',
    [K.blackBoxJumpAction]: 'Go',
    [K.blackBoxPageUnit]: 'page',
    [K.summaryTitle]: 'Summary',
    [K.summaryDuration]: 'Total Record Time',
    [K.summaryAirborneDuration]: 'Airborne Time',
    [K.summaryMaxAlt]: 'Max Altitude',
    [K.summaryMaxGs]: 'Max Ground Speed',
    [K.summaryFuel]: 'Fuel Used',
    [K.summaryMaxG]: 'Max G-Force',
    [K.summaryMinG]: 'Min G-Force',
    [K.summaryTouchdownG]: 'Touchdown G',
    [K.chartAltitude]: 'Altitude (ft)',
    [K.chartSpeed]: 'Ground Speed (kts)',
    [K.chartPitch]: 'Pitch (°)',
    [K.chartVerticalSpeed]: 'Vertical Speed (fpm)',
    [K.chartGForce]: 'Realtime G',
    [K.chartBaro]: 'Barometric Pressure (inHg)',
    [K.chartAoa]: 'AOA (°)',
    [K.chartEngine1N1]: 'Engine 1 N1 (%)',
    [K.chartEngine2N1]: 'Engine 2 N1 (%)',
    [K.chartEngine1N2]: 'Engine 1 N2 (%)',
    [K.chartEngine2N2]: 'Engine 2 N2 (%)',
    [K.chartEngine1Egt]: 'Engine 1 EGT (°C)',
    [K.chartEngine2Egt]: 'Engine 2 EGT (°C)',
    [K.chartAileronInput]: 'Aileron Input',
    [K.chartElevatorInput]: 'Elevator Input',
    [K.chartRudderInput]: 'Rudder Input',
    [K.chartAileronTrim]: 'Aileron Trim',
    [K.chartElevatorTrim]: 'Elevator Trim',
    [K.chartRudderTrim]: 'Rudder Trim',
    [K.chartCrosswind]: 'Crosswind (kts)',
    [K.chartRadioAltitude]: 'Radio Altitude (ft)',
    [K.chartGustDelta]: 'Gust Delta (kts)',
    [K.chartNoData]: 'No Data',
    [K.chartScaleHelp]: 'Tip: Drag X/Y axis labels to widen or tighten chart spacing',
    [K.chartMinuteUnit]: 'min',
    [K.chartCombined]: 'Combined Chart',
    [K.chartShowCombined]: 'Show Combined Chart',
    [K.chartHideCombined]: 'Hide Combined Chart',
    [K.chartEvents]: 'Flight Events',
    [K.chartEventTakeoff]: 'Takeoff',
    [K.chartEventFlaps]: 'Flaps Deploy',
    [K.chartEventFlapsDeploy]: 'Flaps Deploy',
    [K.chartEventFlapsRetract]: 'Flaps Retract',
    [K.chartEventAutopilotLateral]: 'AP Lateral Mode',
    [K.chartEventAutopilotVertical]: 'AP Vertical Mode',
    [K.chartEventGearDown]: 'Gear Down',
    [K.chartEventGearUp]: 'Gear Up',
    [K.chartEventTouchdown]: 'Touchdown',
    [K.chartEventFinalTouchdown]: 'Final Touchdown',
    [K.chartTooltipAlt]: 'Altitude',
    [K.chartTooltipSpeed]: 'Speed',
    [K.flareAxisZeroAtBottom]: 'Place zero baseline at bottom',
    [K.simulatorMsfs]: 'MSFS',
    [K.simulatorXplane]: 'X-Plane',
    [K.simulatorUnknown]: 'Unknown Simulator',
  },
};
