import type { ModuleTranslations } from '../../../core/services/localization-service';

/**
 * Checklist 模块国际化
 * 对应 Flutter 版 `modules/checklist/localization/*.dart`（65 个 key）
 */
export const ChecklistLocalizationKeys = {
  navTitle: 'checklist.nav.title',
  sidebarTitle: 'checklist.sidebar.title',
  currentPhase: 'checklist.header.current_phase',
  emptyPhase: 'checklist.empty_phase',
  resetPhase: 'checklist.footer.reset_phase',
  resetAll: 'checklist.footer.reset_all',
  resetPhaseConfirmTitle: 'checklist.footer.reset_phase_confirm_title',
  resetPhaseConfirmContent: 'checklist.footer.reset_phase_confirm_content',
  resetAllConfirmTitle: 'checklist.footer.reset_all_confirm_title',
  resetAllConfirmContent: 'checklist.footer.reset_all_confirm_content',
  resetPhaseSuccess: 'checklist.message.reset_phase_success',
  resetAllSuccess: 'checklist.message.reset_all_success',
  refresh: 'checklist.footer.refresh',
  importFile: 'checklist.footer.import',
  exportFile: 'checklist.footer.export',
  more: 'checklist.footer.more',
  selectAircraft: 'checklist.header.select_aircraft',
  importSuccess: 'checklist.message.import_success',
  importFailed: 'checklist.message.import_failed',
  exportSuccess: 'checklist.message.export_success',
  exportFailed: 'checklist.message.export_failed',
  refreshSuccess: 'checklist.message.refresh_success',
  refreshEmpty: 'checklist.message.refresh_empty',
  refreshFailed: 'checklist.message.refresh_failed',
  autoChecked: 'checklist.auto.checked',
  autoCheckedHint: 'checklist.auto.checked_hint',
  manualOverride: 'checklist.auto.manual_override',
  manualOverrideHint: 'checklist.auto.manual_override_hint',
  emptyState: 'checklist.empty_state',

  // ── 飞行阶段 ──
  phaseColdAndDark: 'checklist.phase.cold_and_dark',
  phaseBeforePushback: 'checklist.phase.before_pushback',
  phaseBeforeTaxi: 'checklist.phase.before_taxi',
  phaseBeforeTakeoff: 'checklist.phase.before_takeoff',
  phaseCruise: 'checklist.phase.cruise',
  phaseBeforeDescent: 'checklist.phase.before_descent',
  phaseBeforeApproach: 'checklist.phase.before_approach',
  phaseAfterLanding: 'checklist.phase.after_landing',
  phaseParking: 'checklist.phase.parking',

  // ── 折叠态步进 ──
  compactStepPrevious: 'checklist.sidebar.compact.previous',
  compactStepCurrent: 'checklist.sidebar.compact.current',
  compactStepNext: 'checklist.sidebar.compact.next',

  // ── 通用检查单条目 ──
  builtInGenericAircraft: 'checklist.aircraft.generic',
  genericTaskParkingBrake: 'checklist.generic.task.parking_brake',
  genericTaskBatteryPower: 'checklist.generic.task.battery_power',
  genericTaskAvionics: 'checklist.generic.task.avionics',
  genericTaskFlightPlan: 'checklist.generic.task.flight_plan',
  genericTaskFlightControls: 'checklist.generic.task.flight_controls',
  genericTaskFlaps: 'checklist.generic.task.flaps',
  genericTaskInstrumentCheck: 'checklist.generic.task.instrument_check',
  genericTaskTakeoffBriefing: 'checklist.generic.task.takeoff_briefing',
  genericTaskLights: 'checklist.generic.task.lights',
  genericTaskTransponder: 'checklist.generic.task.transponder',
  genericTaskEngineParameters: 'checklist.generic.task.engine_parameters',
  genericTaskRouteMonitoring: 'checklist.generic.task.route_monitoring',
  genericTaskApproachBriefing: 'checklist.generic.task.approach_briefing',
  genericTaskLandingData: 'checklist.generic.task.landing_data',
  genericResponseSet: 'checklist.generic.response.set',
  genericResponseOn: 'checklist.generic.response.on',
  genericResponseChecked: 'checklist.generic.response.checked',
  genericResponseCompleted: 'checklist.generic.response.completed',
  genericResponseFreeAndCorrect: 'checklist.generic.response.free_and_correct',
  genericResponseSetAsRequired: 'checklist.generic.response.set_as_required',
  genericResponseBriefed: 'checklist.generic.response.briefed',
  genericResponseTakeoff: 'checklist.generic.response.takeoff',
  genericResponseTaRa: 'checklist.generic.response.ta_ra',
  genericResponseNormal: 'checklist.generic.response.normal',
  genericResponseConfirmed: 'checklist.generic.response.confirmed',
  genericResponseUp: 'checklist.generic.response.up',
  genericResponseTaxi: 'checklist.generic.response.taxi',
} as const;

const K = ChecklistLocalizationKeys;

export const checklistTranslations: ModuleTranslations = {
  zh_CN: {
    [K.navTitle]: '检查单',
    [K.sidebarTitle]: '飞行阶段',
    [K.currentPhase]: '当前阶段',
    [K.emptyPhase]: '该机型尚无此阶段数据',
    [K.resetPhase]: '重置本阶段',
    [K.resetAll]: '重置全部',
    [K.resetPhaseConfirmTitle]: '确认重置本阶段',
    [K.resetPhaseConfirmContent]: '将清空当前阶段所有勾选项，是否继续？',
    [K.resetAllConfirmTitle]: '确认重置全部',
    [K.resetAllConfirmContent]: '将清空全部阶段勾选并回到初始阶段，是否继续？',
    [K.resetPhaseSuccess]: '本阶段已重置',
    [K.resetAllSuccess]: '全部阶段已重置',
    [K.refresh]: '刷新配置',
    [K.importFile]: '导入',
    [K.exportFile]: '导出',
    [K.more]: '更多',
    [K.selectAircraft]: '选择机型',
    [K.importSuccess]: '检查单已导入',
    [K.importFailed]: '检查单导入失败',
    [K.exportSuccess]: '检查单已导出',
    [K.exportFailed]: '检查单导出失败',
    [K.refreshSuccess]: '已加载 {} 个机型配置',
    [K.refreshEmpty]: '未找到可用的检查单配置',
    [K.refreshFailed]: '检查单刷新失败',
    [K.autoChecked]: '同步',
    [K.autoCheckedHint]: '该项由模拟器遥测自动勾选；手动点击后将改为手动控制',
    [K.manualOverride]: '手动',
    [K.manualOverrideHint]: '该项已改为手动控制，点击交还给模拟器遥测自动同步',
    [K.emptyState]: '暂无可用检查单',
    [K.phaseColdAndDark]: '冷舱启动',
    [K.phaseBeforePushback]: '推出前',
    [K.phaseBeforeTaxi]: '滑行前',
    [K.phaseBeforeTakeoff]: '起飞前',
    [K.phaseCruise]: '巡航',
    [K.phaseBeforeDescent]: '下降前',
    [K.phaseBeforeApproach]: '进近前',
    [K.phaseAfterLanding]: '落地后',
    [K.phaseParking]: '关车/停机',
    [K.compactStepPrevious]: '上一步',
    [K.compactStepCurrent]: '当前',
    [K.compactStepNext]: '下一步',
    [K.builtInGenericAircraft]: '通用机型',
    [K.genericTaskParkingBrake]: '停留刹车',
    [K.genericTaskBatteryPower]: '电瓶电源',
    [K.genericTaskAvionics]: '航电设备',
    [K.genericTaskFlightPlan]: '飞行计划',
    [K.genericTaskFlightControls]: '飞行操纵',
    [K.genericTaskFlaps]: '襟翼',
    [K.genericTaskInstrumentCheck]: '仪表检查',
    [K.genericTaskTakeoffBriefing]: '起飞简令',
    [K.genericTaskLights]: '灯光',
    [K.genericTaskTransponder]: '应答机',
    [K.genericTaskEngineParameters]: '发动机参数',
    [K.genericTaskRouteMonitoring]: '航迹监控',
    [K.genericTaskApproachBriefing]: '进近简令',
    [K.genericTaskLandingData]: '着陆数据',
    [K.genericResponseSet]: '设置 (SET)',
    [K.genericResponseOn]: '接通 (ON)',
    [K.genericResponseChecked]: '检查 (CHECKED)',
    [K.genericResponseCompleted]: '完成 (COMPLETED)',
    [K.genericResponseFreeAndCorrect]: '自由且正确',
    [K.genericResponseSetAsRequired]: '按需设置 (SET)',
    [K.genericResponseBriefed]: '完成 (BRIEFED)',
    [K.genericResponseTakeoff]: '起飞位 (SET)',
    [K.genericResponseTaRa]: 'TA/RA',
    [K.genericResponseNormal]: '正常 (NORMAL)',
    [K.genericResponseConfirmed]: '确认 (CONFIRMED)',
    [K.genericResponseUp]: '收上 (UP)',
    [K.genericResponseTaxi]: '滑行位 (TAXI)',
  },
  en_US: {
    [K.navTitle]: 'Checklist',
    [K.sidebarTitle]: 'Flight Phases',
    [K.currentPhase]: 'Current Phase',
    [K.emptyPhase]: 'No data available for this phase on this aircraft.',
    [K.resetPhase]: 'Reset Phase',
    [K.resetAll]: 'Reset All',
    [K.resetPhaseConfirmTitle]: 'Confirm phase reset',
    [K.resetPhaseConfirmContent]: 'This clears all checks in current phase. Continue?',
    [K.resetAllConfirmTitle]: 'Confirm full reset',
    [K.resetAllConfirmContent]:
      'This clears all phases and goes back to initial phase. Continue?',
    [K.resetPhaseSuccess]: 'Current phase reset',
    [K.resetAllSuccess]: 'All phases reset',
    [K.refresh]: 'Refresh',
    [K.importFile]: 'Import',
    [K.exportFile]: 'Export',
    [K.more]: 'More',
    [K.selectAircraft]: 'Select Aircraft',
    [K.importSuccess]: 'Checklist imported',
    [K.importFailed]: 'Checklist import failed',
    [K.exportSuccess]: 'Checklist exported',
    [K.exportFailed]: 'Checklist export failed',
    [K.refreshSuccess]: 'Loaded {} aircraft configs',
    [K.refreshEmpty]: 'No checklist config found',
    [K.refreshFailed]: 'Checklist refresh failed',
    [K.autoChecked]: 'SYNC',
    [K.autoCheckedHint]: 'Set automatically from simulator telemetry; tap to take manual control',
    [K.manualOverride]: 'MANUAL',
    [K.manualOverrideHint]: 'Under manual control; tap to hand it back to telemetry sync',
    [K.emptyState]: 'No checklist available',
    [K.phaseColdAndDark]: 'Cold & Dark',
    [K.phaseBeforePushback]: 'Before Pushback',
    [K.phaseBeforeTaxi]: 'Before Taxi',
    [K.phaseBeforeTakeoff]: 'Before Takeoff',
    [K.phaseCruise]: 'Cruise',
    [K.phaseBeforeDescent]: 'Before Descent',
    [K.phaseBeforeApproach]: 'Before Approach',
    [K.phaseAfterLanding]: 'After Landing',
    [K.phaseParking]: 'Parking',
    [K.compactStepPrevious]: 'Previous',
    [K.compactStepCurrent]: 'Current',
    [K.compactStepNext]: 'Next',
    [K.builtInGenericAircraft]: 'Generic Aircraft',
    [K.genericTaskParkingBrake]: 'Parking Brake',
    [K.genericTaskBatteryPower]: 'Battery Power',
    [K.genericTaskAvionics]: 'Avionics',
    [K.genericTaskFlightPlan]: 'Flight Plan',
    [K.genericTaskFlightControls]: 'Flight Controls',
    [K.genericTaskFlaps]: 'Flaps',
    [K.genericTaskInstrumentCheck]: 'Instrument Check',
    [K.genericTaskTakeoffBriefing]: 'Takeoff Briefing',
    [K.genericTaskLights]: 'Lights',
    [K.genericTaskTransponder]: 'Transponder',
    [K.genericTaskEngineParameters]: 'Engine Parameters',
    [K.genericTaskRouteMonitoring]: 'Route Monitoring',
    [K.genericTaskApproachBriefing]: 'Approach Briefing',
    [K.genericTaskLandingData]: 'Landing Data',
    [K.genericResponseSet]: 'Set (SET)',
    [K.genericResponseOn]: 'On (ON)',
    [K.genericResponseChecked]: 'Checked',
    [K.genericResponseCompleted]: 'Completed',
    [K.genericResponseFreeAndCorrect]: 'Free and Correct',
    [K.genericResponseSetAsRequired]: 'Set as Required (SET)',
    [K.genericResponseBriefed]: 'Briefed',
    [K.genericResponseTakeoff]: 'Takeoff Position (SET)',
    [K.genericResponseTaRa]: 'TA/RA',
    [K.genericResponseNormal]: 'Normal',
    [K.genericResponseConfirmed]: 'Confirmed',
    [K.genericResponseUp]: 'Up (UP)',
    [K.genericResponseTaxi]: 'Taxi Position (TAXI)',
  },
};
